/**
 * Moves — what the operator is actually doing, one step below the element:
 * a push, a row, a hang, a glass of water. Every drill, Daily Sets track and
 * Train log kind maps to one, and each move has a pictogram
 * (`components/icons/MoveIcon`, data in `moveGlyphs.json`) that lists,
 * meters, cards and notifications draw in the element's color.
 */
import type {TrackId} from '../program/types';
import type {MetricKind} from '../training/types';

export const MOVE_IDS = [
  'push',
  'pull',
  'row',
  'hang',
  'squat',
  'lunge',
  'wallsit',
  'plank',
  'sideplank',
  'crunch',
  'legraise',
  'bridge',
  'balance',
  'carry',
  'run',
  'walk',
  'jump',
  'kick',
  'posture',
  'chestopener',
  'stretch',
  'hipopener',
  'hamstring',
  'staff',
  'footwork',
  'breath',
  'drink',
  'fuel',
  'presence',
  'intent',
  'evening',
  'pulse',
  'activity',
] as const;

export type MoveId = (typeof MOVE_IDS)[number];

const BY_EXERCISE: Readonly<Record<string, MoveId>> = {
  // Stand-ins for a room with no hang point
  'fire.isometric-door-pull': 'pull',
  'fire.towel-door-row': 'row',
  'fire.feet-up-towel-row': 'row',
  'earth.table-edge-hold': 'hang',
  'earth.towel-pinch-hold': 'hang',
  'earth.reverse-crunch': 'legraise',
  // Kicks, strikes, dance, jumps, hang work, yoga and tai chi
  'fire.front-kick': 'kick',
  'fire.roundhouse-kick': 'kick',
  'fire.side-kick': 'kick',
  'fire.back-kick': 'kick',
  'fire.hook-kick': 'kick',
  'fire.axe-kick': 'kick',
  'fire.crescent-kick': 'kick',
  'fire.knee-strike': 'kick',
  'fire.spin-turn-drill': 'footwork',
  'fire.kick-combo': 'kick',
  'fire.jab-cross': 'activity',
  'fire.hook-uppercut': 'activity',
  'fire.elbow-strikes': 'activity',
  'fire.block-drill': 'activity',
  'fire.parry-slip': 'footwork',
  'fire.combo-flow': 'kick',
  'fire.tuck-jump': 'jump',
  'fire.skater-bound': 'jump',
  'fire.pogo-hops': 'jump',
  'fire.vertical-jump': 'jump',
  'earth.stance-transitions': 'footwork',
  'earth.hollow-rock': 'crunch',
  'earth.rkc-plank': 'plank',
  'earth.copenhagen-plank': 'sideplank',
  'earth.bird-dog': 'plank',
  'earth.suitcase-carry': 'carry',
  'earth.windshield-wiper': 'legraise',
  'earth.dragon-flag-negative': 'legraise',
  'earth.tuck-l-sit': 'legraise',
  'fire.inverted-row': 'row',
  'fire.assisted-pullup': 'pull',
  'fire.pullup-top-hold': 'pull',
  'earth.hanging-tuck-hold': 'hang',
  'earth.grip-shifts': 'hang',
  'earth.warrior-flow': 'lunge',
  'earth.chair-pose': 'squat',
  'earth.tree-pose': 'balance',
  'earth.crow-progression': 'balance',
  'water.body-isolations': 'activity',
  'water.body-wave': 'activity',
  'water.arm-wave': 'activity',
  'water.two-step': 'footwork',
  'water.grapevine': 'footwork',
  'water.toprock': 'footwork',
  'water.house-jack': 'footwork',
  'water.spin-spotting': 'footwork',
  'water.freeze-hold': 'balance',
  'water.groove-combo': 'footwork',
  'water.sun-salutation': 'stretch',
  'water.down-dog-cobra': 'stretch',
  'water.cloud-hands': 'activity',
  'water.brush-knee': 'footwork',
  'water.grasp-sparrows-tail': 'activity',
  'water.tai-chi-walk': 'walk',
  'heart.standing-post': 'presence',
  'heart.flow-performance': 'presence',
  // Mat, backyard, neighborhood, house (added 17 Sep 2026)
  'air.listening-walk': 'walk',
  'air.ruler-drop': 'presence',
  'air.wall-ball-catch': 'footwork',
  'air.stair-breath': 'breath',
  'earth.curb-walk': 'balance',
  'earth.stair-step-up': 'lunge',
  'earth.stair-carry': 'carry',
  'earth.chair-dip': 'push',
  'earth.bear-crawl': 'plank',
  'fire.hill-sprints': 'run',
  'fire.block-loop': 'run',
  'fire.shadow-strikes': 'kick',
  'fire.broad-jump': 'jump',
  'water.juggle-toss': 'activity',
  'water.off-hand-task': 'activity',
  'water.legs-up-the-wall': 'legraise',
  'water.foot-roll': 'stretch',
  'water.hip-cars': 'hipopener',
  'water.shoulder-cars': 'chestopener',
  'heart.voice-work': 'presence',
  'heart.teach-a-move': 'presence',
  'heart.dawn-sit': 'presence',
  // Air
  'air.eye-break': 'presence',
  'air.chin-tuck': 'posture',
  'air.wall-angels': 'posture',
  'air.crocodile-breathing': 'breath',
  'air.standing-belly-release': 'breath',
  'air.doorway-pec-stretch': 'chestopener',
  'air.coherence-breath': 'breath',
  'air.box-breath': 'breath',
  'air.physiological-sigh': 'breath',
  'air.brick-halo': 'posture',
  'air.thread-the-needle': 'chestopener',
  'air.nasal-recovery-walk': 'walk',
  'air.shadow-rope': 'jump',
  'air.long-walk': 'walk',
  'air.leg-swings': 'hamstring',
  // Earth
  'earth.posterior-pelvic-tilt': 'bridge',
  'earth.glute-bridge': 'bridge',
  'earth.couch-stretch': 'hipopener',
  'earth.standing-hip-airplane': 'balance',
  'earth.deadbug': 'legraise',
  'earth.crunch': 'crunch',
  'earth.leg-raise': 'legraise',
  'earth.side-up': 'crunch',
  'earth.plank': 'plank',
  'earth.side-plank': 'sideplank',
  'earth.hollow-hold': 'legraise',
  'earth.squat': 'squat',
  'earth.wall-sit': 'wallsit',
  'earth.cossack-squat': 'lunge',
  'earth.single-leg-balance': 'balance',
  'earth.porch-dead-hang': 'hang',
  'earth.brick-farmer-walk': 'carry',
  'earth.brick-pinch': 'carry',
  'earth.pause-squat': 'squat',
  'earth.split-squat': 'lunge',
  'earth.bulgarian-split-squat': 'lunge',
  'earth.shrimp-squat': 'squat',
  'earth.hanging-knee-raise': 'legraise',
  'earth.hanging-leg-raise': 'legraise',
  'earth.situp': 'crunch',
  'earth.v-up': 'crunch',
  'earth.side-plank-hip-dip': 'sideplank',
  'earth.long-lever-plank': 'plank',
  'earth.active-hang': 'hang',
  'earth.one-arm-assisted-hang': 'hang',
  'earth.plank-test': 'plank',
  'earth.cft-brick-lifts': 'carry',
  'earth.single-leg-glute-bridge': 'bridge',
  'earth.horse-stance': 'wallsit',
  // Fire
  'fire.pushups': 'push',
  'fire.situps': 'crunch',
  'fire.wall-pushups': 'push',
  'fire.kick-flow': 'kick',
  'fire.porch-pullup': 'pull',
  'fire.pullup-negative': 'pull',
  'fire.scap-pull': 'pull',
  'fire.pushup-groove': 'push',
  'fire.jump-squat': 'jump',
  'fire.burpee': 'jump',
  'fire.mountain-climbers': 'plank',
  'fire.backyard-strides': 'run',
  'fire.zone2-run': 'run',
  'fire.run-1.5': 'run',
  'fire.fire-rounds': 'jump',
  'fire.kick-flip-foundations': 'kick',
  'fire.incline-pushup': 'push',
  'fire.diamond-pushup': 'push',
  'fire.decline-pushup': 'push',
  'fire.archer-pushup': 'push',
  'fire.doorframe-row': 'row',
  'fire.one-arm-doorframe-row': 'row',
  'fire.table-row': 'row',
  'fire.brick-pack-pullup': 'pull',
  'fire.pullup-test': 'pull',
  'fire.run-2mi': 'run',
  'fire.run-3mi': 'run',
  'fire.cft-sprint': 'run',
  'fire.cft-maneuver': 'run',
  'fire.interval-run': 'run',
  'fire.tempo-run': 'run',
  // Water
  'water.figure-8': 'staff',
  'water.beat-locks': 'footwork',
  'water.sword-form-slow': 'staff',
  'water.album-no-drop': 'staff',
  'water.sip': 'drink',
  'water.refill': 'drink',
  'water.walk-and-drink': 'drink',
  'water.deep-squat-hold': 'hipopener',
  'water.side-line-stretch': 'stretch',
  'water.worlds-greatest-stretch': 'lunge',
  'water.hamstring-floss': 'hamstring',
  'water.calf-wall-stretch': 'hamstring',
  'water.pancake-reach': 'hamstring',
  'water.pigeon': 'hipopener',
  'water.frog-stretch': 'hipopener',
  'water.front-split-progression': 'lunge',
  'water.beat-step': 'footwork',
  'water.staff-combat-rounds': 'staff',
  'water.hip-flexor-stretch': 'hipopener',
  'water.side-split-progression': 'hipopener',
  // Heart
  'heart.morning-intent': 'intent',
  'heart.mirror-presence': 'presence',
  'heart.evening-review': 'evening',
  'heart.pulse-check': 'pulse',
  'heart.still-sit': 'pulse',
  'heart.single-point-focus': 'presence',
  'heart.fuel-check': 'fuel',
  'heart.rave-vision': 'presence',

  // What you carry (kit/carried.ts, 21 Sep 2026)
  'air.band-pull-apart': 'posture',
  'air.band-face-pull': 'posture',
  'air.band-dislocate': 'chestopener',
  'earth.banded-glute-bridge': 'bridge',
  'earth.band-clamshell': 'bridge',
  'earth.band-lateral-walk': 'walk',
  'fire.band-row': 'row',
  'fire.band-pushup': 'push',
  'fire.band-assisted-pullup': 'pull',
  // A rope swings overhead, so all of it is a jump to the limits.
  'fire.skip-rope': 'jump',
  'fire.skip-rope-intervals': 'jump',
  'air.boxer-skip': 'jump',
  'fire.double-under-progression': 'jump',
  'air.ball-pec-release': 'chestopener',
  'water.ball-glute-release': 'hipopener',
  'earth.jug-farmer-carry': 'carry',
  'earth.jug-goblet-squat': 'squat',
  'fire.jug-row': 'row',
  'earth.sandbag-bear-hug-carry': 'carry',
  'earth.sandbag-zercher-squat': 'squat',
  'fire.sandbag-shouldering': 'carry',

  // What a place has (kit/places.ts)
  'earth.bench-step-up': 'lunge',
  'earth.bench-hip-thrust': 'bridge',
  'fire.bench-jump-up': 'jump',
  'fire.rail-row': 'row',
  'earth.rail-assisted-pistol': 'squat',
  'water.rail-hamstring-stretch': 'hamstring',
  'earth.beam-walk': 'balance',
  'earth.cat-balance': 'balance',
  'fire.precision-jumps': 'jump',
  'fire.monkey-bar-traverse': 'hang',
  'fire.parallel-bar-dips': 'push',
  'earth.bar-l-sit': 'legraise',
  'fire.sand-sprints': 'run',
  'earth.sand-walk-barefoot': 'walk',
  'fire.sand-broad-jumps': 'jump',
  'fire.shoulder-roll': 'activity',
  'fire.breakfall': 'activity',
  // Upside down with the arms overhead: a low ceiling says no.
  'fire.cartwheel': 'jump',
  'fire.hallway-shuttles': 'run',
  'earth.walking-lunges': 'lunge',
  'earth.crawl-lines': 'plank',
  'fire.stair-sprints': 'run',
  'fire.stair-bounds': 'jump',
  'earth.heel-drops': 'balance',
  'fire.kerb-lateral-hops': 'jump',
  'fire.uphill-bounds': 'jump',
  'air.hill-walk': 'walk',

  // Flow toys (kit/flow.ts). Spinning props are the staff's move — the
  // same room, noise and ceiling rules apply — except the contact ball,
  // which needs no room at all.
  'water.poi-weave': 'staff',
  'water.poi-butterfly': 'staff',
  'water.poi-flowers': 'staff',
  'water.hoop-waist': 'staff',
  'water.hoop-isolation': 'staff',
  'water.hoop-flow-round': 'staff',
  'water.fan-reels': 'staff',
  'water.fan-isolations': 'staff',
  'water.wand-float': 'staff',
  'water.wand-orbit': 'staff',
  'water.rope-dart-wheel': 'staff',
  'water.rope-dart-wraps': 'staff',
  'water.contact-palm-spin': 'activity',
  'water.contact-isolation': 'activity',
  'water.contact-butterfly': 'activity',
  'water.buugeng-flips': 'staff',
  'water.buugeng-isolations': 'staff',
  'water.double-staff-windmill': 'staff',
  'water.double-staff-weave': 'staff',
  'water.flow-toy-round': 'staff',
};

const BY_METRIC: Readonly<Record<string, MoveId>> = {
  'builtin.run-3mi': 'run',
  'builtin.run-2mi': 'run',
  'builtin.run-1.5mi': 'run',
  'builtin.run-custom': 'run',
  'builtin.pushups-amrap': 'push',
  'builtin.pushups-2min': 'push',
  'builtin.situps-2min': 'crunch',
  'builtin.pullups-amrap': 'pull',
  'builtin.burpees-2min': 'jump',
  'builtin.breath-hold': 'breath',
  'builtin.exhale-hold': 'breath',
  'builtin.box-breath-2min': 'breath',
  'builtin.skipping-2min': 'jump',
  'builtin.crunches-2min': 'crunch',
  'builtin.leg-hipup': 'legraise',
  'builtin.side-ups-amrap': 'crunch',
  'builtin.squats-amrap': 'squat',
  'builtin.plank': 'plank',
  'builtin.side-plank': 'sideplank',
  'builtin.deadhang': 'hang',
  'builtin.wall-sit': 'wallsit',
  'builtin.farmer-carry': 'carry',
  'builtin.weighted-carry-time': 'carry',
  'builtin.balance-hold': 'balance',
  'builtin.flow-no-drop': 'staff',
  'builtin.flow-hold': 'staff',
  'builtin.deep-squat-hold': 'hipopener',
  'builtin.shoulder-cars': 'posture',
  'builtin.hip-cars': 'hipopener',
  'builtin.still-sit': 'pulse',
  'builtin.staff-session': 'staff',
  'builtin.bike-ride': 'activity',
  'builtin.ruck': 'carry',
  'builtin.walk-session': 'walk',
  'builtin.yoga-video': 'stretch',
  'builtin.tai-chi-video': 'presence',
  'builtin.quiet-cardio-video': 'footwork',
  'builtin.waist': 'activity',
};

const BY_TRACK: Readonly<Record<TrackId, MoveId>> = {
  push: 'push',
  row: 'row',
  pull: 'pull',
  squat: 'squat',
  'legs-up': 'legraise',
  crunch: 'crunch',
  side: 'sideplank',
  plank: 'plank',
  hang: 'hang',
  posture: 'posture',
  breath: 'breath',
  mobility: 'hipopener',
  stillness: 'pulse',
  'push-variants': 'push',
  pelvis: 'bridge',
  kicks: 'hipopener',
  flow: 'activity',
};

export function moveForExercise(id: string | undefined): MoveId | undefined {
  return id ? BY_EXERCISE[id] : undefined;
}

export function moveForTrack(id: string | undefined): MoveId | undefined {
  return id ? BY_TRACK[id as TrackId] : undefined;
}

/** Built-in kinds have their own move; kinds the operator added fall back. */
export function moveForMetric(
  kind: MetricKind | undefined,
): MoveId | undefined {
  if (!kind) {
    return undefined;
  }
  return BY_METRIC[kind.id] ?? (kind.category === 'run' ? 'run' : 'activity');
}
