import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Contact ball, buugeng and levitation wand curricula — the path from
 * first holds to advanced flow, ordered basic → intermediate → advanced
 * within each prop.
 *
 * These sit beside the first drills in `kit/flow.ts` (contact palm
 * circle, isolation and butterfly; buugeng turns and isolations; wand
 * float and orbits), which are slotted into the same path. Moves carry
 * the names practitioners use in tutorials, and each `dose` is the
 * Standard chart. Added 21 Sep 2026.
 *
 * Practice props only. Contact ball starts on a lighter, softer ball over
 * a soft surface: acrylic is heavy and hard when it drops. Head and neck
 * rolls sit at the very end of the contact path, learned in steps, with a
 * stop cue.
 *
 * Contact ball is hand-scale work, offered standing or at the desk, and
 * maps to the activity move. Buugeng and the wand swing out around and
 * above you, so they map to the staff move: a low ceiling or an office
 * rules them out. Every drill is standing work and carries "NoFloor".
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const CONTACT_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.contact-cradle',
    element: 'water',
    name: 'Contact Ball Cradle',
    purpose: 'The first hold: the ball sits on the back of the hand and stays.',
    dose: '2 min each hand',
    cues: [
      'Over a soft surface; start on a lighter, softer ball, not acrylic',
      'Palm down at chest height, fingers straight and together',
      'Dip the middle finger a little: the ball rests on three fingers',
      'Move the arm slowly up, down and round; the ball stays put',
      'Then with the eyes closed, and then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.contact-windshield-wiper',
    element: 'water',
    name: 'Contact Ball Windshield Wiper (cradle to palm)',
    purpose: 'Sends the ball from the back of the hand to the palm and back.',
    dose: '2 min each hand',
    cues: [
      'Over a soft surface; start from a steady cradle, elbow up',
      'A low, gentle arc outward; turn the hand and catch in the open palm',
      'Back the same way into the cradle: a wiper swinging side to side',
      'The shoulder turns the hand, not the wrist; the elbow stays still',
      'The hand stays within 2–5 cm (1–2 in) of the ball the whole way',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.contact-back-to-back',
    element: 'water',
    name: 'Contact Ball Back-to-Back Transfer',
    purpose: 'Rolls the ball from one hand’s cradle to the other’s, no toss.',
    dose: '2 min, both directions',
    cues: [
      'Over a soft surface; the ball in one hand’s cradle',
      'Bring the other hand in underneath, the wrists touching',
      'Look at the empty cradle and tilt the first hand: the ball rolls in',
      'If it runs off the fingertips, tip the fingers up a little',
      'Back the other way; then a slow, steady rhythm between the two',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 120,
    tier: 'basic',
  },
  {
    id: 'water.contact-front-arm-roll',
    element: 'water',
    name: 'Contact Ball Front Arm Roll',
    purpose: 'The first body roll: palm to elbow along the forearm, and back.',
    dose: '10 rolls each arm',
    cues: [
      'Over a soft surface; a bigger, lighter ball rolls more easily',
      'Ball in the palm, forearm pointing straight out in front of you',
      'A small, quick nudge of the forearm gets it over the wrist',
      'Lift the hand; eyes on the elbow; turn the arm if it drifts sideways',
      'Tip the arm forward to roll it slowly back into the palm',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 180,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.contact-two-ball-palm-spin',
    element: 'water',
    name: 'Two-Ball Palm Spin',
    purpose: 'The first multi-ball move: two balls turning round each other.',
    dose: '1 min each direction, each hand',
    cues: [
      'Over a soft surface; two matching balls, not the smallest to start',
      'One ball at the heel of the palm, on the little-finger side',
      'The other held between the thumb, index and side of the middle finger',
      'The fingers lift and lower in turn to roll them round each other',
      'Hand level, speed even; both directions, then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.contact-arm-roll-shoulder',
    element: 'water',
    name: 'Contact Ball Arm Roll to the Shoulder',
    purpose: 'Carries the arm roll to the shoulder: the way into chest rolls.',
    dose: '10 each arm, up and back',
    cues: [
      'Over a soft surface; clean front arm rolls on both arms first',
      'Arm out to the side, palm up; lift the hand above the shoulder',
      'The ball rolls past the elbow and up the upper arm to the shoulder',
      'Lower the hand under it, and it rolls back down into the palm',
      'Slow and even; the ball never stops at a joint',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 180,
    tier: 'intermediate',
  },
  {
    id: 'water.contact-chest-roll',
    element: 'water',
    name: 'Contact Ball Chest Roll',
    purpose: 'Arm to arm across the chest: the classic contact body roll.',
    dose: '10 each direction',
    cues: [
      'Over a soft surface; a larger, lighter stage ball is easiest',
      'Arms out to the sides in one line, palms up, chest lifted',
      'Hand to shoulder first, then shoulder back to hand, on each side',
      'Then the full roll: up one arm, across the upper chest, down the other',
      'Raise the hand behind it, lower the one ahead; catch it in the palm',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.contact-three-ball-palm-spin',
    element: 'water',
    name: 'Three-Ball Palm Spin',
    purpose: 'Turns a triangle of three balls in one open hand.',
    dose: '1 min each direction, each hand',
    cues: [
      'Over a soft surface; three small, matching balls',
      'One ball in the palm at the heel; the fingers hold the other two',
      'Roll the triangle round a finger at a time; the balls stay touching',
      'Hand level and relaxed; even speed matters more than fast',
      'Both directions, then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 240,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.contact-body-roll',
    element: 'water',
    name: 'Contact Ball Linked Body Roll',
    purpose:
      'Chains the rolls into one line: hand, arm, chest, arm, hand, and back.',
    dose: '3 min to one track',
    cues: [
      'Over a soft surface; clean chest rolls both ways first',
      'From a butterfly, take the ball in the palm and send it up the arm',
      'Across the chest, down the far arm and into that hand’s butterfly',
      'Then back the other way, with no stop at either end',
      'A drop is part of practice: pick it up into the next roll',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 180,
    tier: 'advanced',
  },
  {
    id: 'water.contact-four-ball-pyramid',
    element: 'water',
    name: 'Four-Ball Pyramid',
    purpose: 'A three-ball palm spin with a fourth ball riding on top.',
    dose: '1 min each direction, each hand',
    cues: [
      'Over a soft surface; a steady three-ball palm spin both ways first',
      'Set a fourth ball on top of the three to make a pyramid',
      'A slightly smaller top ball sits more steadily while you learn',
      'Tilt the hand to keep the base together while the top ball settles',
      'Turn the base slowly; the top ball rides round in its pocket',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.contact-neck-roll',
    element: 'water',
    name: 'Contact Ball Behind-the-Neck Roll',
    purpose: 'Takes the body roll across the shoulders, out of your own sight.',
    dose: '5 each direction',
    cues: [
      'Clean chest rolls both ways first; a light stage ball, not acrylic',
      'Lean forward, head down, arms out: the shoulders make one track',
      'Roll up one arm to the shoulder and on behind the neck',
      'Lower the far arm to draw it across and down to the far hand',
      'Soft ground; stop if you are straining the neck to keep it there',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 180,
    tier: 'advanced',
  },
  {
    id: 'water.contact-head-roll',
    element: 'water',
    name: 'Contact Ball Head Roll (temple to temple)',
    purpose: 'The hardest body roll: across the forehead, temple to temple.',
    dose: '5 min: holds first, then rolls',
    cues: [
      'Learn on a light, soft ball; a dropped acrylic ball can hurt the face',
      'Forehead hold: tilt the head back and balance the ball in the middle',
      'Temple hold: tilt the head to one side, the ball in the temple’s hollow',
      'Roll: move the head under the ball, temple to forehead to temple',
      'Hands ready; let a falling ball drop, and stop if the neck aches',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const CONTACT_MOVES: Readonly<Record<string, MoveId>> = {
  'water.contact-cradle': 'activity',
  'water.contact-windshield-wiper': 'activity',
  'water.contact-back-to-back': 'activity',
  'water.contact-front-arm-roll': 'activity',
  'water.contact-two-ball-palm-spin': 'activity',
  'water.contact-arm-roll-shoulder': 'activity',
  'water.contact-chest-roll': 'activity',
  'water.contact-three-ball-palm-spin': 'activity',
  'water.contact-body-roll': 'activity',
  'water.contact-four-ball-pyramid': 'activity',
  'water.contact-neck-roll': 'activity',
  'water.contact-head-roll': 'activity',
};

export const BUUGENG_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.buugeng-wheel-spins',
    element: 'water',
    name: 'Buugeng Forward and Backward Spins',
    purpose: 'Sets the side plane: one staff turning cleanly beside you.',
    dose: '2 × 1 min each hand: forward, then backward',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'One staff held at its centre, spinning beside you like a wheel',
      'The wrist turns it; keep the plane flat along your side',
      'Slow enough to see each curve pass the top',
      'Forward, then backward; then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.buugeng-pair-same',
    element: 'water',
    name: 'Buugeng Pair, Same Direction',
    purpose: 'Puts a staff in each hand and keeps the two in step.',
    dose: '3 × 1 min: forward, backward, forward',
    cues: [
      'Practice props only; clear space around and above you',
      'A staff in each hand, one spinning beside each hip like a wheel',
      'Both forward, together: the curves reach the top at the same time',
      'Elbows soft; the wrists do the turning',
      'Then both backward; if they drift out of step, slow down',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 180,
    tier: 'basic',
  },
  {
    id: 'water.buugeng-butterfly',
    element: 'water',
    name: 'Buugeng Butterfly',
    purpose: 'Two staffs in front of you, each the mirror image of the other.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Hands close together at chest height, both staffs flat to the front',
      'Opposite directions, same time: each staff mirrors the other',
      'They pass on slightly different planes, one just in front',
      'Wrists and fingers drive it; the hands barely move',
      'Down the middle, then up the middle',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.buugeng-hand-pass',
    element: 'water',
    name: 'Buugeng Hand-to-Hand Pass',
    purpose: 'Hands the spin from one hand to the other without it stopping.',
    dose: '3 × 1 min, both directions',
    cues: [
      'One staff spinning flat to the front, hands close at chest height',
      'Bring the free hand in and take the centre as the spin comes round',
      'Let go with the first hand only once the second has it',
      'The spin keeps its speed and direction through the pass',
      'Back and forth; then the other direction',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 180,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.buugeng-figure-8',
    element: 'water',
    name: 'Buugeng Figure 8 (one staff)',
    purpose: 'One staff from side to side, the wrist turning over each time.',
    dose: '3 × 1 min each hand',
    cues: [
      'Practice props only; clear a staff length all round',
      'One staff spinning forward beside you like a wheel',
      'Carry it across the front to the other side, still spinning forward',
      'The wrist rolls over as the hand crosses; the elbow stays soft',
      'One side, then the other: the hand draws an 8. Then backward',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },
  {
    id: 'water.buugeng-finger-spin-pair',
    element: 'water',
    name: 'Buugeng Finger Spins (a pair)',
    purpose: 'Takes the finger spin into both hands at once.',
    dose: '3 × 1 min: same way, mirrored, same way',
    cues: [
      'Clean finger spins in each hand, both directions, first',
      'A staff in each hand, flat to the front, turned by the fingers',
      'Same direction, same time; the wrists stay nearly still',
      'Then mirrored: the two staffs turning opposite ways',
      'Slow; if one hand lags, stop that hand and restart it',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 180,
    tier: 'intermediate',
  },
  {
    id: 'water.buugeng-orientations',
    element: 'water',
    name: 'Buugeng Pair Orientations',
    purpose: 'Shows how the way you hold the pair changes the shape they make.',
    dose: '4 × 1 min, one orientation each',
    cues: [
      'A staff in each hand, side by side, flat to the front',
      'Matching: both S shapes the same way round. Mirrored: turn one over',
      'Four ways in all: each staff one way round or the other',
      'Spin them together in each and watch where the curves meet',
      'Curve first, then tip first; a mirror or phone camera shows the shape',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.buugeng-two-beat-weave',
    element: 'water',
    name: 'Buugeng Two-Beat Weave',
    purpose: 'Crosses the two staffs from side to side in a steady count.',
    dose: '3 × 2 min',
    cues: [
      'Practice props only; clear space around and above you',
      'Both staffs spinning forward beside you, split time: one up, one down',
      'One turn with both on the right, then one turn with both on the left',
      'The crossing arm goes over; hands stay close in front of the chest',
      'Count it out loud; a drop is part of practice, so restart the count',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.buugeng-behind-back-pass',
    element: 'water',
    name: 'Buugeng Behind-the-Back Pass',
    purpose: 'Takes the spin behind you, where the hands work blind.',
    dose: '3 × 1 min, both directions',
    cues: [
      'Clean hand-to-hand passes in front first; practice props only',
      'One staff spinning beside you; carry it low behind the hips',
      'The other hand meets it behind you and takes the centre by feel',
      'Let go only once the second hand has it; the spin keeps going',
      'Slow first; a drop behind you is part of practice',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 180,
    tier: 'advanced',
  },
  {
    id: 'water.buugeng-circle',
    element: 'water',
    name: 'Buugeng Circle (two curves, one circle)',
    purpose: 'Joins a curve from each staff into one circle that holds still.',
    dose: '3 × 1 min, both directions',
    cues: [
      'Clean isolations with each staff, both directions, first',
      'Mirror the pair and bring the hands together, one staff just in front',
      'Line up a curve from each so the two halves close into one circle',
      'Keep that circle’s centre still; both hands travel round it together',
      'Slow and flat to the front; if the circle breaks open, slow down',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 180,
    tier: 'advanced',
  },
  {
    id: 'water.buugeng-toss',
    element: 'water',
    name: 'Buugeng Toss and Catch',
    purpose: 'Lets the staff leave the hand for one turn and come back to it.',
    dose: '3 × 10 tosses each hand',
    cues: [
      'Practice props only; soft ground, clear space around and above',
      'One staff spinning flat to the front; release it for a single turn',
      'Low first: no higher than the chest',
      'Catch it at the centre as it comes round; never grab at a tip',
      'Same hand, then across to the other; let a bad toss drop',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.buugeng-combination',
    element: 'water',
    name: 'Buugeng Linked Combination',
    purpose: 'Links the pair moves into one line of flow that never stops.',
    dose: '3 min to one track',
    cues: [
      'Practice props only; clear space around and above you',
      'Pick four moves you own: butterfly, weave, figure 8, a pass',
      'Change on the phrase, not in the middle of one',
      'Every change keeps the spin going: no stop and restart',
      'Recover a drop straight into the next move',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 180,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const BUUGENG_MOVES: Readonly<Record<string, MoveId>> = {
  'water.buugeng-wheel-spins': 'staff',
  'water.buugeng-pair-same': 'staff',
  'water.buugeng-butterfly': 'staff',
  'water.buugeng-hand-pass': 'staff',
  'water.buugeng-figure-8': 'staff',
  'water.buugeng-finger-spin-pair': 'staff',
  'water.buugeng-orientations': 'staff',
  'water.buugeng-two-beat-weave': 'staff',
  'water.buugeng-behind-back-pass': 'staff',
  'water.buugeng-circle': 'staff',
  'water.buugeng-toss': 'staff',
  'water.buugeng-combination': 'staff',
};

export const WAND_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.wand-direction-change',
    element: 'water',
    name: 'Levitation Wand Direction Changes',
    purpose: 'Keeps the float up while the circles change direction.',
    dose: '5 min',
    cues: [
      'Start in a steady float: small, level circles, the thread taut',
      'Slow a circle to a half circle, then draw it back the other way',
      'Half circles are circles too: the thread stays round the top',
      'Change on a beat; the free hand keeps steering',
      'If the wand tips or the thread slips, go back to the float',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'basic',
  },
  {
    id: 'water.wand-wall-circle',
    element: 'water',
    name: 'Levitation Wand Wall-Plane Circle',
    purpose: 'Sends the wand round the hand like a clock hand, flat in front.',
    dose: '5 min, both directions',
    cues: [
      'Clear space in front of you; start from a steady float',
      'Palm facing the floor, the hand drawing small, even circles',
      'The wand travels a bigger circle in front of you and stays upright',
      'Anticlockwise as you see it first, then clockwise',
      'Smooth and slow; a jerk swings the wand and shows the thread',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'basic',
  },
  {
    id: 'water.wand-stall',
    element: 'water',
    name: 'Levitation Wand Stall',
    purpose: 'Stops the wand in the air, then lets it float on again.',
    dose: '5 min, a stall every few circles',
    cues: [
      'From a steady float, bring the free hand to the thread',
      'Rest the back of its fingers on the thread, lightly',
      'The thread now runs at a slant between the hands; the wand hangs',
      'Hold a beat, lift the hand away and float on',
      'Delicate: a heavy hand pulls the wand over',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.wand-vertical-eight',
    element: 'water',
    name: 'Levitation Wand Vertical Eight',
    purpose: 'Lets the wand jump over the leading hand and draws an 8.',
    dose: '5 min',
    cues: [
      'Start in a wall-plane circle, anticlockwise as you see it, palm down',
      'As the wand reaches 12 o’clock, wave the hand as if saying hello',
      'The wand jumps over the arm; drop the elbow a little to clear it',
      'Bring the palm back to finish; the hand has drawn an 8',
      'Slow and even; if it catches the arm, go back to the circle',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'water.wand-overhead-circle',
    element: 'water',
    name: 'Levitation Wand Overhead Circle',
    purpose: 'Lifts the circling wand up above your head, and back down.',
    dose: '5 min, both directions',
    cues: [
      'Clear space above you; start from a steady float',
      'Raise the thread hand slowly, still drawing the same small circles',
      'The wand circles above your head; the free hand follows it up',
      'Keep the thread away from the face and neck',
      'Lower slowly back into the float; then the other direction',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'water.wand-behind-back-stall',
    element: 'water',
    name: 'Levitation Wand Behind-the-Back Stall',
    purpose: 'Stalls the wand behind you, finding the thread by feel.',
    dose: '5 min, a stall every few circles',
    cues: [
      'Clean front stalls first; clear space behind you',
      'Float the wand round your side until both hands are behind you',
      'The free hand finds the thread and rests on it, lightly',
      'Lost it? Bring the hands together behind you, then slide out to it',
      'Hold a beat, release, and float back round to the front',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.wand-linked-flow',
    element: 'water',
    name: 'Levitation Wand Linked Flow',
    purpose: 'Links float, circles, eights and stalls into one line of flow.',
    dose: '3 min to one track',
    cues: [
      'Clear space around and above you; start in a float',
      'Add a circle, an eight, an orbit and a stall, in any order',
      'Change on the phrase, not in the middle of one',
      'Link through a circle each time; the wand stays up while it circles',
      'If it tangles, stop, free it and restart from the float',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 180,
    tier: 'advanced',
  },
  {
    id: 'water.wand-long-string',
    element: 'water',
    name: 'Levitation Wand Long String',
    purpose: 'A longer thread lets the wand travel farther from the hand.',
    dose: '5 min',
    cues: [
      'Fit the longer thread as your wand’s instructions say',
      'Float and circle first, bigger and slower than on the short thread',
      'Let the wand travel out and back; the hand stays smooth',
      'More thread tangles more: keep it clear of the neck and face',
      'If it knots, stop and free it; short thread again any time',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.wand-doubles',
    element: 'water',
    name: 'Levitation Wand Doubles',
    purpose: 'A wand on each hand: two floats that move as a pair.',
    dose: '5 min',
    cues: [
      'Two wands, a thread on each hand; clear space around you',
      'Start each into a float, one at a time',
      'Same direction first, then mirrored: the hands circle opposite ways',
      'Hands far enough apart that the threads never cross',
      'If they tangle, stop, free them and restart one at a time',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const WAND_MOVES: Readonly<Record<string, MoveId>> = {
  'water.wand-direction-change': 'staff',
  'water.wand-wall-circle': 'staff',
  'water.wand-stall': 'staff',
  'water.wand-vertical-eight': 'staff',
  'water.wand-overhead-circle': 'staff',
  'water.wand-behind-back-stall': 'staff',
  'water.wand-linked-flow': 'staff',
  'water.wand-long-string': 'staff',
  'water.wand-doubles': 'staff',
};
