import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Dance combat — fighting as dance, to music.
 *
 * Capoeira from the ginga up, combinations on the beat, kicks linked by
 * steps and spins, tricking, and the staff. The path runs basic to
 * advanced, easiest first within each tier; the slow sword form and the
 * staff combat rounds, written before the path existed, are slotted in
 * beside these in `../disciplines.ts`. Added 21 Sep 2026.
 *
 * Solo work only: shadow work, flow and form. No partner, no contact, no
 * sparring. Practice staffs only.
 *
 * Power-led moves (kicks, tricks, strike combinations) are fire; flow-led
 * ones are water. Aerials and anything upside down want grass or a mat,
 * and each carries its own progression and a "stop if" cue.
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const DANCE_COMBAT_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.capoeira-ginga',
    element: 'water',
    name: 'Capoeira Ginga',
    purpose:
      'The rocking step every capoeira move comes out of and goes back to.',
    dose: '3 × 2 min to one track',
    cues: [
      'Feet wide, knees bent: step one foot back into a low, wide lunge',
      'The arm on the back leg’s side comes up across the face',
      'Bring that foot forward level again, then step the other one back',
      'Low and never still: the feet draw a triangle on the ground',
      'The music sets the speed: a slow track means a lower, slower ginga',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'basic',
  },
  {
    id: 'fire.combat-flow-beat-combos',
    element: 'fire',
    name: 'Shadowboxing on the Beat',
    purpose: 'Puts the hands on the music: strikes on the beat, steps between.',
    dose: '3 × 2 min rounds, 30 sec easy bounce between',
    cues: [
      'Guard up, knees soft, a small bounce in time with the track',
      'One strike per beat: jab; jab, cross; jab, cross, hook',
      'Strikes land on the beat; step or slide in the counts between',
      'Each strike comes back to the guard the way it went out',
      'Change the combination when the phrase changes, every eight counts',
    ],
    targets: ['Conditioning', 'Coordination', 'Flow', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'basic',
  },
  {
    id: 'water.capoeira-esquivas',
    element: 'water',
    name: 'Capoeira Esquivas (lateral, baixa, cocorinha)',
    purpose:
      'Teaches you to drop out of the way and come straight back to the ginga.',
    dose: '3 × 2 min from the ginga, both sides',
    cues: [
      'From the ginga, drop on the beat; eyes stay forward the whole time',
      'Lateral: sink to one side, chest toward that knee, a hand over the head',
      'Baixa: the back leg reaches further back, a hand down by the front foot',
      'Cocorinha: squat on the whole foot, one hand guarding the head',
      'Come back up into the ginga, not to standing; then the other side',
    ],
    targets: ['Agility', 'Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.staff-dance-combat-guards',
    element: 'water',
    name: 'Staff Guard Flow',
    purpose:
      'Teaches the staff to travel between guards in time with the music.',
    dose: '3 × 2 min to one track',
    cues: [
      'Practice staff only; clear the staff’s length all round, and above',
      'Hands in thirds, one palm up and one palm down',
      'High guard across the forehead, low across the hips, upright each side',
      'Change guard on the beat with a step; land it, then go on to the next',
      'Turn from the hips; the arms follow and the grip stays loose',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'fire.capoeira-meia-lua-de-frente',
    element: 'fire',
    name: 'Meia Lua de Frente',
    purpose: 'The first capoeira kick: a straight leg sweeping a half-moon.',
    dose: '3 × 5 each leg, from the ginga',
    cues: [
      'From the ginga, the back leg swings up straight and out to its side',
      'It sweeps across in front of you, outside to inside: a half-moon',
      'Hips stay square to the front; one arm stays up by the face',
      'Put the foot back where it came from and carry on the ginga',
      'Waist height first; height comes from the hips, not from leaning',
    ],
    targets: ['Agility', 'Coordination', 'Flow', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'fire.capoeira-queixada',
    element: 'fire',
    name: 'Queixada',
    purpose:
      'The half-moon the other way: a step, a twist and an outward sweep.',
    dose: '3 × 5 each leg, from the ginga',
    cues: [
      'From the ginga, twist so your side faces forward, knees bent',
      'Step the back foot forward and across; the weight goes onto it',
      'As it lands, the other leg swings up straight, inside to outside',
      'A wide arc, the outer edge of the foot leading; arms up throughout',
      'Land it back into the ginga; then the other side',
    ],
    targets: ['Agility', 'Coordination', 'Flow', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.capoeira-negativa-role',
    element: 'water',
    name: 'Negativa and Rolê',
    purpose:
      'The low ground position, and the turn that carries you out of it.',
    dose: '6 each side: negativa, rolê, up into the ginga',
    cues: [
      'Grass or a mat; the hands go down, so check the ground first',
      'Negativa: sink onto the ball of one foot, the other leg long in front',
      'That leg’s hand goes down by the hip, not behind; weight forward',
      'Rolê: both hands down, turn over them, the legs sweep round low',
      'Rise into the ginga; eyes forward the whole time, not on the floor',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Strength'],
    venues: ['yard'],
    approxSeconds: 240,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.combat-flow-slips-pivots',
    element: 'water',
    name: 'Shadowboxing Flow (slips, rolls, pivots)',
    purpose:
      'Joins the combinations to the moves between them, so nothing stops.',
    dose: '3 × 2 min rounds, 30 sec easy bounce between',
    cues: [
      'Two or three strikes on the beat, then answer an imagined one',
      'Slip: the head moves just off the line, knees bent, eyes forward',
      'Roll: bend the knees and trace a U under an imagined hook',
      'Pivot on the front foot to a new angle and start the next combination',
      'Breathe out on every strike; keep moving, never reset to still',
    ],
    targets: ['Flow', 'Agility', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-dance-combat-spin-strike',
    element: 'water',
    name: 'Staff Spin to Strike',
    purpose:
      'Turns the end of a spin into a strike, and the strike into a spin.',
    dose: '3 × 2 min, each side leading',
    cues: [
      'Practice staff only; clear the staff’s length all round, and above',
      'A figure 8 at your side, one hand near the centre of the staff',
      'On the beat, the other hand joins and the turn becomes a strike',
      'Push with the front hand, pull with the back; the step lands with it',
      'The strike carries on round into the next spin: no dead stops',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'fire.capoeira-armada',
    element: 'fire',
    name: 'Armada',
    purpose: 'Capoeira’s spinning kick: head, then hips, then a straight leg.',
    dose: '3 × 5 each side, from the ginga',
    cues: [
      'From the ginga, step the back foot across and turn your back forward',
      'Head first: look over your shoulder to where you started facing',
      'Then shoulders and hips; the far leg swings round, straight and wide',
      'The outside edge of the foot leads; land it back into the ginga',
      'Waist height and slow first; spot the same point every time',
    ],
    targets: ['Agility', 'Coordination', 'Flow', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'fire.combat-flow-kick-chain',
    element: 'fire',
    name: 'Kick Chain (steps and spins on the beat)',
    purpose: 'Links kicks with steps and turns, so each lands into the next.',
    dose: '4 × 1 min, switching the lead leg each round',
    cues: [
      'Clear room to travel: 5 m (16 ft) in front of you',
      'Front kick, then put the foot down forward, not back where it started',
      'Round kick with the back leg, and land that one forward too',
      'Turn your back, look over your shoulder, then a back kick with the heel',
      'One kick per two beats; steps and turns fill the counts between',
    ],
    targets: ['Agility', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'water.capoeira-au',
    element: 'water',
    name: 'Aú (capoeira cartwheel)',
    purpose:
      'The capoeira cartwheel, built in steps: slow, low and eyes forward.',
    dose: '3 × 5 each side at your current step',
    cues: [
      'Grass or a mat; warm the wrists and shoulders first',
      'First a hand down by the front foot as the back leg kicks up and lands',
      'Then both hands in turn, legs bent and low; straighter only when clean',
      'Arms straight, shoulders pushed up; land one foot, then the other',
      'Eyes forward, not on the floor; stop if a wrist or shoulder hurts',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'fire.tricking-tornado-kick',
    element: 'fire',
    name: 'Tornado Kick',
    purpose: 'The first tricking kick: a step, a turn, a jumping round kick.',
    dose: '5 × 3, full rest between',
    cues: [
      'Grass only, after a full warm-up; stop if a landing twists the knee',
      'Face the target; step across so your back turns to it, and keep turning',
      'Drive the other knee up and jump off the stepping foot',
      'In the air, the stepping leg swings a round kick; land on the other',
      'Build it: turn and hop with no kick, then a low kick, then height',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'fire.tricking-pop-360',
    element: 'fire',
    name: 'Pop 360 Kick',
    purpose: 'A jump off both feet that turns into an outside crescent kick.',
    dose: '5 × 3, full rest between',
    cues: [
      'Grass only, after a full warm-up; stop if a landing twists the knee',
      'Step to the side, then step across so your back turns to the target',
      'Jump off both feet and turn the last half in the air',
      'The leg on the side you turn toward sweeps an outside crescent',
      'Land soft on both feet; learn the turning jump before adding the kick',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'fire.capoeira-meia-lua-de-compasso',
    element: 'fire',
    name: 'Meia Lua de Compasso',
    purpose:
      'Capoeira’s spinning heel kick, thrown with both hands on the floor.',
    dose: '3 × 5 each side, from the ginga',
    cues: [
      'Grass or a mat; warm the hips and the backs of the legs first',
      'From the ginga, drop the chest and put both hands on the floor',
      'Watch the spot you started facing, looking through your hands',
      'The back leg swings round, straight and wide, heel leading',
      'Rise into the ginga; stop if the low back or a hamstring pulls',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-dance-combat-back-pass',
    element: 'water',
    name: 'Staff Back Pass to Strike',
    purpose:
      'Takes the staff behind your back and out the far side as a strike.',
    dose: '3 × 2 min, both directions',
    cues: [
      'Practice staff only; clear the staff’s length all round, and above',
      'Learn the pass still first: hand to hand behind the waist, no spin',
      'From a spin at your side, pass it behind your back to the other hand',
      'It comes out the far side already moving: let that be the strike',
      'Slow until the catch behind you is sure; a drop is part of practice',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.capoeira-solo-game',
    element: 'water',
    name: 'Capoeira Solo Game',
    purpose:
      'Plays capoeira with an imagined partner: every move answers another.',
    dose: '2 tracks, a short walk between',
    cues: [
      'Grass, with room all round; everything starts and ends in the ginga',
      'Send a kick, then dodge the one your imagined partner sends back',
      'Change levels: meia lua high, esquiva low, negativa, rolê out',
      'Aú only on soft ground, and only once it is clean on its own',
      'A slower track means a lower, slower game; the ginga never stops',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'Presence'],
    venues: ['yard'],
    approxSeconds: 600,
    tier: 'advanced',
  },
  {
    id: 'water.combat-flow-round',
    element: 'water',
    name: 'Combat Flow Round',
    purpose: 'All your strikes, kicks, turns and steps in one track, no stops.',
    dose: '1 track (3–5 min), no stops',
    cues: [
      'Clear space all round; grass if tricks or ground moves come in',
      'Long combinations: four to eight moves before you settle the guard',
      'Hands on the beat, kicks and spins on the accents, steps between',
      'Through the breakdowns keep moving: bounce, ginga or step in place',
      'Pick the track first and play it to the end; slow and clean beats fast',
    ],
    targets: [
      'Flow',
      'Conditioning',
      'Coordination',
      'Agility',
      'Presence',
      'NoFloor',
    ],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-dance-combat-freestyle',
    element: 'water',
    name: 'Staff Combat Flow Freestyle',
    purpose: 'Spins, strikes, guards and passes, freestyled to one track.',
    dose: '1 track (3–5 min)',
    cues: [
      'Practice staff only; clear the staff’s length plus a step all round',
      'No plan: spins ride the melody, strikes land on the beat',
      'Move through guards, turns and back passes; the staff never stops dead',
      'Use the whole space: step in, back and round; change levels',
      'A drop is part of practice: pick it up into the next move',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'fire.tricking-butterfly-kick',
    element: 'fire',
    name: 'Butterfly Kick',
    purpose: 'The flat, spinning jump that most twisting tricks grow out of.',
    dose: '5 × 3, full rest between',
    cues: [
      'Grass or a mat, fresh legs; a clean aú and tornado kick come first',
      'Feet wide, chest down level with the floor, arms swinging across',
      'Build it: the wind-up alone, then the back leg swinging, then the hop',
      'The back leg swings up and round first, the other follows; chest down',
      'First leg up, first leg down; stop if a landing twists or jars',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 360,
    tier: 'advanced',
  },
  {
    id: 'fire.tricking-540-kick',
    element: 'fire',
    name: '540 Kick',
    purpose: 'A tornado kick that turns further and lands on the kicking leg.',
    dose: '5 × 2, full rest between',
    cues: [
      'Grass or a mat, fresh legs; a high, clean tornado kick comes first',
      'Build it: a low, fast tornado that kicks through onto the kicking foot',
      'Then the full turn with the kicking knee bent, then with the leg long',
      'Spot the target on take-off, and again as you come round to land',
      'Land on the kicking leg, knee soft; stop if a knee or ankle twists',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const DANCE_COMBAT_MOVES: Readonly<Record<string, MoveId>> = {
  'water.capoeira-ginga': 'footwork',
  'fire.combat-flow-beat-combos': 'activity',
  'water.capoeira-esquivas': 'footwork',
  'water.staff-dance-combat-guards': 'staff',
  'fire.capoeira-meia-lua-de-frente': 'kick',
  'fire.capoeira-queixada': 'kick',
  'water.capoeira-negativa-role': 'footwork',
  'water.combat-flow-slips-pivots': 'activity',
  'water.staff-dance-combat-spin-strike': 'staff',
  'fire.capoeira-armada': 'kick',
  'fire.combat-flow-kick-chain': 'kick',
  'water.capoeira-au': 'jump',
  'fire.tricking-tornado-kick': 'jump',
  'fire.tricking-pop-360': 'jump',
  'fire.capoeira-meia-lua-de-compasso': 'kick',
  'water.staff-dance-combat-back-pass': 'staff',
  'water.capoeira-solo-game': 'kick',
  'water.combat-flow-round': 'kick',
  'water.staff-dance-combat-freestyle': 'staff',
  'fire.tricking-butterfly-kick': 'jump',
  'fire.tricking-540-kick': 'jump',
};
