import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Dance — the styles people actually dance at raves and festivals.
 *
 * House, shuffle and cutting shapes, popping and animation, liquid,
 * hip-hop grooves, jumpstyle, and the breaking foundations that suit a
 * rave floor, laid out as one path from first steps to advanced. They
 * slot in beside the dance drills already in `library.ts` and
 * `kit/mirror.ts`: isolations, the body and arm waves, the two-step, the
 * grapevine, toprock, the Jack, spins, freezes, beat-step and the groove
 * combo. Added 21 Sep 2026.
 *
 * No fighting here: dance combat has its own file.
 *
 * Standing steps carry "NoFloor". The floorwork (six-step, baby freeze,
 * lofting) needs a mat or a smooth floor, and is the only work here that
 * does not. Jumpstyle is loud, so it drops "house" and says so in a cue.
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const DANCE_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.hiphop-bounce-rock',
    element: 'water',
    name: 'Hip-Hop Bounce and Rock',
    purpose: 'The basic hip-hop grooves for keeping time with your body.',
    dose: '3 × 1 min to one track',
    cues: [
      'Hip-hop: feet shoulder-width apart, knees soft, shoulders loose',
      'Down bounce: bend the knees on every beat and rise between',
      'Up bounce: straighten the knees on the beat instead',
      'Rock: tip the chest forward and back from the hips, once per beat',
      'Keep the bounce and the rock while you step side to side',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.house-stomp',
    element: 'water',
    name: 'House Stomp',
    purpose: 'A march on the beat, the base of house footwork.',
    dose: '3 × 1 min to one track',
    cues: [
      'House: march in place on the beat, each foot landing flat',
      'Stomp on 1: lift the knee a little higher and land the whole foot',
      'Move the stomp: on 1, then on 1 and 5, then on 1, 3, 5 and 7',
      'Add the Jack: drop the chest with every stomp',
      'Indoors, keep it quiet: take the weight in your knees',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.house-side-jack',
    element: 'water',
    name: 'House Side Jack',
    purpose: 'The Jack done sideways, so you can travel with it.',
    dose: '3 × 1 min: side jacks, then front and side mixed',
    cues: [
      'House: start with the front Jack, then do the same move sideways',
      'Step out to one side; move the hips first, then the chest',
      'Bend the knees slightly on every beat; keep the shoulders level',
      'Do four to each side, then change side on every beat',
      'Mix them in one eight-count: front, front, side, side',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.dance-liquid-flow',
    element: 'water',
    name: 'Liquid Dance: Hand Flow and Contours',
    purpose: 'A smooth rave dance style where the hands never stop.',
    dose: '3 × 1 min to a slow, melodic track',
    cues: [
      'Liquid: hands and arms only at first; stand tall, shoulders loose',
      'Hand flow: circle and slide the hands round each other, not touching',
      'Contours: trace the outline of your head or an imaginary ball',
      'Keep one even speed the whole time, with no stops or jerks',
      'Follow the melody, not the kick drum',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.popping-fresno',
    element: 'water',
    name: 'Popping Hits and the Fresno',
    purpose: 'Teaches the pop: tensing and releasing a muscle on the beat.',
    dose: '3 × 1 min to a slow, funky track',
    cues: [
      'Popping: a hit is a quick tense and release of a muscle, on the beat',
      'Hit the forearms and triceps first, then the chest, then the thighs',
      'Tense on the beat, then release at once; the release makes it visible',
      'Fresno: step to one side and hit twice, then step to the other side',
      'Land the step and the hit together; stay slow until every hit is clean',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.shuffle-running-man',
    element: 'water',
    name: 'Shuffle Running Man',
    purpose: 'The first shuffle step, with the rhythm all shuffle steps use.',
    dose: '4 × 1 min to one track',
    cues: [
      'Shuffle: on the balls of the feet, knees soft, steps small',
      'Stand on one foot with the other knee lifted',
      'Put the lifted foot down in front as the standing foot slides back',
      'Lift the back foot into the next knee lift as the front foot slides in',
      'Step it without the slide first; add the slide once the count is even',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 330,
    tier: 'basic',
  },
  {
    id: 'water.house-heel-toe',
    element: 'water',
    name: 'House Heel-Toe',
    purpose:
      'Moves you sideways by turning on the heels and balls of the feet.',
    dose: '4 × 1 min, both directions',
    cues: [
      'House: feet together, knees soft, weight slightly behind centre',
      'Turn one foot on its heel and the other on its ball; the toes split',
      'Swap: turn each foot on its other end so they close parallel',
      'Each swap moves you sideways: eight counts one way, eight back',
      'Spring off the floor lightly; forcing it slows you down',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 300,
    tier: 'basic',
  },
  {
    id: 'water.shuffle-t-step',
    element: 'water',
    name: 'Shuffle T-Step',
    purpose: 'The sideways shuffle glide that most combos start from.',
    dose: '4 × 1 min, leading each side in turn',
    cues: [
      'Shuffle: stand on one foot, the other knee lifted a little',
      'Kick the free foot out to the side, then back in to the standing arch',
      'Swivel the standing foot as you go: toes out, then heel out',
      'The swivels move you sideways; the foot coming in forms the T',
      'After eight counts, switch feet and glide back the other way',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 330,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.hiphop-party-grooves',
    element: 'water',
    name: 'Hip-Hop Party Grooves (Wop, Cabbage Patch)',
    purpose: 'Two classic party grooves, linked together to one track.',
    dose: '3 min to one track',
    cues: [
      'Hip-hop: find the bounce first; do both grooves on top of it',
      'Wop: sway to one side each beat, bend the knees, drop that shoulder',
      'Swing the far arm across the chest: body goes down, hand comes up',
      'Cabbage Patch: circle fists flat at the chest; lift that side’s heel',
      'Link them: eight Wop, eight Cabbage Patch, eight bounce, repeat',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 180,
    tier: 'intermediate',
  },
  {
    id: 'water.house-skate',
    element: 'water',
    name: 'House Skate',
    purpose: 'A continuous glide from foot to foot.',
    dose: '3 × 1 min: in place, then travelling',
    cues: [
      'House: weight on one foot, knees soft, torso upright',
      'Glide the other foot out, forward and to the side, on its ball',
      'Draw it in, take your weight on it, and glide the first foot out',
      'Keep it continuous; do not stop between steps',
      'Swing the arms gently opposite the legs; then travel forward and back',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.house-pas-de-bourree',
    element: 'water',
    name: 'House Pas de Bourrée',
    purpose:
      'Behind, side, front: three quick steps that change your lead foot.',
    dose: '4 × 1 min, both sides',
    cues: [
      'House: keep the Jack’s bounce going throughout',
      'Step one foot behind, then the other out to the side',
      'Step the first foot down in front; then start with the other foot',
      'Up, up, down: the first two on the balls, the third settles',
      'Then drag the foot in front or behind instead of stepping',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'water.popping-dime-stops',
    element: 'water',
    name: 'Popping Dime Stops',
    purpose: 'Teaches fast moves that stop dead, with no wobble.',
    dose: '3 × 1 min to a slow track',
    cues: [
      'Popping: a dime stop is a fast move that stops dead, with no shake',
      'Do not hit; the stop stays clean because nothing tenses',
      'Move the head left and stop, right and stop, one move per beat',
      'Then move a hand across the body and stop it dead on each count',
      'Mix them: stop, stop, hit',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.cutting-shapes-charleston',
    element: 'water',
    name: 'Cutting Shapes Charleston',
    purpose:
      'The twist and tap that cutting shapes is built on, danced to house.',
    dose: '4 × 1 min, both feet',
    cues: [
      'Cutting shapes: small, bouncy and twisting, on the balls of the feet',
      'Twist: feet apart, toes in; cross one foot in front, toes out; back',
      'Charleston: on one foot, tap the free foot forward, then behind you',
      'Swivel the standing heel with each tap so the knees open and close',
      'Link the twist into the Charleston and switch feet on the beat',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 330,
    tier: 'intermediate',
  },
  {
    id: 'water.house-farmer',
    element: 'water',
    name: 'House Farmer',
    purpose:
      'A bouncing house step: a hop, a low knee and a stamp on the beat.',
    dose: '3 × 1 min, both sides',
    cues: [
      'House: learn the stomp first; this is a bouncing version of it',
      'Hop to one side and lift the other knee, low',
      'Set that foot down beside you on the beat; keep your weight in place',
      'Hop back the other way and repeat; keep it low and grounded',
      'Learn it slowly in parts, then join them into one eight-count',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.shuffle-kick-outs',
    element: 'water',
    name: 'Shuffle Kick-Outs',
    purpose: 'Quick switching kicks that add speed to your shuffle.',
    dose: '4 × 30 sec on, 30 sec easy',
    cues: [
      'Shuffle: light hops on the balls of the feet, upper body calm',
      'Hop on one foot as the other kicks out low in front, knee soft',
      'Switch with a small hop: that foot lands as the other kicks out',
      'Then kick out to the side and bring the foot back in beside you',
      'Link them into the running man and T-step without losing the count',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.jumpstyle-basic',
    element: 'water',
    name: 'Jumpstyle Basic',
    purpose: 'The basic hardstyle step: small jumps and kicks on the beat.',
    dose: '4 × 1 min, 1 min easy between',
    cues: [
      'Loud: neighbours below hear every landing; use a yard or ground floor',
      'Jumpstyle: small, springy jumps; keep the upper body calm',
      'Hop and kick one leg forward, then hop and kick it back behind you',
      'Land on both feet, then repeat with the other leg',
      'Land with soft knees; keep jumps small to stay on time at speed',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['standing', 'yard'],
    approxSeconds: 420,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.house-loose-legs',
    element: 'water',
    name: 'House Loose Legs',
    purpose: 'Fast footwork done on relaxed, loose legs.',
    dose: '4 × 1 min, both legs',
    cues: [
      'House: learn heel-toe and the stomp first; this builds on them',
      'Hop lightly on one foot as the other leg swings out to the side',
      'Keep the knee and ankle loose so the foot flicks out and swings back',
      'Do two swings, then change feet; then three, then four',
      'Stay on the balls of the feet; aim for looseness, not height',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 330,
    tier: 'advanced',
  },
  {
    id: 'water.dance-liquid-threads',
    element: 'water',
    name: 'Liquid Dance: Threads and Builds',
    purpose: 'Makes holes and objects in the air look real.',
    dose: '3 min threads, then 3 min builds',
    cues: [
      'Liquid: loop the arms into a hole that stays still in the air',
      'Threads: pass a hand, then the head, through the hole as if it is real',
      'Keep the hole fixed in space while the body passes through it',
      'Builds: shape an object in the air; keep its size the same as it moves',
      'Move smoothly and evenly; film it to check the illusion works',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 360,
    tier: 'advanced',
  },
  {
    id: 'water.popping-strobing',
    element: 'water',
    name: 'Animation Strobing (popping)',
    purpose: 'Breaks a smooth move into tiny moves and dead stops.',
    dose: '3 × 1 min to a slow track',
    cues: [
      'Animation: strobing breaks one smooth move into many small ones',
      'Raise an arm slowly in steps 2–3 cm (1 in) apart: move, stop dead',
      'Space the stops evenly; time them to the hi-hats',
      'Then strobe a walk or turn, the whole body stopping at once',
      'Film it to spot drift and uneven stops you cannot feel',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.shuffle-spins',
    element: 'water',
    name: 'Shuffle Spins',
    purpose: 'Spins that land on the beat, straight into the next step.',
    dose: '8 each direction',
    cues: [
      'Shuffle: learn Spins and Spotting first; spot every turn here too',
      'T-step spin: keep kicking and swivelling round a small circle',
      'Then spin a quick 360 on the ball of one foot, arms pulled in',
      'Land straight into the running man, on the beat, with no extra step',
      'Spin both directions; use a clear, dry floor, never a wet one',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.breaking-six-step',
    element: 'water',
    name: 'Breaking Six-Step',
    purpose: 'Basic breaking footwork: your legs circle round your hands.',
    dose: '5 rounds each direction',
    cues: [
      'Breaking: on a mat or smooth floor; circle and warm the wrists first',
      'Crouch on the balls of the feet, one hand down, fingertips spread',
      'Walk the legs in a full circle around the hands in six steps',
      'Take your weight on one hand at a time; both only at step 3',
      'Learn it tall, then low; stop if a wrist aches',
    ],
    targets: ['Agility', 'Strength', 'Coordination', 'Conditioning'],
    venues: ['mat'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.breaking-baby-freeze',
    element: 'water',
    name: 'Breaking Baby Freeze',
    purpose:
      'The first breaking freeze: balanced on your hands, feet in the air.',
    dose: '5 holds of up to 10 sec',
    cues: [
      'Breaking: use a mat, after the six-step; circle and warm the wrists',
      'Squat and put your hands down shoulder-width apart, fingers spread',
      'Tuck one elbow into your hip; rest the other knee on the other elbow',
      'Tip forward until the side of your head just touches; lift the feet',
      'Stop if the neck takes weight or a wrist hurts; lower the feet first',
    ],
    targets: ['Strength', 'Coordination', 'Flow'],
    venues: ['mat'],
    approxSeconds: 180,
    tier: 'advanced',
  },
  {
    id: 'water.house-lofting',
    element: 'water',
    name: 'House Lofting: Floor Spins and Slides',
    purpose: 'House spins and slides on the floor, rising back into the step.',
    dose: '3 × 1 min to an easy track',
    cues: [
      'House lofting: use a smooth floor or mat; warm the knees and wrists',
      'Never drop onto a knee: lower through a deep squat onto one hand',
      'Spin on the seat or hip, knees tucked, one hand pushing you round',
      'Slide out along the floor, then rise through a crouch onto the beat',
      'Start at half speed; stop if a knee or wrist gets knocked',
    ],
    targets: ['Flow', 'Agility', 'Coordination', 'Strength'],
    venues: ['mat'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.dance-style-switch',
    element: 'water',
    name: 'Dance Style-Switch Round',
    purpose: 'Practise changing dance style when the music changes.',
    dose: '2 tracks, back to back',
    cues: [
      'Use any styles you know: house, shuffle, popping, liquid, hip-hop',
      'Switch style at each new phrase, every 8 or 16 bars',
      'Match the music: footwork on the drums, liquid on the melody',
      'Change on the beat; use the last move of one style to start the next',
      'Give your weakest style its own phrase every round',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 600,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const DANCE_MOVES: Readonly<Record<string, MoveId>> = {
  'water.hiphop-bounce-rock': 'footwork',
  'water.house-stomp': 'footwork',
  'water.house-side-jack': 'footwork',
  'water.dance-liquid-flow': 'activity',
  'water.popping-fresno': 'activity',
  'water.shuffle-running-man': 'footwork',
  'water.house-heel-toe': 'footwork',
  'water.shuffle-t-step': 'footwork',
  'water.hiphop-party-grooves': 'footwork',
  'water.house-skate': 'footwork',
  'water.house-pas-de-bourree': 'footwork',
  'water.popping-dime-stops': 'activity',
  'water.cutting-shapes-charleston': 'footwork',
  'water.house-farmer': 'footwork',
  'water.shuffle-kick-outs': 'footwork',
  'water.jumpstyle-basic': 'jump',
  'water.house-loose-legs': 'footwork',
  'water.dance-liquid-threads': 'activity',
  'water.popping-strobing': 'activity',
  'water.shuffle-spins': 'footwork',
  'water.breaking-six-step': 'footwork',
  'water.breaking-baby-freeze': 'balance',
  'water.house-lofting': 'footwork',
  'water.dance-style-switch': 'footwork',
};
