import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Dance combat — fighting as dance, to music.
 *
 * Capoeira from the ginga up, combinations on the beat, kicks linked by
 * steps and spins, tricking, and the staff. The path runs basic to
 * advanced, easiest first within each tier; the slow sword form and the
 * staff combat rounds, written before the path existed, are slotted in
 * beside these in `../disciplines.ts`. Added 21 Sep 2026.
 *
 * Solo work only: shadow work, flow and form. No partner, no contact, no
 * sparring. Practice staffs only.
 *
 * Power-led moves (kicks, tricks, strike combinations) are fire; flow-led
 * ones are water. Aerials and anything upside down want grass or a mat,
 * and each carries its own progression and a "stop if" cue.
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const DANCE_COMBAT_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.capoeira-ginga',
    element: 'water',
    name: 'Capoeira Ginga',
    purpose: 'The basic capoeira step; every move starts and ends in it.',
    dose: '3 × 2 min to one track',
    cues: [
      'Feet wide, knees bent: step one foot back into a low, wide lunge',
      'Raise the arm on the back leg’s side across your face',
      'Bring that foot forward level again, then step the other one back',
      'Stay low and keep moving; the feet trace a triangle on the ground',
      'Match the music: on a slow track, go lower and slower',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'basic',
  },
  {
    id: 'fire.combat-flow-beat-combos',
    element: 'fire',
    name: 'Shadowboxing on the Beat',
    purpose: 'Shadowboxing to music: strikes on the beat, steps between.',
    dose: '3 × 2 min rounds, 30 sec easy bounce between',
    cues: [
      'Guard up, knees soft; bounce slightly in time with the track',
      'One strike per beat: jab; jab, cross; jab, cross, hook',
      'Land strikes on the beat; step or slide in the counts between',
      'Return each strike to the guard the way it went out',
      'Change the combination when the phrase changes, every eight counts',
    ],
    targets: ['Conditioning', 'Coordination', 'Flow', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'basic',
  },
  {
    id: 'water.capoeira-esquivas',
    element: 'water',
    name: 'Capoeira Esquivas (lateral, baixa, cocorinha)',
    purpose: 'Dodges: drop out of the way, then return straight to the ginga.',
    dose: '3 × 2 min from the ginga, both sides',
    cues: [
      'From the ginga, drop on the beat; keep your eyes forward throughout',
      'Lateral: sink to one side, chest to that knee, one hand over the head',
      'Baixa: reach the back leg further back, a hand down by the front foot',
      'Cocorinha: squat on the whole foot, one hand guarding the head',
      'Rise back into the ginga, not to standing; then the other side',
    ],
    targets: ['Agility', 'Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.staff-dance-combat-guards',
    element: 'water',
    name: 'Staff Guard Flow',
    purpose: 'Move the staff between guard positions in time with the music.',
    dose: '3 × 2 min to one track',
    cues: [
      'Practice staff only; clear the staff’s length all round, and above',
      'Hands in thirds, one palm up and one palm down',
      'High guard across the forehead, low across the hips, upright each side',
      'Change guard on the beat with a step; hold it, then move to the next',
      'Turn from the hips; let the arms follow; keep the grip loose',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'fire.capoeira-meia-lua-de-frente',
    element: 'fire',
    name: 'Meia Lua de Frente',
    purpose: 'The first capoeira kick: a straight leg swept in a half circle.',
    dose: '3 × 5 each leg, from the ginga',
    cues: [
      'From the ginga, swing the back leg up straight and out to its side',
      'Sweep it across in front of you, outside to inside, in a half circle',
      'Keep the hips square to the front and one arm up by the face',
      'Put the foot back where it came from and carry on the ginga',
      'Kick waist height first; get height from the hips, not by leaning',
    ],
    targets: ['Agility', 'Coordination', 'Flow', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'fire.capoeira-queixada',
    element: 'fire',
    name: 'Queixada',
    purpose:
      'The reverse half-circle kick: a step, a twist and an outward sweep.',
    dose: '3 × 5 each leg, from the ginga',
    cues: [
      'From the ginga, twist so your side faces forward, knees bent',
      'Step the back foot forward and across; put your weight on it',
      'As it lands, swing the other leg up straight, inside to outside',
      'Make a wide arc, the outer edge of the foot leading; keep arms up',
      'Land it back into the ginga; then the other side',
    ],
    targets: ['Agility', 'Coordination', 'Flow', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.capoeira-negativa-role',
    element: 'water',
    name: 'Negativa and Rolê',
    purpose: 'A low ground position, and the turn that takes you out of it.',
    dose: '6 each side: negativa, rolê, up into the ginga',
    cues: [
      'Grass or a mat; your hands go down, so check the ground first',
      'Negativa: sink onto the ball of one foot, the other leg long in front',
      'Put that leg’s hand down by the hip, not behind; weight forward',
      'Rolê: put both hands down and turn over them, legs sweeping round low',
      'Rise into the ginga; keep your eyes forward, not on the floor',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Strength'],
    venues: ['yard'],
    approxSeconds: 240,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.combat-flow-slips-pivots',
    element: 'water',
    name: 'Shadowboxing Flow (slips, rolls, pivots)',
    purpose:
      'Links combinations with slips, rolls and pivots, without stopping.',
    dose: '3 × 2 min rounds, 30 sec easy bounce between',
    cues: [
      'Throw two or three strikes on the beat, then answer an imagined one',
      'Slip: move the head just off the line, knees bent, eyes forward',
      'Roll: bend the knees and trace a U under an imagined hook',
      'Pivot on the front foot to a new angle and start the next combination',
      'Breathe out on every strike; keep moving and never stand still',
    ],
    targets: ['Flow', 'Agility', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-dance-combat-spin-strike',
    element: 'water',
    name: 'Staff Spin to Strike',
    purpose: 'Links a spin into a strike, and the strike into the next spin.',
    dose: '3 × 2 min, each side leading',
    cues: [
      'Practice staff only; clear the staff’s length all round, and above',
      'Spin a figure 8 at your side, one hand near the centre of the staff',
      'On the beat, add the other hand and turn the spin into a strike',
      'Push with the front hand, pull with the back; step as it lands',
      'Carry the strike round into the next spin without stopping',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'fire.capoeira-armada',
    element: 'fire',
    name: 'Armada',
    purpose: 'Capoeira’s spinning kick: head, then hips, then a straight leg.',
    dose: '3 × 5 each side, from the ginga',
    cues: [
      'From the ginga, step the back foot across and turn your back forward',
      'Head first: look over your shoulder to where you started facing',
      'Turn shoulders and hips; swing the far leg round, straight and wide',
      'Lead with the outside edge of the foot; land back into the ginga',
      'Kick waist height and slow at first; spot the same point every time',
    ],
    targets: ['Agility', 'Coordination', 'Flow', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'fire.combat-flow-kick-chain',
    element: 'fire',
    name: 'Kick Chain (steps and spins on the beat)',
    purpose: 'Links kicks with steps and turns so each leads into the next.',
    dose: '4 × 1 min, switching the lead leg each round',
    cues: [
      'Clear 5 m (16 ft) of space in front of you to travel',
      'Front kick, then put the foot down forward, not back where it started',
      'Round kick with the back leg, and land that one forward too',
      'Turn your back, look over your shoulder, then back kick with the heel',
      'One kick every two beats; step and turn in the counts between',
    ],
    targets: ['Agility', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'water.capoeira-au',
    element: 'water',
    name: 'Aú (capoeira cartwheel)',
    purpose:
      'The capoeira cartwheel, learned in stages: slow, low, eyes forward.',
    dose: '3 × 5 each side at your current step',
    cues: [
      'Grass or a mat; warm the wrists and shoulders first',
      'First put one hand by the front foot; kick the back leg up and land',
      'Then both hands in turn, legs bent and low; straighten only when clean',
      'Keep arms straight, shoulders pushed up; land one foot, then the other',
      'Eyes forward, not on the floor; stop if a wrist or shoulder hurts',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'fire.tricking-tornado-kick',
    element: 'fire',
    name: 'Tornado Kick',
    purpose: 'The first tricking kick: a step, a turn, a jumping round kick.',
    dose: '5 × 3, full rest between',
    cues: [
      'Grass only, after a full warm-up; stop if a landing twists the knee',
      'Face the target; step across so your back turns to it; keep turning',
      'Drive the other knee up and jump off the stepping foot',
      'In the air, round kick with the stepping leg; land on the other',
      'Build it: turn and hop with no kick, then a low kick, then height',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'fire.tricking-pop-360',
    element: 'fire',
    name: 'Pop 360 Kick',
    purpose: 'A jump off both feet that turns into an outside crescent kick.',
    dose: '5 × 3, full rest between',
    cues: [
      'Grass only, after a full warm-up; stop if a landing twists the knee',
      'Step to the side, then step across so your back turns to the target',
      'Jump off both feet and turn the last half in the air',
      'Sweep an outside crescent with the leg on the side you turn toward',
      'Land soft on both feet; learn the turning jump before adding the kick',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'fire.capoeira-meia-lua-de-compasso',
    element: 'fire',
    name: 'Meia Lua de Compasso',
    purpose:
      'Capoeira’s spinning heel kick, thrown with both hands on the floor.',
    dose: '3 × 5 each side, from the ginga',
    cues: [
      'Grass or a mat; warm the hips and the backs of the legs first',
      'From the ginga, drop the chest and put both hands on the floor',
      'Look through your hands at the spot you started facing',
      'Swing the back leg round, straight and wide, heel leading',
      'Rise into the ginga; stop if the low back or a hamstring pulls',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-dance-combat-back-pass',
    element: 'water',
    name: 'Staff Back Pass to Strike',
    purpose: 'Passes the staff behind your back and out into a strike.',
    dose: '3 × 2 min, both directions',
    cues: [
      'Practice staff only; clear the staff’s length all round, and above',
      'First pass it hand to hand behind the waist, with no spin',
      'From a spin at your side, pass it behind your back to the other hand',
      'It comes out the far side moving; use that motion for the strike',
      'Go slowly until the catch behind you is sure; drops are normal',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.capoeira-solo-game',
    element: 'water',
    name: 'Capoeira Solo Game',
    purpose:
      'Capoeira with an imagined partner: answer each move with another.',
    dose: '2 tracks, a short walk between',
    cues: [
      'Use grass with room all round; start and end everything in the ginga',
      'Kick, then dodge the kick your imagined partner sends back',
      'Change levels: meia lua high, esquiva low, negativa, rolê out',
      'Do aú only on soft ground, and only once it is clean on its own',
      'On a slower track, play lower and slower; keep the ginga going',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'Presence'],
    venues: ['yard'],
    approxSeconds: 600,
    tier: 'advanced',
  },
  {
    id: 'water.combat-flow-round',
    element: 'water',
    name: 'Combat Flow Round',
    purpose: 'All your strikes, kicks, turns and steps in one track, no stops.',
    dose: '1 track (3–5 min), no stops',
    cues: [
      'Clear space all round; use grass if you add tricks or ground moves',
      'Long combinations: four to eight moves before you return to guard',
      'Hands on the beat, kicks and spins on the accents, steps between',
      'Keep moving through the breakdowns: bounce, ginga or step in place',
      'Pick the track first and play it to the end; slow and clean, not fast',
    ],
    targets: [
      'Flow',
      'Conditioning',
      'Coordination',
      'Agility',
      'Presence',
      'NoFloor',
    ],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-dance-combat-freestyle',
    element: 'water',
    name: 'Staff Combat Flow Freestyle',
    purpose: 'Spins, strikes, guards and passes, freestyled to one track.',
    dose: '1 track (3–5 min)',
    cues: [
      'Practice staff only; clear the staff’s length plus a step all round',
      'Do not plan it: spin to the melody, strike on the beat',
      'Move through guards, turns and back passes; keep the staff moving',
      'Use the whole space: step in, back and round; change levels',
      'If you drop it, pick it up and go into the next move',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'fire.tricking-butterfly-kick',
    element: 'fire',
    name: 'Butterfly Kick',
    purpose: 'A flat, spinning jump that most twisting tricks are built on.',
    dose: '5 × 3, full rest between',
    cues: [
      'Grass or a mat, fresh legs; learn a clean aú and tornado kick first',
      'Feet wide, chest down level with the floor, swing the arms across',
      'Build it: the wind-up alone, then add the back leg swing, then the hop',
      'Swing the back leg up and round first, the other follows; chest down',
      'First leg up, first leg down; stop if a landing twists or jars',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 360,
    tier: 'advanced',
  },
  {
    id: 'fire.tricking-540-kick',
    element: 'fire',
    name: '540 Kick',
    purpose: 'A tornado kick that turns further and lands on the kicking leg.',
    dose: '5 × 2, full rest between',
    cues: [
      'Grass or a mat, fresh legs; learn a high, clean tornado kick first',
      'Build it: a low, fast tornado that lands on the kicking foot',
      'Then the full turn with the kicking knee bent, then the leg straight',
      'Spot the target on take-off, and again as you come round to land',
      'Land on the kicking leg, knee soft; stop if a knee or ankle twists',
    ],
    targets: ['Agility', 'Coordination', 'Strength'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const DANCE_COMBAT_MOVES: Readonly<Record<string, MoveId>> = {
  'water.capoeira-ginga': 'footwork',
  'fire.combat-flow-beat-combos': 'activity',
  'water.capoeira-esquivas': 'footwork',
  'water.staff-dance-combat-guards': 'staff',
  'fire.capoeira-meia-lua-de-frente': 'kick',
  'fire.capoeira-queixada': 'kick',
  'water.capoeira-negativa-role': 'footwork',
  'water.combat-flow-slips-pivots': 'activity',
  'water.staff-dance-combat-spin-strike': 'staff',
  'fire.capoeira-armada': 'kick',
  'fire.combat-flow-kick-chain': 'kick',
  'water.capoeira-au': 'jump',
  'fire.tricking-tornado-kick': 'jump',
  'fire.tricking-pop-360': 'jump',
  'fire.capoeira-meia-lua-de-compasso': 'kick',
  'water.staff-dance-combat-back-pass': 'staff',
  'water.capoeira-solo-game': 'kick',
  'water.combat-flow-round': 'kick',
  'water.staff-dance-combat-freestyle': 'staff',
  'fire.tricking-butterfly-kick': 'jump',
  'fire.tricking-540-kick': 'jump',
};
