import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Dance — the styles people actually dance at raves and festivals.
 *
 * House, shuffle and cutting shapes, popping and animation, liquid,
 * hip-hop grooves, jumpstyle, and the breaking foundations that suit a
 * rave floor, laid out as one path from first steps to advanced. They
 * slot in beside the dance drills already in `library.ts` and
 * `kit/mirror.ts`: isolations, the body and arm waves, the two-step, the
 * grapevine, toprock, the Jack, spins, freezes, beat-step and the groove
 * combo. Added 21 Sep 2026.
 *
 * No fighting here: dance combat has its own file.
 *
 * Standing steps carry "NoFloor". The floorwork (six-step, baby freeze,
 * lofting) needs a mat or a smooth floor, and is the only work here that
 * does not. Jumpstyle is loud, so it drops "house" and says so in a cue.
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const DANCE_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.hiphop-bounce-rock',
    element: 'water',
    name: 'Hip-Hop Bounce and Rock',
    purpose: 'The grooves under all hip-hop: a body that keeps the time.',
    dose: '3 × 1 min to one track',
    cues: [
      'Hip-hop: feet shoulder-width apart, knees soft, shoulders loose',
      'Down bounce: the knees dip on every beat and rise between',
      'Up bounce: now they straighten on the beat; feel how it changes',
      'Rock: the chest tips forward and back from the hips, one per beat',
      'Keep the bounce and walk it: step side to side under the rock',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.house-stomp',
    element: 'water',
    name: 'House Stomp',
    purpose:
      'A march that lands on every beat: the ground house footwork stands on.',
    dose: '3 × 1 min to one track',
    cues: [
      'House: march in place on the beat, each foot landing flat',
      'Stomp on 1: the knee lifts a little higher and the whole foot lands',
      'Move the stomp: on 1, then on 1 and 5, then on 1, 3, 5 and 7',
      'Add the Jack: the chest drops with every stomp',
      'Indoors, keep it quiet: the weight goes into the knees, not the floor',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.house-side-jack',
    element: 'water',
    name: 'House Side Jack',
    purpose: 'The Jack turned sideways, so the pulse can travel with the feet.',
    dose: '3 × 1 min: side jacks, then front and side mixed',
    cues: [
      'House: start in the front Jack, then turn the same pulse sideways',
      'Step out to one side; the hips arrive first and the chest follows',
      'Knees soften on every beat; the shoulders stay level',
      'Four to each side, then change side on every beat',
      'Mix them on one eight: front, front, side, side',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.dance-liquid-flow',
    element: 'water',
    name: 'Liquid Dance: Hand Flow and Contours',
    purpose:
      'The rave’s own smooth style: hands that never stop and never jerk.',
    dose: '3 × 1 min to a slow, melodic track',
    cues: [
      'Liquid: hands and arms only at first; stand tall, shoulders loose',
      'Hand flow: the hands circle and slide round each other, never touching',
      'Contours: the palms trace an outline: your head, or an imaginary ball',
      'One even speed the whole time; any stop or jerk breaks the illusion',
      'Follow the melody, not the kick drum',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.popping-fresno',
    element: 'water',
    name: 'Popping Hits and the Fresno',
    purpose:
      'The pop itself: a muscle that tenses and lets go right on the beat.',
    dose: '3 × 1 min to a slow, funky track',
    cues: [
      'Popping: a hit is a quick tense and release of a muscle, on the beat',
      'Forearms and triceps first, then the chest, then the thighs',
      'Tense on the beat and let go straight after; the release makes it read',
      'Fresno: step out to one side and hit twice, then over to the other',
      'Step and hit land together; slow tempo until every hit is clean',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.shuffle-running-man',
    element: 'water',
    name: 'Shuffle Running Man',
    purpose: 'The first shuffle step, and the rhythm every other one keeps.',
    dose: '4 × 1 min to one track',
    cues: [
      'Shuffle: on the balls of the feet, knees soft, steps small',
      'Stand on one foot with the other knee lifted',
      'Put the lifted foot down in front as the standing foot slides back',
      'The back foot lifts into the next knee as the front foot slides home',
      'Step it without the slide first; add the slide once the count is even',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 330,
    tier: 'basic',
  },
  {
    id: 'water.house-heel-toe',
    element: 'water',
    name: 'House Heel-Toe',
    purpose:
      'Sideways travel on the heels and balls of the feet, light and quick.',
    dose: '4 × 1 min, both directions',
    cues: [
      'House: feet together, knees soft, weight a touch behind centre',
      'One foot turns on its heel, the other on its ball: the toes split',
      'Swap ends: each foot turns on its other end and they close parallel',
      'Each swap carries you sideways: eight counts one way, eight back',
      'Spring off the floor lightly; forcing it only makes it slow',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 300,
    tier: 'basic',
  },
  {
    id: 'water.shuffle-t-step',
    element: 'water',
    name: 'Shuffle T-Step',
    purpose:
      'The shuffle’s sideways glide, and the step most combos start from.',
    dose: '4 × 1 min, leading each side in turn',
    cues: [
      'Shuffle: stand on one foot, the other knee lifted a little',
      'The free foot kicks out to the side, then back in to the standing arch',
      'The standing foot swivels as you go: toes out, then heel out',
      'Those swivels slide you sideways; the foot coming in makes the T',
      'Eight counts, then switch feet and glide back the other way',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 330,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.hiphop-party-grooves',
    element: 'water',
    name: 'Hip-Hop Party Grooves (Wop, Cabbage Patch)',
    purpose:
      'Two old party grooves that still work anywhere, chained to one track.',
    dose: '3 min to one track',
    cues: [
      'Hip-hop: find the bounce first; both grooves ride on it',
      'Wop: sway to one side each beat, knees bending, that shoulder dropping',
      'The far arm swings across the chest: body goes down, hand comes up',
      'Cabbage Patch: fists at the chest circle flat; that side’s heel lifts',
      'Chain them: eight Wop, eight Cabbage Patch, eight bounce, repeat',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 180,
    tier: 'intermediate',
  },
  {
    id: 'water.house-skate',
    element: 'water',
    name: 'House Skate',
    purpose: 'A glide from foot to foot that never stops, like skating.',
    dose: '3 × 1 min: in place, then travelling',
    cues: [
      'House: weight on one foot, knees soft, torso upright',
      'The other foot glides out, forward and to the side, on its ball',
      'Draw it back in, take the weight on it, and the first foot glides out',
      'Keep it continuous: step-stop-step kills the skating look',
      'Arms swing gently against the legs; then travel forward and back',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.house-pas-de-bourree',
    element: 'water',
    name: 'House Pas de Bourrée',
    purpose:
      'Behind, side, front: three quick steps that change your lead foot.',
    dose: '4 × 1 min, both sides',
    cues: [
      'House: keep the Jack’s bounce going underneath',
      'One foot steps behind, the other steps out to the side',
      'The first foot steps down in front; then start with the other foot',
      'Up, up, down: the first two on the balls, the third settles',
      'Then drag the foot in front or behind instead of stepping',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'water.popping-dime-stops',
    element: 'water',
    name: 'Popping Dime Stops',
    purpose: 'Clean stops with no wobble: what makes popping look sharp.',
    dose: '3 × 1 min to a slow track',
    cues: [
      'Popping: a dime stop is a fast move that stops dead, with no shake',
      'No hit in it: the stop is clean because nothing tenses',
      'Head left and stop, right and stop, one move per beat',
      'Then a hand travels across the body and stops dead on each count',
      'Mix them: stop, stop, hit; the contrast is what the eye sees',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.cutting-shapes-charleston',
    element: 'water',
    name: 'Cutting Shapes Charleston',
    purpose:
      'The twist and tap that cutting shapes grows from, danced to house.',
    dose: '4 × 1 min, both feet',
    cues: [
      'Cutting shapes: small, bouncy and twisting, on the balls of the feet',
      'Twist: feet apart, toes in; cross one foot in front, toes out; back',
      'Charleston: on one foot, tap the free foot forward, then behind you',
      'The standing heel swivels with each tap, so the knees open and close',
      'Chain twist into Charleston and switch feet without losing the beat',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 330,
    tier: 'intermediate',
  },
  {
    id: 'water.house-farmer',
    element: 'water',
    name: 'House Farmer',
    purpose:
      'House’s bouncing step: a hop, a low knee and a stamp on the beat.',
    dose: '3 × 1 min, both sides',
    cues: [
      'House: learn the stomp first; this is its bouncing cousin',
      'Hop to one side as the other knee lifts, low',
      'Set that foot down beside you on the beat; the weight stays put',
      'Hop back the other way and repeat; keep it low and grounded',
      'Slow and in pieces first, then join them into one eight',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.shuffle-kick-outs',
    element: 'water',
    name: 'Shuffle Kick-Outs',
    purpose: 'Quick switching kicks that add speed and snap to the shuffle.',
    dose: '4 × 30 sec on, 30 sec easy',
    cues: [
      'Shuffle: light hops on the balls of the feet, upper body calm',
      'Hop on one foot as the other kicks out low in front, knee soft',
      'Switch with a small hop: that foot lands as the other kicks out',
      'Then kick out to the side and bring the foot back in beside you',
      'Link them into the running man and T-step without losing the count',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.jumpstyle-basic',
    element: 'water',
    name: 'Jumpstyle Basic',
    purpose:
      'The step of the hardstyle floor: small jumps and kicks on the beat.',
    dose: '4 × 1 min, 1 min easy between',
    cues: [
      'Loud: neighbours below hear every landing; yard or ground floor',
      'Jumpstyle: small, springy jumps; the upper body stays calm',
      'Hop and kick one leg forward, then hop and kick it back behind you',
      'Land on both feet, then the same with the other leg',
      'Soft knees on every landing; small jumps keep you on time at speed',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['standing', 'yard'],
    approxSeconds: 420,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.house-loose-legs',
    element: 'water',
    name: 'House Loose Legs',
    purpose:
      'Fast footwork on relaxed legs: control that comes from letting go.',
    dose: '4 × 1 min, both legs',
    cues: [
      'House: heel-toe and the stomp come first; this rides on top of them',
      'Hop lightly on one foot as the other leg swings out to the side',
      'Knee and ankle stay loose, so the foot flicks out and swings back',
      'Two swings, then change feet; then three, then four',
      'On the balls of the feet; the looseness is the step, not the height',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 330,
    tier: 'advanced',
  },
  {
    id: 'water.dance-liquid-threads',
    element: 'water',
    name: 'Liquid Dance: Threads and Builds',
    purpose: 'Liquid’s illusions: holes and objects in the air that seem real.',
    dose: '3 min threads, then 3 min builds',
    cues: [
      'Liquid: loop the arms into a hole that stays still in the air',
      'Threads: pull a hand through the hole, then the head, as if it is real',
      'The hole stays fixed in space while the body passes through it',
      'Builds: shape an object in the air; its size never changes as it moves',
      'Smooth and even throughout; film it to see if the illusion holds',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 360,
    tier: 'advanced',
  },
  {
    id: 'water.popping-strobing',
    element: 'water',
    name: 'Animation Strobing (popping)',
    purpose:
      'Makes smooth movement look lit by a strobe: tiny moves, dead stops.',
    dose: '3 × 1 min to a slow track',
    cues: [
      'Animation: strobing breaks one smooth move into many small ones',
      'A slow arm raise in steps 2–3 cm (1 in) apart: move, stop dead',
      'Space the stops evenly; tick them off on the hi-hats',
      'Then the whole body: a strobed walk or turn, all of it stopping at once',
      'Film it: the eye catches drift and uneven stops the body misses',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.shuffle-spins',
    element: 'water',
    name: 'Shuffle Spins',
    purpose: 'Turns that land back on the beat, straight into the next step.',
    dose: '8 each direction',
    cues: [
      'Shuffle: Spins and Spotting first; spot every turn here too',
      'T-step spin: keep the kick and the swivel going round a small circle',
      'Then a quick 360 on the ball of one foot, arms pulled in',
      'Land it straight into the running man, on the beat, no stumble step',
      'Both directions; a clear, dry floor, never a wet one',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.breaking-six-step',
    element: 'water',
    name: 'Breaking Six-Step',
    purpose:
      'The footwork breaking is built on: the legs circling round the hands.',
    dose: '5 rounds each direction',
    cues: [
      'Breaking: on a mat or smooth floor; circle and warm the wrists first',
      'Crouch on the balls of the feet, one hand down, fingertips spread',
      'Six steps walk the legs in a full circle around the hands',
      'One hand holds you at a time; both only at step 3, the push-up shape',
      'Learn it tall, then low; stop if a wrist aches',
    ],
    targets: ['Agility', 'Strength', 'Coordination', 'Conditioning'],
    venues: ['mat'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.breaking-baby-freeze',
    element: 'water',
    name: 'Breaking Baby Freeze',
    purpose:
      'The first freeze in breaking: balanced on the hands, feet in the air.',
    dose: '5 holds of up to 10 sec',
    cues: [
      'Breaking: on a mat, after the six-step; wrists circled and warm',
      'Squat, hands down shoulder-width apart, fingers spread',
      'One elbow tucks into your hip; the other knee rests on the other elbow',
      'Tip forward until the side of the head just touches, then the feet lift',
      'Stop if the neck takes weight or a wrist hurts; lower the feet first',
    ],
    targets: ['Strength', 'Coordination', 'Flow'],
    venues: ['mat'],
    approxSeconds: 180,
    tier: 'advanced',
  },
  {
    id: 'water.house-lofting',
    element: 'water',
    name: 'House Lofting: Floor Spins and Slides',
    purpose:
      'House taken to the floor: spins and slides that rise into the step.',
    dose: '3 × 1 min to an easy track',
    cues: [
      'House lofting: a smooth floor or mat; knees and wrists warm',
      'Never drop onto a knee: lower through a deep squat onto one hand',
      'Spin on the seat or hip, knees tucked, one hand pushing you round',
      'Slide out along the floor, then rise through a crouch onto the beat',
      'Half speed first; stop if a knee or wrist takes a knock',
    ],
    targets: ['Flow', 'Agility', 'Coordination', 'Strength'],
    venues: ['mat'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.dance-style-switch',
    element: 'water',
    name: 'Dance Style-Switch Round',
    purpose:
      'Changing style when the music changes: what makes a freestyle yours.',
    dose: '2 tracks, back to back',
    cues: [
      'House, shuffle, popping, liquid, hip-hop: whatever you have',
      'A new style each time the music turns a phrase, every 8 or 16 bars',
      'Match the part: footwork on the drums, liquid on the melody',
      'Change on the beat; the last move of one style starts the next',
      'Give your weakest style a phrase of its own every round',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['house', 'standing', 'yard'],
    approxSeconds: 600,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const DANCE_MOVES: Readonly<Record<string, MoveId>> = {
  'water.hiphop-bounce-rock': 'footwork',
  'water.house-stomp': 'footwork',
  'water.house-side-jack': 'footwork',
  'water.dance-liquid-flow': 'activity',
  'water.popping-fresno': 'activity',
  'water.shuffle-running-man': 'footwork',
  'water.house-heel-toe': 'footwork',
  'water.shuffle-t-step': 'footwork',
  'water.hiphop-party-grooves': 'footwork',
  'water.house-skate': 'footwork',
  'water.house-pas-de-bourree': 'footwork',
  'water.popping-dime-stops': 'activity',
  'water.cutting-shapes-charleston': 'footwork',
  'water.house-farmer': 'footwork',
  'water.shuffle-kick-outs': 'footwork',
  'water.jumpstyle-basic': 'jump',
  'water.house-loose-legs': 'footwork',
  'water.dance-liquid-threads': 'activity',
  'water.popping-strobing': 'activity',
  'water.shuffle-spins': 'footwork',
  'water.breaking-six-step': 'footwork',
  'water.breaking-baby-freeze': 'balance',
  'water.house-lofting': 'footwork',
  'water.dance-style-switch': 'footwork',
};
