import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Light gloves, flow flags and dragon staff curricula — the path from
 * first shapes and rolls to full shows and body rolls, ordered basic →
 * intermediate → advanced within each prop.
 *
 * These sit beside the first drills in `kit/flowMore.ts` (gloving finger
 * rolls, tracing and tutting; flag spins and the three-beat weave; dragon
 * staff forearm rolls and the chi roll), which are slotted into the same
 * path. Moves carry the names practitioners use in tutorials, and each
 * `dose` is the Standard chart. Added 21 Sep 2026.
 *
 * Practice props only: soft or LED.
 *
 * Gloving needs no room at all: it is hand-scale, offered at the desk,
 * and works the same with bare hands. Flags and dragon staff swing and
 * roll a long prop around the body, so they map to the staff move and a
 * low ceiling or an office rules them out. Every drill is standing work
 * and carries "NoFloor".
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const GLOVING_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.gloving-stacking',
    element: 'water',
    name: 'Gloving Stacks',
    purpose: 'Stacks the hands in even layers, the simplest shape to learn.',
    dose: '3 × 1 min: climb up, climb down, then to a beat',
    cues: [
      'Hold one hand flat in front of you, palm down, fingers together',
      'Lay the other hand on top in exactly the same shape',
      'Move the lower hand to the top, and repeat to climb up',
      'Climb back down the same way, keeping the layers level',
      'Go slowly first, then one layer per beat',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'basic',
  },
  {
    id: 'water.gloving-liquid',
    element: 'water',
    name: 'Gloving Liquid (hand waves)',
    purpose: 'Moves the hands round each other smoothly, without stopping.',
    dose: '3 × 1 min to a slow track',
    cues: [
      'Hold the fingertips of both hands loosely together, wrists soft',
      'Roll your wrists and fingers so a wave moves through both hands',
      'Move one hand over, under and round the other without stopping',
      'Then pass the wave from one hand, along the arms, to the other',
      'No sharp angles: move smoothly from each shape to the next',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'basic',
  },
  {
    id: 'water.gloving-digits',
    element: 'water',
    name: 'Gloving Digits',
    purpose: 'Builds precise control of small finger shapes.',
    dose: '3 × 1 min: each hand, then both together',
    cues: [
      'First, bend the fingers at the middle knuckle, tips level',
      'For a digit roll, line up both hands, fingers matching',
      'Bend each finger in turn at that knuckle, then back the other way',
      'Move one finger at a time; keep the rest of the hand still',
      'Go slowly first; speed up only while each shape stays clean',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'basic',
  },
  {
    id: 'water.gloving-whips',
    element: 'water',
    name: 'Gloving Underhand Whips',
    purpose: 'Moves the lights toward the viewer in wide circles.',
    dose: '3 × 1 min: each hand leads, both directions',
    cues: [
      'Roll the fingers from little finger to index as the wrist turns over',
      'Repeat with the other hand, passing underneath the first',
      'Make big circles; bigger circles leave longer light trails',
      'Move out toward the viewer and back, wrists and elbows loose',
      'Vary where you place them: high, low and to each side',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'basic',
  },
  {
    id: 'water.gloving-light-show',
    element: 'water',
    name: 'Gloving Light Show for a Viewer',
    purpose: 'Practise giving a light show to another person.',
    dose: '3 × 1 min shows, to a mirror or a friend',
    cues: [
      'Ask first; only give a show if they say yes',
      'Stay about an arm’s length away; never touch the viewer',
      'Do not point bright lights straight into their eyes',
      'Start slow and simple, follow the beat, and end clearly',
      'With no viewer, use a mirror or phone camera in a dim room',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 240,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.gloving-flails',
    element: 'water',
    name: 'Gloving Flails',
    purpose: 'Makes wide circles of light from the wrists, fingers open.',
    dose: '3 × 1 min, both directions',
    cues: [
      'Open the fingers and spread them evenly',
      'Circle the hands from the wrists so the lights make rings',
      'Move both wrists outward, then back to the front; repeat',
      'Then circle from the elbows: bigger rings, same even speed',
      'Go both directions; keep the fingers open throughout',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'intermediate',
  },
  {
    id: 'water.gloving-dials',
    element: 'water',
    name: 'Gloving Dials',
    purpose: 'Builds finger control: one finger swings over onto another.',
    dose: '3 × 1 min: each hand, then both',
    cues: [
      'Start from a finger stack: fingertips of both hands lined up',
      'Swing one finger over in a half circle onto another',
      'Land it exactly, pause, then dial the next one',
      'Go slowly and precisely; keep the rest of the hand still',
      'Then use dials to link digits and tuts',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'intermediate',
  },
  {
    id: 'water.gloving-king-tuts',
    element: 'water',
    name: 'Gloving King Tuts',
    purpose: 'Uses the whole arms for tutting, in big square shapes.',
    dose: '3 × 1 min to a steady beat',
    cues: [
      'Hold the forearms and upper arms at right angles, in square shapes',
      'Make one shape per beat and hold it still until the next',
      'Place shapes above you, beside you and out in front',
      'Then add finger tuts inside the arm shapes',
      'Get square corners first; speed up only while they stay square',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'intermediate',
  },
  {
    id: 'water.gloving-contours',
    element: 'water',
    name: 'Gloving Contours',
    purpose: 'One hand traces smoothly over the surface of the other.',
    dose: '3 × 1 min: each hand leads',
    cues: [
      'Hold one hand still in a fixed shape in front of you',
      'Move the other hand over its surface, close but not gripping',
      'Swap: the moving hand holds still and the still hand moves',
      'Also trace along the arms and round the body',
      'Move slowly and smoothly so the viewer can see the shape',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'intermediate',
  },
  {
    id: 'water.gloving-wave-tuts',
    element: 'water',
    name: 'Gloving Wave Tuts',
    purpose: 'Joins liquid and tutting, with finger rolls between shapes.',
    dose: '3 × 1 min to one track',
    cues: [
      'Build a tut shape and hold it square',
      'Move out of it with a finger roll across the hand',
      'Land the next square shape at the end of the roll',
      'Keep the waves smooth and the shapes sharp',
      'Keep moving from one shape to the next without a break',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.gloving-infinite-roll',
    element: 'water',
    name: 'Gloving Infinite Finger Roll',
    purpose: 'A continuous finger roll passed from one hand to the other.',
    dose: '3 × 1 min, both directions',
    cues: [
      'Learn clean finger rolls on each hand first',
      'As one hand ends its roll, bring the other round to meet it',
      'Join the index fingers and continue the roll in the other hand',
      'Keep the point where the index fingers meet fixed in the air',
      'Go slowly until the join cannot be seen; then reverse direction',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'advanced',
  },
  {
    id: 'water.gloving-spacing-depth',
    element: 'water',
    name: 'Gloving Tech: Spacing and Depth',
    purpose: 'Moves the show through near, far, high, low and wide.',
    dose: '3 × 1 min: one move, carried everywhere',
    cues: [
      'Spacing: spread the fingers evenly so each light is seen apart',
      'Depth: move the hands toward the viewer, then away',
      'Levels: do the same move from low down to above the head',
      'Width: use the whole reach of the arms, left and right',
      'Avoid staying at chest height in one spot; it looks flat',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 210,
    tier: 'advanced',
  },
  {
    id: 'water.gloving-phrasing',
    element: 'water',
    name: 'Gloving to the Phrase',
    purpose: 'Fits a sequence to the music’s phrases as well as its beat.',
    dose: '3 min to one track',
    cues: [
      'Listen first for where the music changes; a phrase ends there',
      'Build a sequence that fills one phrase and ends with it',
      'Use sharp shapes on accents and liquid on smooth parts',
      'Change concept when the music changes, not mid-phrase',
      'Save your biggest move for the drop',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 180,
    tier: 'advanced',
  },
  {
    id: 'water.gloving-blending',
    element: 'water',
    name: 'Gloving Blending Concepts',
    purpose: 'Links concepts so you change between them without stopping.',
    dose: '3 × 2 min',
    cues: [
      'Pick three concepts, such as liquid, tuts and whips',
      'Find a way to move from each one into each of the others',
      'Use finger rolls and waves to link them',
      'Then do one in each hand: tuts in one, liquid in the other',
      'If a move breaks, go straight into another; do not reset',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.gloving-full-show',
    element: 'water',
    name: 'Gloving Full Light Show',
    purpose: 'A full show for one viewer: open, build, peak and wind down.',
    dose: '1 track (3–5 min)',
    cues: [
      'Ask first; an arm’s length away, no touching, no light in the eyes',
      'Open slow and simple; look up at the viewer now and then',
      'Build up: add concepts, speed, depth and levels',
      'Do your biggest moves at the biggest moment in the music',
      'Slow down smoothly and finish cleanly',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['standing', 'desk'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/**
 * Flow flags: spin flags on short sticks, not colour-guard. Written
 * material on spin flags is thin; most of what it teaches is poi and club
 * swinging on a flag, so this path keeps to those shared moves and leaves
 * out tosses, stalls and wraps, which a cloth makes unreliable.
 */
export const FLAGS_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.flag-split-time',
    element: 'water',
    name: 'Flag Same Time and Split Time',
    purpose: 'Teaches two flags to spin together, then in opposite timing.',
    dose: '4 × 1 min: same time, split time, forward and backward',
    cues: [
      'Practice props only; clear an arm and flag length all round and above',
      'Hold a flag in each hand; spin both forward beside you',
      'Same time: both flags at the top together, then both at the bottom',
      'Split time: one at the top while the other is at the bottom',
      'Then spin backward; keep an even speed so both cloths stay open',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.flag-overhead',
    element: 'water',
    name: 'Flag Overhead Circles',
    purpose: 'Spins the flag flat above your head.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Practice props only; check the space above you is clear',
      'Circle one flag flat above your head, parallel to the ceiling',
      'Turn it with the wrist; keep the arm up and relaxed',
      'Even speed keeps it open; if it wraps, stop and shake it out',
      'Use each hand, both directions; lower the arm if the shoulder tires',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.flag-butterfly',
    element: 'water',
    name: 'Flag Butterfly',
    purpose: 'Spins two flags as mirror images in front of you.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Practice props only; clear an arm and flag length all round',
      'Hands in front of the chest, a little apart; flags flat to the front',
      'Spin them in opposite directions, same time, mirroring each other',
      'They pass at the top and bottom on slightly different planes',
      'Drive it from the wrists; down the middle, then up the middle',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.flag-two-beat-weave',
    element: 'water',
    name: 'Flag Two-Beat Weave',
    purpose: 'A weave where the arms cross and uncross on every beat.',
    dose: '3 × 2 min: forward, backward, forward',
    cues: [
      'Practice props only; clear an arm and flag length all round and above',
      'Spin both flags forward beside you, in split time',
      'Each flag turns once on its own side, then once on the far side',
      'Cross and uncross the arms with every turn; hands near the chest',
      'Lead with either arm on top; go slow and even to keep cloths apart',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.flag-reels',
    element: 'water',
    name: 'Flag Reels (hip and shoulder)',
    purpose: 'Moves the spinning flags from in front of you to behind you.',
    dose: '4 × 1 min: hip and shoulder, each direction',
    cues: [
      'Practice props only; clear an arm and flag length all round',
      'Spin both flags flat to the front, same direction, same time',
      'Carry the circles from in front of you to behind you, then back',
      'Start at hip height, then shoulder height; keep the planes flat',
      'Go slow enough to feel where the cloths are; both directions',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.flag-inspin-flowers',
    element: 'water',
    name: 'Flag Inspin Flowers',
    purpose: 'Circles the arm and the flag in the same direction.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Practice props only; clear an arm and flag length all round',
      'Spin one flag flat to the front; move the arm in a big, even circle',
      'Turn the flag and the arm the same way',
      'Count the flag turns to each arm circle and keep the count even',
      'Use both hands, both directions, then both flags together',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.flag-antispin-flowers',
    element: 'water',
    name: 'Flag Antispin Flowers',
    purpose: 'Turns the arm and flag in opposite directions to make petals.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Practice props only; learn inspin flowers first',
      'Spin one flag flat to the front; arm one way, flag the other',
      'For four petals, do three flag turns per arm circle; count them',
      'If the petals lose shape or the cloth wraps, slow the arm down',
      'Use both hands and both directions, then both flags',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'advanced',
  },
  {
    id: 'water.flag-weave-turns',
    element: 'water',
    name: 'Flag Weave Turns',
    purpose: 'Turn your body while the flags keep spinning.',
    dose: '3 × 2 min, turning both ways',
    cues: [
      'Practice props only; clear an arm and flag length all round and above',
      'Spin both flags forward beside you, in split time',
      'Step round to face the other way; keep the flags turning in place',
      'Now they spin backward; turn back and they spin forward again',
      'Turn left and right; slow turns first, then turn out of a weave',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.flag-flow-round',
    element: 'water',
    name: 'Flag Flow Round',
    purpose: 'Links all your flag moves into continuous flow.',
    dose: '1 track (3–5 min)',
    cues: [
      'Practice props only; clear an arm and flag length all round and above',
      'Mix spins, weaves, butterflies, reels and flowers to one track',
      'Change move when the music changes, not in the middle of a phrase',
      'If the flags tangle, free them and start again straight away',
      'Keep your feet moving and let the flags follow',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/**
 * Dragon staff: a contact staff with spoked ends that rolls over the body
 * and is not held. Heavy, so shoes on and soft ground under you. The neck
 * roll sits at the very end of the path, reached through full-arm rolls,
 * with a stop cue.
 */
export const DRAGON_STAFF_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.dragon-staff-two-arm',
    element: 'water',
    name: 'Dragon Staff Two-Arm Rolls',
    purpose: 'Rolls the staff across both forearms, moving the arms together.',
    dose: '3 × 1 min: toward you, then away',
    cues: [
      'Practice staff only; shoes on; clear a staff length all round',
      'Hold both arms out in front, shoulder-width apart, palms up',
      'Lay the staff across both forearms, its middle between them',
      'Tilt both arms together; the staff rolls and its spoked ends turn',
      'Roll it toward you, then away; catch it at the middle to stop',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 210,
    tier: 'basic',
  },
  {
    id: 'water.dragon-staff-palms-down',
    element: 'water',
    name: 'Dragon Staff Palms-Down Rolls',
    purpose: 'Rolls the staff along the back of the forearm.',
    dose: '3 × 1 min each arm: toward you, then away',
    cues: [
      'Practice staff only; shoes on; grass or soft ground under you',
      'One arm out, palm down; lay the staff across the back of the forearm',
      'Raise or lower the hand to slope the arm; the staff rolls along it',
      'Make small, early tilts; the spoked ends turn as it rolls',
      'Use each arm, both ways; catch it at the middle to stop',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.dragon-staff-hand-rolls',
    element: 'water',
    name: 'Dragon Staff Hand Rolls',
    purpose: 'Rolls the staff from the forearm onto the open hand and back.',
    dose: '3 × 1 min each hand',
    cues: [
      'Practice staff only; start from a steady forearm roll',
      'Hold the hand open and flat, fingers together, palm up',
      'Let the staff roll off the wrist onto the palm, toward the fingers',
      'Tilt the hand back before the fingertips so it rolls back to the arm',
      'Use smaller, earlier tilts than on the arm; do each hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.dragon-staff-full-arm',
    element: 'water',
    name: 'Dragon Staff Full-Arm Rolls',
    purpose: 'Rolls the staff the whole length of the arm, hand to shoulder.',
    dose: '3 × 1 min each arm, both directions',
    cues: [
      'Practice staff only; shoes on; clear a staff length all round',
      'Hold the arm straight out, palm up; start the staff at the hand',
      'Raise the hand; it rolls past the elbow and up the upper arm',
      'Keep the arm straight and the shoulder low so it rolls smoothly',
      'Stop at the shoulder and roll it back; leave the neck for much later',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.dragon-staff-palm-spin',
    element: 'water',
    name: 'Dragon Staff Palm Spins',
    purpose: 'Spins the staff flat on an open palm.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Practice staff only; nobody within a staff length of you',
      'Rest the staff’s middle flat on your upturned palm, fingers spread',
      'Push one end round to start it turning on the palm',
      'Keep the palm under the middle; small hand circles keep it going',
      'Use each hand, both directions; slow down if the staff tips',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.dragon-staff-rewinds',
    element: 'water',
    name: 'Dragon Staff Rewinds',
    purpose: 'Reverses the direction of a roll without stopping it.',
    dose: '3 × 1 min: each arm, then arm to arm',
    cues: [
      'Practice staff only; steady rolls in both directions first',
      'Roll it along one arm, then tilt the other way before the end',
      'It slows, pauses briefly and rolls back; do not grab it',
      'Then reverse an arm-to-arm roll and keep it going',
      'Tilt small and early; a late tilt throws the staff off the arm',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 210,
    tier: 'advanced',
  },
  {
    id: 'water.dragon-staff-turns',
    element: 'water',
    name: 'Dragon Staff Turns With Rolls',
    purpose: 'Keeps the staff rolling while you turn your body.',
    dose: '3 × 1 min, turning each way',
    cues: [
      'Practice staff only; a staff length clear all round; grass underfoot',
      'Start a steady arm-to-arm roll in front of the chest',
      'Step round slowly, turning the arms and the roll with you',
      'Do quarter turns first, then half turns, then a full turn',
      'Turn both ways; stop and reset if you get dizzy or the roll wobbles',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 210,
    tier: 'advanced',
  },
  {
    id: 'water.dragon-staff-neck-roll',
    element: 'water',
    name: 'Dragon Staff Neck Roll',
    purpose: 'Rolls the staff up one arm, behind the neck and down the other.',
    dose: '3 × 5 passes, each way',
    cues: [
      'Practice staff only; learn full-arm rolls to each shoulder first',
      'Bend forward, arms wide, so it crosses the upper back, not the neck',
      'Guide it by hand at first; then let it roll from arm to arm',
      'Tuck the chin, head down; stand a little taller once it rolls smoothly',
      'Stop if it touches the head, or anything in the neck hurts',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each gloving move: hand-scale. */
export const GLOVING_MOVES: Readonly<Record<string, MoveId>> = {
  'water.gloving-stacking': 'activity',
  'water.gloving-liquid': 'activity',
  'water.gloving-digits': 'activity',
  'water.gloving-whips': 'activity',
  'water.gloving-light-show': 'activity',
  'water.gloving-flails': 'activity',
  'water.gloving-dials': 'activity',
  'water.gloving-king-tuts': 'activity',
  'water.gloving-contours': 'activity',
  'water.gloving-wave-tuts': 'activity',
  'water.gloving-infinite-roll': 'activity',
  'water.gloving-spacing-depth': 'activity',
  'water.gloving-phrasing': 'activity',
  'water.gloving-blending': 'activity',
  'water.gloving-full-show': 'activity',
};

/** Pictogram and limit class for each flag move: needs room. */
export const FLAGS_MOVES: Readonly<Record<string, MoveId>> = {
  'water.flag-split-time': 'staff',
  'water.flag-overhead': 'staff',
  'water.flag-butterfly': 'staff',
  'water.flag-two-beat-weave': 'staff',
  'water.flag-reels': 'staff',
  'water.flag-inspin-flowers': 'staff',
  'water.flag-antispin-flowers': 'staff',
  'water.flag-weave-turns': 'staff',
  'water.flag-flow-round': 'staff',
};

/** Pictogram and limit class for each dragon staff move: needs room. */
export const DRAGON_STAFF_MOVES: Readonly<Record<string, MoveId>> = {
  'water.dragon-staff-two-arm': 'staff',
  'water.dragon-staff-palms-down': 'staff',
  'water.dragon-staff-hand-rolls': 'staff',
  'water.dragon-staff-full-arm': 'staff',
  'water.dragon-staff-palm-spin': 'staff',
  'water.dragon-staff-rewinds': 'staff',
  'water.dragon-staff-turns': 'staff',
  'water.dragon-staff-neck-roll': 'staff',
};
