import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Hoop and fan curricula — the path from first spins to advanced flow.
 *
 * Each list runs basic → intermediate → advanced, easiest first within a
 * tier, and slots in beside the hoop and fan drills already in
 * `kit/flow.ts`: waist hooping, the isolation and the flow round; fan
 * reels and fan isolations. Each dose is the move's Standard chart; the
 * app plays it softer or harder (see `program/charts.ts`). Added 21 Sep
 * 2026.
 *
 * Practice props only: soft or LED. Nothing here teaches fire.
 *
 * Every move is standing work, so every move carries "NoFloor". Tosses
 * need clear space above and soft ground below.
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const HOOP_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.hoop-hand-spin',
    element: 'water',
    name: 'Hoop Hand Spins',
    purpose: 'The first off-body move: a hoop that turns round the hand.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Practice props only; clear space around and above you',
      'Arm out in front, palm to the side, thumb up and out in an L',
      'Hoop upright and flat to the front, turning in the web of the thumb',
      'Make small circles with the hand to keep it going; keep the arm still',
      'Both directions, then the weaker hand; drops are normal',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.hoop-hand-offs',
    element: 'water',
    name: 'Hoop Hand-Offs Around the Body',
    purpose: 'Passes the hoop round you, hand to hand, never touching you.',
    dose: '3 × 1 min each direction',
    cues: [
      'Hoop level at waist height, both hands on the front edge',
      'One hand carries it round behind you; the other takes it at the back',
      'Bring it round to the front and hand it over again: one steady circle',
      'Keep it level and close; it circles you without touching',
      'Both directions; let go during this pass to start waist hooping',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.hoop-weave',
    element: 'water',
    name: 'Hoop One-Hand Weave',
    purpose: 'The off-body figure 8 that carries the hoop from side to side.',
    dose: '4 × 1 min: each hand, forward and backward',
    cues: [
      'Practice props only; clear space around and above you',
      'Hoop upright at your side, edge to the front, in a loose grip',
      'Turn it forward once on that side, turning from the wrist',
      'Carry it across in front of you and turn it once on the other side',
      'The hand draws a figure 8; the grip rolls underhand to overhand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.hoop-lasso',
    element: 'water',
    name: 'Hoop Lasso (overhead)',
    purpose: 'Spins the hoop flat above your head.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Clear space above you: no branches, lines or lights overhead',
      'Take the hoop underhand at the top and carry it up across the body',
      'Let go over your head; it turns flat round the open hand',
      'Upper arm by the ear, fingers up; push the hand forward and back',
      'Both hands and both directions; drops are normal',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.hoop-knee',
    element: 'water',
    name: 'Knee Hooping',
    purpose: 'Hooping at the knees, with the same rhythm as the waist.',
    dose: '3 × 1 min each direction',
    cues: [
      'A bigger hoop turns slower and is easier to keep up',
      'Feet together, or one just ahead; start the hoop just above the knees',
      'Knees soft; push them forward and back as it passes, as at the waist',
      'Stand tall; push from the knees, not by bending at the hips',
      'Both directions; then try letting it slide down from waist hooping',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.hoop-escalator',
    element: 'water',
    name: 'Hoop Escalator',
    purpose: 'Turns an upright hoop at your side into waist hooping.',
    dose: '3 × 5 each side',
    cues: [
      'A medium hoop is easiest; a very big one flips up too high',
      'Hoop upright at your side, hand on top, the bottom near the floor',
      'Step the near foot into it from the front, ankle under the hoop',
      'Turn it up and round toward you; lift the other foot and step through',
      'Push it off the hip into waist hooping; then the other side',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },
  {
    id: 'water.hoop-chest',
    element: 'water',
    name: 'Chest Hooping',
    purpose: 'Moves the hoop from waist to chest, driven by the ribs.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Solid waist hooping first, both directions',
      'Arms up and out of the way, or inside the hoop at the front',
      'Shimmy it up from waist to chest, or hoop faster until it climbs',
      'Rock the chest forward and back; keep the hips still',
      'Short sets and full rests; this is hard work',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'water.hoop-vortex',
    element: 'water',
    name: 'Hoop Vortex',
    purpose: 'Loops the hoop from waist to overhead and back without stopping.',
    dose: '3 × 1 min each direction',
    cues: [
      'Clear space above you; waist hooping and the lasso clean first',
      'Lift up: a hand behind your back takes the hoop and pulls it up',
      'Bring down: take it from the palm and bring it over one shoulder',
      'Shoulder to opposite hip; push it round the waist, then lift again',
      'To loop it, hand off behind the back and lift with the other hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.hoop-breaks',
    element: 'water',
    name: 'Hoop Breaks and Reversals',
    purpose: 'Stops the hoop on a beat, then sends it back.',
    dose: '4 × 1 min: hand, waist, knee, then mixed',
    cues: [
      'A break stops the hoop on a beat; a reversal sends it back',
      'Hand spin first: catch it in the hand, hold a beat, spin it back',
      'Waist: catch the front edge with both hands, then throw it back round',
      'Knee: lift a bent knee across to meet the hoop and turn it back',
      'Time each break to the music; both directions',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'intermediate',
  },
  {
    id: 'water.hoop-iso-variations',
    element: 'water',
    name: 'Hoop Isolation Variations',
    purpose: 'Variations on the basic isolation: iso-pop, ghosting and linear.',
    dose: '4 × 1 min: iso-pop, ghosting, linear, then mixed',
    cues: [
      'Clean basic isolations with each hand first; a light hoop helps',
      'Iso-pop: extend the arm so the hoop pops out straight, then back in',
      'Ghosting: the free hand traces the hoop’s edge, just off it',
      'Linear: slide the hoop’s centre along a level line',
      'Use a mirror or a phone camera to check the still point holds',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.hoop-coin-flip',
    element: 'water',
    name: 'Hoop Coin Flips',
    purpose: 'The first release: the hoop flips over the arm.',
    dose: '3 × 8 each arm',
    cues: [
      'Practice props only; clear space all round; a light hoop is safer',
      'Hoop out to your side, gripped palm up; swing it to feel where it folds',
      'It folds over the arm and meets it just above the elbow',
      'Let go as it flips; the elbow follows it out and the hand catches it',
      'Small and slow first; do the same count on the other arm',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.hoop-twin-spins',
    element: 'water',
    name: 'Twin Hoop Hand Spins',
    purpose: 'The first doubles move: a hoop spinning on each hand.',
    dose: '4 × 1 min: together, mirrored, then split time',
    cues: [
      'Two smaller, lighter hoops; clear space around and above you',
      'A hoop on each hand, thumbs up in the L; hands wide so they never meet',
      'Together first: both turning the same way at the same time',
      'Mirrored: opposite ways, each hoop on its own plane',
      'Split time: half a turn apart; lead with the weaker hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.hoop-tosses',
    element: 'water',
    name: 'Hoop Tosses (vertical and pizza)',
    purpose: 'Toss the hoop and catch it without stopping your flow.',
    dose: '3 × 8 of each toss',
    cues: [
      'Practice props only; clear space all round and above, over grass',
      'Vertical: arms straight up, hands at its sides; flick them in',
      'Let go with both hands at once; it drops round you: catch at the waist',
      'Pizza: at the top of a vortex lift, send it up flat; catch, other hand',
      'Low tosses until every catch is clean; if one goes wrong, let it fall',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard'],
    approxSeconds: 360,
    tier: 'advanced',
  },
  {
    id: 'water.hoop-duck-out',
    element: 'water',
    name: 'Hoop Shoulder Duck-Out',
    purpose: 'Passes the hoop from the neck to one shoulder and back again.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Neck hooping first: knees soft and bouncy; bare shoulders grip best',
      'As the hoop passes in front, roll one shoulder forward into it',
      'Tuck the chin and slide the head out; it circles that shoulder',
      'When it reaches your back, tuck the chin and duck back in; each side',
      'Stop if the neck or shoulder hurts; never force it',
    ],
    targets: ['Flow', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.hoop-twin-weave',
    element: 'water',
    name: 'Twin Hoop Three-Beat Weave',
    purpose: 'The three-beat weave with two hoops, in split time.',
    dose: '3 × 2 min: forward, reverse, forward',
    cues: [
      'The one-hand weave clean on each hand first',
      'A hoop in each hand, both turning forward beside you, split time',
      'One hand follows the other through the figure 8; each hoop crosses',
      'Count it slowly out loud; the hoops keep to their own paths',
      'Reverse: the same count with both hoops turning backward',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each hoop move. */
export const HOOP_MOVES: Readonly<Record<string, MoveId>> = {
  'water.hoop-hand-spin': 'staff',
  'water.hoop-hand-offs': 'staff',
  'water.hoop-weave': 'staff',
  'water.hoop-lasso': 'staff',
  'water.hoop-knee': 'staff',
  'water.hoop-escalator': 'staff',
  'water.hoop-chest': 'staff',
  'water.hoop-vortex': 'staff',
  'water.hoop-breaks': 'staff',
  'water.hoop-iso-variations': 'staff',
  'water.hoop-coin-flip': 'staff',
  'water.hoop-twin-spins': 'staff',
  'water.hoop-tosses': 'staff',
  'water.hoop-duck-out': 'staff',
  'water.hoop-twin-weave': 'staff',
};

export const FANS_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.fan-finger-spins',
    element: 'water',
    name: 'Fan Finger Spins',
    purpose: 'A fan spinning round one finger, the base of most fan tricks.',
    dose: '4 × 1 min: forward and backward, one fan then both',
    cues: [
      'Practice props only; over grass or a mat, and clear space around you',
      'Middle finger through the ring, other fingers folded away; elbows wide',
      'Forward: let it fall and keep it turning with small finger circles',
      'Backward: start with it low and flick the wrist up to set it turning',
      'To stop, bring the thumb in; the web of the hand catches the frame',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.fan-butterfly',
    element: 'water',
    name: 'Fan Butterfly',
    purpose: 'Builds mirror timing for two fans, driven from the wrists.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Fans flat to the front at chest height, hands a little apart',
      'Opposite directions, together time: each fan mirrors the other',
      'Turn the fans with the wrists; keep the elbows low and still',
      'They pass at the top and bottom, one just in front of the other',
      'Both ways: down the middle, then up the middle',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.fan-stalls',
    element: 'water',
    name: 'Fan Stalls and Reversals',
    purpose: 'Stops the fan at one point, then sends it back.',
    dose: '4 × 1 min: one fan each hand, then both',
    cues: [
      'One fan circling flat to the front, slow and even',
      'At the top, stop it: the fan points straight up for a beat',
      'Send it back down the way it came; now it circles the other way',
      'Then stall at the bottom and at each side; the plane stays flat',
      'Both fans together, mirrored; land each stall on a beat',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.fan-weave',
    element: 'water',
    name: 'Fan Three-Beat Weave',
    purpose:
      'The three-beat weave with fans, in split time with crossing arms.',
    dose: '3 × 2 min: forward, reverse, forward',
    cues: [
      'Practice props only; clear space around you',
      'Both fans turning forward beside you, split time: one up, one down',
      'Each fan turns on its own side, then crosses to the far side and back',
      'Turn the fans with the wrists; hands close in front of the chest',
      'Reverse: the same count with both fans turning backward',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.fan-reel-turns',
    element: 'water',
    name: 'Fan Split-Time Reels and Turns',
    purpose: 'Split-time reels, then reels that keep going while you turn.',
    dose: '4 × 1 min: split time, then turning, each direction',
    cues: [
      'Hip reels at the same time first, as in the basic reels',
      'Split time: one fan in front of you while the other is behind',
      'The planes stay flat and the timing even; count it out loud',
      'Turns: step round a full, slow turn while the reels keep going',
      'Turn both ways; shoulder height once hip height is clean',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.fan-flowers',
    element: 'water',
    name: 'Fan Flowers (inspin and antispin)',
    purpose: 'Combines the arm circle and the fan’s spin into one shape.',
    dose: '4 × 1 min: inspin, antispin, each direction',
    cues: [
      'One fan, flat to the front; the arm draws a big, even circle',
      'Inspin: the fan turns the same way as the arm; antispin: the other way',
      'Four-petal antispin: three fan turns to each arm circle; count them',
      'Keep the plane flat; if the petals lose shape, slow the arm down',
      'Both hands, both directions, then both fans together',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.fan-extensions',
    element: 'water',
    name: 'Fan Extensions and Point Isolations',
    purpose: 'The fan held straight out from the hand, then a still tip.',
    dose: '4 × 1 min: extension, point isolation, each hand',
    cues: [
      'One fan, flat to the front; the centre isolation clean first',
      'Extension: the fan points straight out from the hand',
      'Arm and fan circle round the shoulder together, in one straight line',
      'Point isolation: pick one tip of the fan and keep it fixed in the air',
      'The handle circles that tip; slow, both directions, then both fans',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.fan-horizontal-spins',
    element: 'water',
    name: 'Fan Horizontal Finger Spins',
    purpose: 'The finger spin done flat, without gravity to drive it.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Over grass or a mat: drops are common while this is new',
      'Upright finger spins clean first; middle finger through the ring',
      'Lay the fan flat and hook the middle finger as it turns',
      'The hand circles faster than for upright spins to keep it going',
      'Low in front first, then at chest height; both directions',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.fan-behind-back-weave',
    element: 'water',
    name: 'Fan Behind-the-Back Weave',
    purpose: 'The weave behind your back, done by feel.',
    dose: '3 × 1 min each direction',
    cues: [
      'The front weave clean at a slow count, both directions, first',
      'Both fans turn beside you; they cross behind your back, not in front',
      'Pass the hands low behind the hips; open the shoulders',
      'You cannot see the crossing, so feel the count in your wrists',
      'If the fans clash, stop, reset in front and rebuild the count',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.fan-eight-petal',
    element: 'water',
    name: 'Fan Eight-Petal Antispin',
    purpose: 'Two four-petal antispins combined into one eight-petal flower.',
    dose: '4 × 1 min, slow, each direction',
    cues: [
      'Clean four-petal antispin with each hand first',
      'One hand moves at a time; the other waits, then follows',
      'Arms an eighth of a turn apart; each steps round a quarter at a time',
      'One hand draws a diamond, the other a square: the petals alternate',
      'As slow as you can; the fans pass in front and behind, never touching',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'advanced',
  },
  {
    id: 'water.fan-tosses',
    element: 'water',
    name: 'Fan Tosses (single spin)',
    purpose: 'Toss a fan for one turn and catch it by the handle.',
    dose: '3 × 8 each hand',
    cues: [
      'Practice props only; clear space above, over grass, people well away',
      'No finger in the ring as you let go, or it snags on the throw',
      'Send it up with enough spin for one full turn, no more',
      'Catch the handle in the base of the palm; eyes on the handle',
      'Low throws first; if a catch goes wrong, let it fall rather than grab',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.fan-weave-toss',
    element: 'water',
    name: 'Fan Weave with a Toss',
    purpose: 'Toss one fan out of the weave; catch it on the beat.',
    dose: '3 × 1 min each hand, a toss every few beats',
    cues: [
      'Single-spin tosses clean with each hand, and a steady weave',
      'Weave slowly; on a count, send one fan up for a single turn',
      'The other fan keeps weaving while the first is in the air',
      'Catch it on the beat and carry straight on into the weave',
      'Over grass with clear space above; drops are normal',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard'],
    approxSeconds: 390,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each fan move. */
export const FANS_MOVES: Readonly<Record<string, MoveId>> = {
  'water.fan-finger-spins': 'staff',
  'water.fan-butterfly': 'staff',
  'water.fan-stalls': 'staff',
  'water.fan-weave': 'staff',
  'water.fan-reel-turns': 'staff',
  'water.fan-flowers': 'staff',
  'water.fan-extensions': 'staff',
  'water.fan-horizontal-spins': 'staff',
  'water.fan-behind-back-weave': 'staff',
  'water.fan-eight-petal': 'staff',
  'water.fan-tosses': 'staff',
  'water.fan-weave-toss': 'staff',
};
