import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Juggling and devil sticks — each a path from first tricks to advanced.
 *
 * Juggling covers balls, beanbags and clubs; devil sticks, the centre
 * stick and two hand sticks. Each path opens with the drills already in
 * `kit/flowMore.ts` (the three-ball cascade, two in one hand, the devil
 * stick idle and its flips) and goes on from there, basic moves first,
 * then intermediate, then advanced. Names are the ones jugglers use.
 *
 * Practice props only: soft or LED. Nothing here teaches fire.
 *
 * Every drill is standing work, so every drill carries "NoFloor".
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const JUGGLING_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.juggling-tennis',
    element: 'water',
    name: 'Juggler’s Tennis (over the top)',
    purpose: 'Teaches the overthrow: a ball sent over the top of the pattern.',
    dose: '3 × 2 min, each hand sending the throw over',
    cues: [
      'From a steady cascade, throw one ball higher and wider than the rest',
      'Throw it from the outside of the hand, over the top',
      'Start with single overthrows, a few normal throws between; each hand',
      'Tennis: the same ball always goes over; the others go under it',
      'Watch that one ball go back and forth over the top',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.juggling-claw',
    element: 'water',
    name: 'Claw Cascade',
    purpose: 'A cascade where you catch each ball from above, palm down.',
    dose: '3 × 2 min: one hand, the other, then both',
    cues: [
      'Start with a low, steady cascade',
      'Reach up and grab each ball from above, palm down, as it falls',
      'Pull the hand down and throw from there, palm still down',
      'Claw with one hand while the other juggles normally; then swap',
      'Then claw with both hands; keep the same cascade rhythm',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.juggling-columns',
    element: 'water',
    name: 'Three-Ball Columns',
    purpose: 'The first pattern with both hands throwing at the same time.',
    dose: '3 × 2 min, each hand taking the two',
    cues: [
      'Throw two balls in one hand as columns: straight up, side by side',
      'Hold the third in the other hand, level with the other two',
      'Throw it at the same moment as the outside ball: one up, two up',
      'Straight up and straight down; no ball crosses the middle',
      'Swap which hand holds two; do an extra set with the weaker hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.juggling-half-shower',
    element: 'water',
    name: 'Half-Shower',
    purpose: 'The first pattern where each hand throws differently.',
    dose: '3 × 2 min: each hand taking the overthrows',
    cues: [
      'Learn juggler’s tennis first, until the overthrow feels easy',
      'One hand throws every ball over the top; the other throws under',
      'Start with two overthrows in a row from one hand, then the cascade',
      'Add one more overthrow each time until it runs without a break',
      'Lower the overthrows toward cascade height as it gets steady',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.juggling-reverse-cascade',
    element: 'water',
    name: 'Reverse Cascade',
    purpose: 'A cascade where every throw goes over the top.',
    dose: '3 × 2 min',
    cues: [
      'Learn the half-shower on each side first; this is both at once',
      'Throw from the outside, over the incoming ball; catch in the middle',
      'From the cascade, do two overthrows in a row, one from each hand',
      'Add one overthrow at a time until every throw goes over',
      'Keep it slow and even; it allows fewer loose throws than the cascade',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.juggling-under-the-leg',
    element: 'water',
    name: 'Under the Leg',
    purpose: 'Your first body throw: a ball thrown under a raised leg.',
    dose: '3 × 2 min: one side, the other, then alternating',
    cues: [
      'One ball: lift the knee, reach under the thigh and throw across',
      'Bring the knee up to the hand; do not bend down to reach it',
      'Start with two in that hand and make the first throw under the leg',
      'Then from a running cascade, throw the ball before it a little higher',
      'Do one at a time, then every throw on that side, then alternate legs',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.juggling-441',
    element: 'water',
    name: '441 (Half-Box)',
    purpose: 'Teaches the quick, low pass used in the shower and the box.',
    dose: '3 × 2 min, each hand starting',
    cues: [
      'Hold two balls in the strong hand and one in the other',
      'Throw straight up from the strong hand, then from the other',
      'Then pass the strong hand’s last ball low and fast across; stop',
      'Do one cycle at a time, each hand leading; then join them up',
      'Up, up, across: throw the two ups a little higher than the cascade',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.juggling-club-cascade',
    element: 'water',
    name: 'Three-Club Cascade (singles)',
    purpose: 'The cascade with clubs, one full turn per throw.',
    dose: '6 min: one club, then two, then three',
    cues: [
      'Practice clubs, over grass or a soft surface; keep your feet back',
      'Grip the middle of the handle, the thumb along it toward the body',
      'With one club pointing down, lift and throw it across; one full turn',
      'Peak about 30 cm (1 ft) above the head; catch it level, handle in',
      'Add a second, then a third, as with balls; give each the same turn',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },
  {
    id: 'water.juggling-behind-the-back',
    element: 'water',
    name: 'Behind the Back',
    purpose: 'Your first blind throw, made from behind your back.',
    dose: '3 × 2 min, each hand in turn',
    cues: [
      'Warm up the shoulders first; reaching behind strains a cold one',
      'One ball: swing the hand behind the waist and throw up and across',
      'It comes over the opposite shoulder and drops into the other hand',
      'In the cascade, throw the ball before it a little higher, then resume',
      'Keep your eyes in front, on the spot where the ball comes over',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.juggling-shower',
    element: 'water',
    name: 'Three-Ball Shower',
    purpose: 'A circle pattern: high arcs one way, a fast pass back.',
    dose: '3 × 2 min, both directions',
    cues: [
      'Learn the half-shower and 441 first; they teach the arc and the pass',
      'One hand only throws high arcs across; the other only passes back',
      'Two balls: throw one high, pass the other across under it, catch both',
      'Three: two in the throwing hand; two arcs, pass as the second goes',
      'Do both directions, so the weaker hand throws the arcs too',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.juggling-mills-mess',
    element: 'water',
    name: 'Mills Mess',
    purpose: 'Cross and uncross your arms while the balls move side to side.',
    dose: '3 × 2 min: one cycle at a time, then runs',
    cues: [
      'One ball: arms crossed, strong hand on top; throw as you uncross',
      'Recross the other way while it flies; catch it in the other hand',
      'Two balls: throw one as you uncross, the next once the arms are level',
      'Three: one clean cycle at a time, then two, then keep it going',
      'The balls travel side to side; if they go straight up, slow down',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.juggling-club-doubles',
    element: 'water',
    name: 'Club Doubles',
    purpose: 'Teaches two-turn club throws, a step toward four clubs.',
    dose: '3 × 2 min: one club, then all doubles, then mixed',
    cues: [
      'Get singles steady first; same grip, higher throw, quicker wrist',
      'One club: two full turns, straight up to the same hand, then across',
      'Three clubs, all doubles: higher and slower than singles, even throws',
      'Then switch: a run of singles, a run of doubles, back to singles',
      'Clear space and soft ground; let a bad throw drop, do not grab it',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.juggling-box',
    element: 'water',
    name: 'The Box',
    purpose: 'One hand throws straight up while the other passes across.',
    dose: '3 × 2 min, each hand starting',
    cues: [
      'Two balls: one hand throws straight up as the other passes across',
      'Pass back before the high ball lands, so that hand is free to catch',
      'Three, two in the strong hand: throw one straight up',
      'Just before it lands, the other throws up and the strong hand passes',
      'One ball moves across the middle; the others go straight up each side',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.juggling-backcrosses',
    element: 'water',
    name: 'Backcrosses',
    purpose: 'The cascade thrown entirely behind the back and caught in front.',
    dose: '3 × 2 min, with breaks for the shoulders',
    cues: [
      'Learn clean behind-the-back throws on both sides; warm the shoulders',
      'In the cascade, do one back throw, then return to normal; each side',
      'Then one side only: every throw from that hand behind the back',
      'Then both hands: two or three in a row, adding one at a time',
      'Stop and rest if a shoulder aches; this takes a month or more',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'advanced',
  },
  {
    id: 'water.juggling-four-ball-fountain',
    element: 'water',
    name: 'Four-Ball Fountain',
    purpose: 'The first four-ball pattern: two in each hand, never crossing.',
    dose: '3 × 2 min, each hand starting',
    cues: [
      'First get two in one hand steady in each hand; the balls never cross',
      'Three: two in the strong hand; throw from it, then from the other',
      'As the first comes down, throw the last ball; catch all three',
      'Four, two in each hand: strong, weak, strong, weak; catch all four',
      'Add one or two throws at a time; this takes weeks, not days',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each juggling move: hand-scale. */
export const JUGGLING_MOVES: Readonly<Record<string, MoveId>> = {
  'water.juggling-tennis': 'activity',
  'water.juggling-claw': 'activity',
  'water.juggling-columns': 'activity',
  'water.juggling-half-shower': 'activity',
  'water.juggling-reverse-cascade': 'activity',
  'water.juggling-under-the-leg': 'activity',
  'water.juggling-441': 'activity',
  'water.juggling-club-cascade': 'activity',
  'water.juggling-behind-the-back': 'activity',
  'water.juggling-shower': 'activity',
  'water.juggling-mills-mess': 'activity',
  'water.juggling-club-doubles': 'activity',
  'water.juggling-box': 'activity',
  'water.juggling-backcrosses': 'activity',
  'water.juggling-four-ball-fountain': 'activity',
};

export const DEVIL_STICKS_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.devil-stick-stop-and-go',
    element: 'water',
    name: 'Devil Stick Stop and Go',
    purpose: 'Builds control: stop the stick flat, then send it back.',
    dose: '3 × 2 min, each hand doing the stops',
    cues: [
      'Practice sticks only; start from a steady, slow idle',
      'Toss it to one side with a little extra spin; stop it there, flat',
      'Bring the other hand stick under its free end and send it back',
      'Stop it flat again on the same side; keep each stop level and steady',
      'Then stop on the other side; return to the idle between sets',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.devil-stick-helicopter',
    element: 'water',
    name: 'Devil Stick Helicopter',
    purpose: 'Turns the idle into a flat spin, the base of many moves.',
    dose: '3 × 2 min, both spin directions',
    cues: [
      'From the idle, pull the stick toward you with one hand stick',
      'Push it away with the other; pull, push, and it starts to turn',
      'Tilt one hand stick up a little and the other down; let it roll',
      'Keep it at chest height and clear of the face; slow, even hits',
      'Do both directions: swap which hand pulls and which pushes',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.devil-stick-propeller',
    element: 'water',
    name: 'Devil Stick Propeller',
    purpose: 'Keeps the stick turning full circles with one hand stick.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'From the idle, meet it with one hand stick just below its centre',
      'Let it roll over the hand stick; just before it falls off, lift',
      'It makes a full turn in the air and lands on the same hand stick',
      'Roll, lift, roll, lift; keep the other hand stick out of the way',
      'Each hand, both directions; do an extra set with the weaker hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.devil-stick-around-the-body',
    element: 'water',
    name: 'Devil Stick Under the Leg and Behind the Back',
    purpose: 'Single hits under the leg or behind the back, then back to idle.',
    dose: '3 × 2 min: under the leg, then behind the back, each side',
    cues: [
      'Under the leg: raise the knee; take the next hit from under the thigh',
      'Reach under the same-side leg first, then the far leg; back to idle',
      'Behind the back: toss it to one side; reach round with the far hand',
      'Point that hand stick down as it goes, so it clears the body',
      'One hit from behind, then bring it back to the front; each side',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.devil-stick-single-sticking',
    element: 'water',
    name: 'Devil Stick Single Sticking',
    purpose: 'Keeps the stick up with one hand stick: forehand, then backhand.',
    dose: '3 × 1 min each hand',
    cues: [
      'From the idle, toss it with enough spin for a half flip',
      'Bring the same hand stick across to where the other one would be',
      'After the half flip, lift it from there: a backhand hit',
      'Forehand, half flip, backhand, half flip; keep the other stick low',
      'Then the other hand; half flips first, quarter flips much later',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.devil-stick-hand-stick-flips',
    element: 'water',
    name: 'Hand Stick Flips and Thumb Rolls',
    purpose: 'Flip and spin the hand sticks during the idle.',
    dose: '3 × 1 min each hand',
    cues: [
      'Practice sticks only; use a slow, high idle to give yourself time',
      'As one hand stick lifts the stick across, release it for a half flip',
      'Catch it in the same hand, back under the stick for the next lift',
      'Throw it a little higher or wider than the centre stick to miss it',
      'Then a thumb roll: turn the hand stick flat around an upright thumb',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.devil-stick-leg-roll',
    element: 'water',
    name: 'Devil Stick Leg Roll',
    purpose: 'Rolls the stick over your thigh as it passes between hands.',
    dose: '3 × 1 min each leg',
    cues: [
      'From the idle, lift one knee as you send the stick across',
      'It rolls over the top of the thigh and turns a half flip',
      'Meet it with the other hand stick as it comes off; back to the idle',
      'Aim the centre of the stick at the middle of the thigh',
      'Then back and forth over the same leg; then the other leg',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.devil-stick-saw',
    element: 'water',
    name: 'Devil Stick Saw',
    purpose: 'Spins the stick forward, end over end, in front of you.',
    dose: '3 × 2 min: forward, then reverse',
    cues: [
      'Start with one end on a hand stick, the other against your body',
      'Lift with the first hand stick from underneath, just below the centre',
      'It rolls off, turning forward; bring the other hand stick under next',
      'Keep bringing the hand sticks round and under, one after the other',
      'Hits nearer the centre spin it slower; then learn it in reverse',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.devil-stick-handoff',
    element: 'water',
    name: 'Devil Stick Single Stick Handoff',
    purpose: 'An idle with one hand stick, passed between hands on each flip.',
    dose: '3 × 2 min',
    cues: [
      'Set one hand stick down and single stick with half flips',
      'After a forehand hit, pass it to the other hand; do not throw it',
      'Take the next hit with that hand and carry on single sticking',
      'Then pass it across on every half flip, both ways',
      'Use slower half flips to give yourself time for each pass',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.devil-stick-single-stick-helicopter',
    element: 'water',
    name: 'Devil Stick Single Stick Helicopter',
    purpose: 'A helicopter kept going with one hand stick making every hit.',
    dose: '3 × 1 min each hand',
    cues: [
      'Get the helicopter and single sticking steady first',
      'From the helicopter, hit with one hand stick, then move it across',
      'Hit again from the other side with the same tilt and push',
      'The return is hardest: go wide round the low end of the stick',
      'Each hand; keep the spin at chest height and your face clear',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.devil-stick-behind-back-pass',
    element: 'water',
    name: 'Devil Stick Pass Behind the Back',
    purpose: 'Passes the stick behind your back from one side to the other.',
    dose: '3 × 2 min, both directions',
    cues: [
      'First idle out to one side, with the far hand reaching behind you',
      'Push harder with the front hand so the stick goes behind your back',
      'It comes out on the other side; the hands swap front and behind',
      'Carry on the idle there, then send it back the other way',
      'Slow, even pushes; after a drop, restart from the idle at the side',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.devil-stick-curl',
    element: 'water',
    name: 'Devil Stick Curl',
    purpose: 'Carries the flat spin round your body on one hand stick.',
    dose: '5 curls each side, back to the helicopter after each',
    cues: [
      'Start from a single stick helicopter at the speed of the curl',
      'Keep the hand stick level as it goes under the arm and round',
      'The hand turns in under the arm, round behind, up and to the front',
      'While learning, let the stick rest against your hand as it goes',
      'Go slow, clear of your face; if it slips off, go back to the helicopter',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each devil stick move: needs room. */
export const DEVIL_STICKS_MOVES: Readonly<Record<string, MoveId>> = {
  'water.devil-stick-stop-and-go': 'staff',
  'water.devil-stick-helicopter': 'staff',
  'water.devil-stick-propeller': 'staff',
  'water.devil-stick-around-the-body': 'staff',
  'water.devil-stick-single-sticking': 'staff',
  'water.devil-stick-hand-stick-flips': 'staff',
  'water.devil-stick-leg-roll': 'staff',
  'water.devil-stick-saw': 'staff',
  'water.devil-stick-handoff': 'staff',
  'water.devil-stick-single-stick-helicopter': 'staff',
  'water.devil-stick-behind-back-pass': 'staff',
  'water.devil-stick-curl': 'staff',
};
