import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Juggling and devil sticks — each a path from first tricks to advanced.
 *
 * Juggling covers balls, beanbags and clubs; devil sticks, the centre
 * stick and two hand sticks. Each path opens with the drills already in
 * `kit/flowMore.ts` (the three-ball cascade, two in one hand, the devil
 * stick idle and its flips) and goes on from there, basic moves first,
 * then intermediate, then advanced. Names are the ones jugglers use.
 *
 * Practice props only: soft or LED. Nothing here teaches fire.
 *
 * Every drill is standing work, so every drill carries "NoFloor".
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const JUGGLING_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.juggling-tennis',
    element: 'water',
    name: 'Juggler’s Tennis (over the top)',
    purpose: 'Teaches the overthrow: a ball sent over the top of the pattern.',
    dose: '3 × 2 min, each hand sending the throw over',
    cues: [
      'From a steady cascade, throw one ball higher and wider than the rest',
      'It leaves from the outside of the hand and goes over the top',
      'Single throws first, with a few normal throws between; each hand',
      'Tennis: the same ball always goes over; the others go under it',
      'Watch that one ball travel back and forth, like a ball over a net',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.juggling-claw',
    element: 'water',
    name: 'Claw Cascade',
    purpose: 'Changes the look of the cascade: catch from above, palm down.',
    dose: '3 × 2 min: one hand, the other, then both',
    cues: [
      'A low, steady cascade first',
      'Reach up and snatch each ball from above, palm down, as it falls',
      'Pull the hand down and throw on from there, the palm still down',
      'One hand clawing while the other juggles as normal; then swap',
      'Then both hands; the rhythm of the cascade stays the same',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.juggling-columns',
    element: 'water',
    name: 'Three-Ball Columns',
    purpose: 'The first pattern with both hands throwing at the same time.',
    dose: '3 × 2 min, each hand taking the two',
    cues: [
      'Two balls in one hand as columns: straight up, side by side',
      'The third waits in the other hand, level with the other two',
      'It goes up at the same moment as the outside ball: one up, two up',
      'Straight up and straight down; no ball crosses the middle',
      'Swap which hand holds two; the weaker hand gets the extra set',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.juggling-half-shower',
    element: 'water',
    name: 'Half-Shower',
    purpose: 'The first pattern where each hand throws in its own way.',
    dose: '3 × 2 min: each hand taking the overthrows',
    cues: [
      'Juggler’s tennis first: the overthrow has to feel easy',
      'One hand throws every ball over the top; the other throws under',
      'Build it: two overthrows in a row from one hand, then the cascade',
      'Add one more overthrow each time until it runs without a break',
      'The overthrows come down toward cascade height as it settles',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.juggling-reverse-cascade',
    element: 'water',
    name: 'Reverse Cascade',
    purpose: 'The cascade turned inside out: every throw goes over the top.',
    dose: '3 × 2 min',
    cues: [
      'Half-shower on each side first; this is both sides at once',
      'Throw from the outside, over the incoming ball; catch in the middle',
      'From the cascade: two overthrows in a row, one from each hand',
      'Add one overthrow at a time until every throw goes over',
      'Slow and even; it leaves less room for a loose throw than the cascade',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.juggling-under-the-leg',
    element: 'water',
    name: 'Under the Leg',
    purpose: 'The first body throw, with a knee lift in every rep.',
    dose: '3 × 2 min: one side, the other, then alternating',
    cues: [
      'One ball: lift the knee, reach under the thigh and throw across',
      'Bring the knee up to the hand; do not fold down to reach it',
      'Start with two in that hand and make the first throw under the leg',
      'Then from a running cascade: the throw before it goes a touch higher',
      'One at a time, then every throw on that side, then alternate legs',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.juggling-441',
    element: 'water',
    name: '441 (Half-Box)',
    purpose:
      'Adds the quick, low pass across that the shower and box are built on.',
    dose: '3 × 2 min, each hand starting',
    cues: [
      'Two balls in the strong hand, one in the other',
      'Straight up from the strong hand, then straight up from the other',
      'Then the strong hand passes its last ball low and fast across: stop',
      'One cycle at a time, each hand leading; then join them up',
      'Up, up, across: the two go a little higher than the cascade',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.juggling-club-cascade',
    element: 'water',
    name: 'Three-Club Cascade (singles)',
    purpose: 'Takes the cascade to clubs: one even turn on every throw.',
    dose: '6 min: one club, then two, then three',
    cues: [
      'Practice clubs, over grass or a soft surface; keep your feet back',
      'Grip the middle of the handle, the thumb along it toward the body',
      'One club: from pointing down, lift and throw across; one full turn',
      'Peak about 30 cm (1 ft) above the head; catch it level, handle in',
      'Two, then three, as with balls; every club gets the same turn',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },
  {
    id: 'water.juggling-behind-the-back',
    element: 'water',
    name: 'Behind the Back',
    purpose: 'The first blind throw: the hand works where you cannot see it.',
    dose: '3 × 2 min, each hand in turn',
    cues: [
      'Warm up the shoulders; the reach behind is hard on a cold one',
      'One ball: the hand swings behind the waist and throws up and across',
      'It comes over the opposite shoulder and drops into the other hand',
      'In the cascade, throw the one before it a touch higher, then go back',
      'Eyes stay in front, on the spot where the ball comes over',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.juggling-shower',
    element: 'water',
    name: 'Three-Ball Shower',
    purpose: 'The classic circle: high arcs one way, a fast pass back.',
    dose: '3 × 2 min, both directions',
    cues: [
      'Half-shower and 441 first: the arc and the pass are both in them',
      'One hand only throws high arcs across; the other only passes back',
      'Two balls: a high throw, pass the other across under it, catch both',
      'Three: two in the throwing hand; two arcs, and pass as the second goes',
      'Both directions; the weaker hand learns to throw the arcs too',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.juggling-mills-mess',
    element: 'water',
    name: 'Mills Mess',
    purpose: 'Arms cross and uncross while the balls flow from side to side.',
    dose: '3 × 2 min: one cycle at a time, then runs',
    cues: [
      'One ball: arms crossed, strong hand on top; throw as you uncross',
      'Recross the other way while it flies; catch it in the other hand',
      'Two balls: throw one as you uncross, the next once the arms are level',
      'Three: one clean cycle at a time, then two, then keep it going',
      'The balls travel side to side; if they go straight up, slow down',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.juggling-club-doubles',
    element: 'water',
    name: 'Club Doubles',
    purpose:
      'The two-turn throw: a higher, slower cascade and a step to four clubs.',
    dose: '3 × 2 min: one club, then all doubles, then mixed',
    cues: [
      'Singles steady first; the same grip, a higher throw, a quicker wrist',
      'One club: two full turns, straight up to the same hand, then across',
      'Three clubs, all doubles: higher and slower than singles, even throws',
      'Then switch: a run of singles, a run of doubles, back to singles',
      'Clear space and soft ground; let a bad throw drop rather than grab it',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.juggling-box',
    element: 'water',
    name: 'The Box',
    purpose: 'Both hands at once: one throws straight up as the other passes.',
    dose: '3 × 2 min, each hand starting',
    cues: [
      'Two balls: one hand throws straight up as the other passes across',
      'Pass back before the high ball lands, so that hand is free to catch',
      'Three, two in the strong hand: throw one straight up',
      'Just before it lands, the other throws up and the strong hand passes',
      'One ball shuttles across the middle; the others rise on each side',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.juggling-backcrosses',
    element: 'water',
    name: 'Backcrosses',
    purpose: 'The cascade thrown entirely behind the back and caught in front.',
    dose: '3 × 2 min, with breaks for the shoulders',
    cues: [
      'Behind the back clean on both sides first; warm the shoulders',
      'In the cascade, one back throw, then back to normal; each side',
      'Then one side only: every throw from that hand behind the back',
      'Then both hands: two or three in a row, adding one at a time',
      'Stop and rest if a shoulder aches; this takes a month or more',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'advanced',
  },
  {
    id: 'water.juggling-four-ball-fountain',
    element: 'water',
    name: 'Four-Ball Fountain',
    purpose: 'The first four-ball pattern: two in each hand, never crossing.',
    dose: '3 × 2 min, each hand starting',
    cues: [
      'Two in one hand steady in each hand first; the balls never cross',
      'Three: two in the strong hand; up from it, then up from the other',
      'As the first comes down, throw the last ball; catch all three',
      'Four, two in each hand: strong, weak, strong, weak; catch all four',
      'Add one or two throws at a time; this takes weeks, not days',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each juggling move: hand-scale. */
export const JUGGLING_MOVES: Readonly<Record<string, MoveId>> = {
  'water.juggling-tennis': 'activity',
  'water.juggling-claw': 'activity',
  'water.juggling-columns': 'activity',
  'water.juggling-half-shower': 'activity',
  'water.juggling-reverse-cascade': 'activity',
  'water.juggling-under-the-leg': 'activity',
  'water.juggling-441': 'activity',
  'water.juggling-club-cascade': 'activity',
  'water.juggling-behind-the-back': 'activity',
  'water.juggling-shower': 'activity',
  'water.juggling-mills-mess': 'activity',
  'water.juggling-club-doubles': 'activity',
  'water.juggling-box': 'activity',
  'water.juggling-backcrosses': 'activity',
  'water.juggling-four-ball-fountain': 'activity',
};

export const DEVIL_STICKS_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.devil-stick-stop-and-go',
    element: 'water',
    name: 'Devil Stick Stop and Go',
    purpose: 'Control instead of chasing: stop the stick flat, then send it.',
    dose: '3 × 2 min, each hand doing the stops',
    cues: [
      'Practice sticks only; start from a steady, slow idle',
      'Toss it to one side with a little extra spin; stop it there, flat',
      'The other hand stick comes under its free end and sends it back: go',
      'Stop it flat again on the same side; the stops stay level and calm',
      'Then stop on the other side; back into the idle between sets',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.devil-stick-helicopter',
    element: 'water',
    name: 'Devil Stick Helicopter',
    purpose: 'Turns the idle into a flat spin, the root of a family of moves.',
    dose: '3 × 2 min, both spin directions',
    cues: [
      'From the idle, one hand stick pulls the stick toward you as it lifts',
      'The other pushes it away from you; pull, push, and it starts to turn',
      'Tilt one hand stick up a little and the other down; let it roll',
      'Keep it at chest height and clear of the face; slow, even hits',
      'Both directions: swap which hand pulls and which one pushes',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.devil-stick-propeller',
    element: 'water',
    name: 'Devil Stick Propeller',
    purpose: 'One hand stick keeps it turning full circles, like a propeller.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'From the idle, meet it with one hand stick just below its centre',
      'Let it roll over the hand stick; just before it falls off, lift',
      'It makes a full turn in the air and lands on the same hand stick',
      'Roll, lift, roll, lift; the other hand stick stays out of the way',
      'Each hand, both directions; the weaker hand gets the extra set',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.devil-stick-around-the-body',
    element: 'water',
    name: 'Devil Stick Under the Leg and Behind the Back',
    purpose: 'Single hits from around the body, straight back into the idle.',
    dose: '3 × 2 min: under the leg, then behind the back, each side',
    cues: [
      'Under the leg: raise the knee; take the next hit from under the thigh',
      'Same hand under the same leg first, then the far leg; back to idle',
      'Behind the back: toss it out to one side; the far hand reaches round',
      'Point that hand stick down as it goes, so it clears the body',
      'One hit from behind, then bring it back to the front; each side',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.devil-stick-single-sticking',
    element: 'water',
    name: 'Devil Stick Single Sticking',
    purpose: 'Keeps the stick up with one hand stick: forehand, then backhand.',
    dose: '3 × 1 min each hand',
    cues: [
      'From the idle, toss it with enough spin for a half flip',
      'Bring the same hand stick across to where the other one would be',
      'After the half flip, lift it from there: a backhand hit',
      'Forehand, half flip, backhand, half flip; the other stick stays low',
      'Then the other hand; half flips first, quarter flips much later',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.devil-stick-hand-stick-flips',
    element: 'water',
    name: 'Hand Stick Flips and Thumb Rolls',
    purpose: 'Adds spins of your own: hand sticks flipped and turned mid-idle.',
    dose: '3 × 1 min each hand',
    cues: [
      'Practice sticks only; a slow, high idle gives you the time',
      'As one hand stick lifts the stick across, let it go: a half flip',
      'Catch it in the same hand, back under the stick for the next lift',
      'Throw it a little higher or wider than the centre stick to miss it',
      'Then a thumb roll: the hand stick turns flat around an upright thumb',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.devil-stick-leg-roll',
    element: 'water',
    name: 'Devil Stick Leg Roll',
    purpose: 'Lets the stick roll over the thigh on its way from hand to hand.',
    dose: '3 × 1 min each leg',
    cues: [
      'From the idle, lift one knee as you send the stick across',
      'It rolls over the top of the thigh and turns a half flip',
      'The other hand stick meets it as it comes off; back to the idle',
      'Aim the centre of the stick at the middle of the thigh',
      'Then back and forth over the same leg; then the other leg',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.devil-stick-saw',
    element: 'water',
    name: 'Devil Stick Saw',
    purpose: 'A new plane: the stick turns like a wheel rolling away from you.',
    dose: '3 × 2 min: forward, then reverse',
    cues: [
      'Start it rested: one end on a hand stick, the other against your body',
      'The first hand stick lifts from underneath, just below the centre',
      'It rolls off, turning forward; the other hand stick comes under next',
      'Keep bringing the hand sticks round and under, one after the other',
      'Hits nearer the centre spin it slower; then learn it in reverse',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.devil-stick-handoff',
    element: 'water',
    name: 'Devil Stick Single Stick Handoff',
    purpose: 'An idle with only one hand stick, handed across on each flip.',
    dose: '3 × 2 min',
    cues: [
      'Set one hand stick down and single stick with half flips',
      'After a forehand hit, hand it to the other hand: passed, not thrown',
      'That hand takes the next hit and carries on single sticking',
      'Then hand it across on every half flip, both ways',
      'A slower half flip gives your hands the time for each pass',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.devil-stick-single-stick-helicopter',
    element: 'water',
    name: 'Devil Stick Single Stick Helicopter',
    purpose: 'Keeps the flat spin going with one hand stick making every hit.',
    dose: '3 × 1 min each hand',
    cues: [
      'Helicopter and single sticking solid first',
      'From the helicopter, hit with one hand stick, then move it across',
      'Hit again from the other side with the same tilt and push',
      'Coming back is the hard part: go wide round the low end of the stick',
      'Each hand; keep the spin at chest height and your face clear',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.devil-stick-behind-back-pass',
    element: 'water',
    name: 'Devil Stick Pass Behind the Back',
    purpose: 'Sends the stick itself round behind you, side to side.',
    dose: '3 × 2 min, both directions',
    cues: [
      'First hold an idle out to one side, the far hand reaching behind you',
      'From it, the front hand pushes harder: the stick goes behind your back',
      'It comes out on the other side; the hands swap front and behind',
      'Carry on the idle there, then send it back the other way',
      'Slow, even pushes; after a drop, restart from the idle at the side',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.devil-stick-curl',
    element: 'water',
    name: 'Devil Stick Curl',
    purpose: 'Carries the flat spin right round the body on one hand stick.',
    dose: '5 curls each side, back to the helicopter after each',
    cues: [
      'Single stick helicopter first, spinning at the speed of the curl',
      'The move: a glass on a flat palm, carried under the arm and round',
      'The hand turns in under the arm, round behind, up and to the front',
      'While learning, let the stick rest against your hand as it goes',
      'Slow, and wide of the face; if it slips off, back to the helicopter',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each devil stick move: needs room. */
export const DEVIL_STICKS_MOVES: Readonly<Record<string, MoveId>> = {
  'water.devil-stick-stop-and-go': 'staff',
  'water.devil-stick-helicopter': 'staff',
  'water.devil-stick-propeller': 'staff',
  'water.devil-stick-around-the-body': 'staff',
  'water.devil-stick-single-sticking': 'staff',
  'water.devil-stick-hand-stick-flips': 'staff',
  'water.devil-stick-leg-roll': 'staff',
  'water.devil-stick-saw': 'staff',
  'water.devil-stick-handoff': 'staff',
  'water.devil-stick-single-stick-helicopter': 'staff',
  'water.devil-stick-behind-back-pass': 'staff',
  'water.devil-stick-curl': 'staff',
};
