import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Poi and rope dart curricula — the path from first spins to advanced
 * flow, ordered basic → intermediate → advanced within each prop.
 *
 * These sit beside the first poi and rope dart drills in `kit/flow.ts`
 * (three-beat weave, butterfly and flowers; wheel spins and wraps), which
 * are slotted into the same path. Moves carry the names practitioners use
 * in tutorials, and each `dose` is the Standard chart. Added 21 Sep 2026.
 *
 * Practice props only: soft or LED poi, and a soft end on the rope dart —
 * a tennis ball knotted in a sock, never a hard dart. Neck wraps sit at
 * the very end of the rope dart path, learned in steps, with a stop cue.
 *
 * Every drill is standing work that swings a prop overhead and around,
 * so each carries "NoFloor" and maps to the staff move: a low ceiling or
 * an office rules it out.
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const POI_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.poi-wheel-spins',
    element: 'water',
    name: 'Poi Wheel Plane Spins',
    purpose: 'Builds an even, flat circle, the base of every poi move.',
    dose: '4 × 1 min: each hand, then both, each direction',
    cues: [
      'Practice props only; clear space around and above you',
      'One poi, the handle loose in the fingers, spinning forward beside you',
      'Turn it with the wrist; keep the elbow soft and close to the body',
      'Keep the circle flat and upright; if it hits your leg, slow down',
      'Backward, then the other hand, then both poi forward together',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'basic',
  },
  {
    id: 'water.poi-timing-direction',
    element: 'water',
    name: 'Poi Timing and Direction (four ways)',
    purpose: 'Teaches the four timing and direction patterns of two-poi moves.',
    dose: '4 × 1 min, one way each; forward, then backward',
    cues: [
      'Both poi in the wheel plane, one at each side',
      'Together time, same direction: both forward, both at the top at once',
      'Split time, same direction: both forward, one up as the other is down',
      'Together time, opposite: one forward, one back, both at the top at once',
      'Split time, opposite: one forward, one back, one up, one down',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'basic',
  },
  {
    id: 'water.poi-planes',
    element: 'water',
    name: 'Poi Planes: Wheel, Wall and Floor',
    purpose: 'Keeps the poi on flat planes, so they stop bumping and tangling.',
    dose: '3 × 2 min, changing plane every 8 counts',
    cues: [
      'Practice props only; clear space around and above you',
      'Wheel plane: both poi circle upright beside you',
      'Wall plane: one poi at a time, circling flat in front of you',
      'Floor plane: one poi in a flat circle above the head',
      'Change plane on the count; if a poi wobbles, slow it until it is steady',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.poi-two-beat-weave',
    element: 'water',
    name: 'Poi Two-Beat Weave',
    purpose: 'A quicker version of the weave, and the base for windmills.',
    dose: '3 × 2 min: forward, reverse, forward',
    cues: [
      'Practice props only; clear space around and above you',
      'Both poi forward, split time, the hands close together',
      'Both poi turn once on the right, then once on the left, and repeat',
      'On each side the other arm reaches across in front of the body',
      'Reverse: the same count with both poi spinning backward',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'basic',
  },
  {
    id: 'water.poi-reels',
    element: 'water',
    name: 'Poi Hip and Shoulder Reels',
    purpose: 'Carries flat circles round the body, from in front to behind.',
    dose: '4 × 1 min: hip and shoulder, each side',
    cues: [
      'Practice props only; clear space around and above you',
      'Both poi flat to the front, same direction, together time',
      'Hip reel: carry both circles round one hip to behind you, then back',
      'Shoulder reel: the same at shoulder height, round the shoulder',
      'Keep the planes flat as they travel; turn the chest a little with them',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.poi-stalls',
    element: 'water',
    name: 'Poi Stalls',
    purpose: 'Stops a poi in the air to change direction. Used in transitions.',
    dose: '3 × 2 min: each hand, then both',
    cues: [
      'One poi in the wheel plane, spinning forward beside you',
      'As it rises in front, lift the hand with it so the tether stays in line',
      'It slows, hangs still for a moment, then falls back the way it came',
      'Now it spins backward; stall it again to bring it forward',
      'Then stalls in the wall plane in front; each hand, then both at once',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.poi-windmill',
    element: 'water',
    name: 'Poi Windmill',
    purpose: 'Split time above the head. Trains the overhead planes.',
    dose: '3 × 2 min: forward, reverse, forward',
    cues: [
      'Practice props only; clear space around and well above you',
      'One poi first: a figure 8, one loop in front of you and one behind',
      'The loops cross above the head; turn the hips a little side on',
      'Two poi: split time, same direction, the hands close together up high',
      'As one poi circles in front, the other circles behind; then reverse',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.poi-turns',
    element: 'water',
    name: 'Poi Turns (wheel to wall and back)',
    purpose: 'Turn while the poi keep spinning, so you can move around.',
    dose: '3 × 2 min: turning left and right, then in split time',
    cues: [
      'Both poi forward at your sides, wheel plane, together time',
      'Turn a quarter, hands where they were: one poi in front, one behind',
      'Keep turning to face the other way: the poi are at your sides again',
      'Now they spin backward: they held their planes while you turned',
      'Turn back the other way; then split time, then opposite directions',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.poi-buzzsaw',
    element: 'water',
    name: 'Poi Buzzsaw',
    purpose: 'Split time with both poi on one circle, half a turn apart.',
    dose: '4 × 1 min: forward, reverse, low, high',
    cues: [
      'Practice props only; wrap each tether once round the hand to shorten it',
      'Split time, same direction, both poi flat to the front',
      'Bring the hands together until they almost touch',
      'The poi follow each other round one circle, half a turn apart',
      'Reverse it; then carry it low beside the legs and up by the shoulder',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.poi-crossers',
    element: 'water',
    name: 'Poi Crossers',
    purpose: 'Crosses each poi to the body’s far side, keeping its plane.',
    dose: '3 × 2 min: forward, backward, forward',
    cues: [
      'Both poi forward in the wheel plane beside you',
      'Cross the arms loosely in front; each poi turns on the far side',
      'The poi keep their planes and their direction as the arms cross',
      'Stay crossed and swap arms: the lower arm drops back and comes over',
      'Slow and big first; then change the timing, then go backward',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.poi-isolations',
    element: 'water',
    name: 'Poi Extensions and Isolations',
    purpose: 'Trains extensions and isolations, which hybrids are built from.',
    dose: '4 × 1 min: each hand, then both, each direction',
    cues: [
      'Practice props only; one poi, flat to the front',
      'Extension: the poi in line with a long arm, one big circle together',
      'Isolation: hand and poi head share one small circle, always opposite',
      'Keep the middle of the tether still; keep your eyes on that point',
      'Both directions, each hand, then both poi mirrored in front',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.poi-antispin-three-petal',
    element: 'water',
    name: 'Poi Antispin: Four Petals to Three',
    purpose: 'Changes how many times the poi turns per arm circle in antispin.',
    dose: '4 × 1 min: each hand, then both, each direction',
    cues: [
      'From a clean four-petal antispin: three poi turns to one arm circle',
      'Three petals: two poi turns to one arm circle; the arm a little faster',
      'Count the petals aloud; space them evenly round the circle',
      'Hold four for a phrase, then three, then four, without stopping',
      'Each hand, both directions, then both poi together',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.poi-hybrids',
    element: 'water',
    name: 'Poi Hybrids',
    purpose: 'Each hand does a different pattern at the same time.',
    dose: '4 × 1 min: two hybrids, each way round',
    cues: [
      'Clean extensions, isolations and antispin in each hand first',
      'Both hands circle the same way at the same time, a little apart',
      'First: one poi in extension, the other in isolation',
      'Then four-petal antispin in one hand against an extension in the other',
      'Go very slow; swap hands; if a shape blurs, go back to one poi',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.poi-behind-back-weave',
    element: 'water',
    name: 'Poi Behind-the-Back Weave',
    purpose: 'The weave with the crossings behind your back, done by feel.',
    dose: '3 × 2 min: forward, reverse, forward',
    cues: [
      'A clean three-beat weave, forward and reverse, first',
      'The same count, but each crossing hand reaches behind the back',
      'The crossing poi turns beside the far hip, not out behind you',
      'Go slow with loose shoulders; the reach behind is the hard part',
      'If you drop it, pick it up and restart the count',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'advanced',
  },
  {
    id: 'water.poi-tosses',
    element: 'water',
    name: 'Poi Tosses',
    purpose: 'Toss a poi, catch it and keep spinning without a stop.',
    dose: '3 × 10 tosses each hand',
    cues: [
      'Soft poi only, over grass; clear space all round and well above',
      'One poi in the wheel plane beside you, slow and even',
      'Let go as it rises in front; it lifts away, still turning',
      'Catch the handle as it comes down and carry straight on spinning',
      'Head height first; stop and go lower if it drifts toward the face',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'advanced',
  },
];

export const ROPE_DART_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.rope-dart-pendulum',
    element: 'water',
    name: 'Rope Dart Pendulum Swings',
    purpose: 'The first rope dart skill: letting rope out and drawing it back.',
    dose: '3 × 1 min: in front, then each side',
    cues: [
      'Soft end only: a tennis ball knotted in a sock, never a hard dart',
      'Clear 3 m (10 ft) all round, and keep people out of it',
      'Feet level; swing the dart side to side in front of you, short and low',
      'The tail hand feeds rope out through the front hand, then takes it back',
      'Then forward and back beside you, feet staggered, the same feeding',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
    tier: 'basic',
  },
  {
    id: 'water.rope-dart-figure-8',
    element: 'water',
    name: 'Rope Dart Figure 8s',
    purpose: 'Links the wheels on each side into one figure 8.',
    dose: '3 × 1 min each way: falling in front, then rising',
    cues: [
      'Soft end only; clear 3 m (10 ft) all round',
      'Start with a slow wheel on your stronger side',
      'Carry it across in front to a wheel on the other side, and back',
      'The dart crosses in front of you on a diagonal: a figure 8',
      'Keep the rope length the same; keep your face out of the line',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.rope-dart-overhead',
    element: 'water',
    name: 'Rope Dart Overhead Spins',
    purpose: 'A flat circle above your head, and how to move into it.',
    dose: '3 × 1 min each direction',
    cues: [
      'Soft end only; clear 3 m (10 ft) all round and nothing overhead',
      'Hand above the head, the dart in a flat circle over you',
      'Short rope first; let out more only while the circle stays flat',
      'From a wheel beside you, lift into the overhead circle, then back down',
      'Both directions; if it dips toward head height, shorten the rope',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.rope-dart-casts',
    element: 'water',
    name: 'Rope Dart Casts and Retrievals',
    purpose: 'Sends the dart out in a line, then back into a spin.',
    dose: '2 × 10 each side',
    cues: [
      'Soft end only; clear 3 m (10 ft) in front and keep people out of it',
      'From a wheel beside you, rising in front, open the front hand',
      'Let rope slide out so the dart travels forward; the tail stays in hand',
      'Draw it back and turn it straight into the wheel again',
      'Short casts first, a little more rope each time; each side',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.rope-dart-stalls',
    element: 'water',
    name: 'Rope Dart Stalls and Recoveries',
    purpose: 'Stops the dart smoothly and keeps you going after a mistake.',
    dose: '3 × 2 min, each side',
    cues: [
      'Soft end only; clear 3 m (10 ft) all round',
      'Cast out along the wheel; move the hand with the dart to slow it',
      'It slows and stops in the air, then falls back the way it came',
      'Take it into a wheel the other way, with no jerk on the rope',
      'Recovery: when a move goes wrong, draw it into any wheel and carry on',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.rope-dart-elbow-launch',
    element: 'water',
    name: 'Rope Dart Elbow Launches',
    purpose: 'Wraps the rope round the bent elbow, then sends the dart out.',
    dose: '2 × 8 each arm',
    cues: [
      'Soft end only; clear 3 m (10 ft) in front',
      'A slow wheel beside you, rising in front',
      'Lift the elbow, bent, to shoulder height in the line of the wheel',
      'The rope catches in the crook of the elbow and turns round it once',
      'As it comes round again, straighten the arm, send it out and step',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },
  {
    id: 'water.rope-dart-foot-launch',
    element: 'water',
    name: 'Rope Dart Foot Launches',
    purpose: 'Catches the dart on the foot, then sends it out.',
    dose: '2 × 8 each foot',
    cues: [
      'Soft end only; shoes on; clear 3 m (10 ft) in front',
      'A slow wheel beside you, the dart falling in front',
      'Lift the knee before the dart comes down past eye height',
      'Catch the rope on the laces; give with it until the dart rests there',
      'Extend the leg to send it forward, toes pointing; draw it into a wheel',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },
  {
    id: 'water.rope-dart-step-through',
    element: 'water',
    name: 'Rope Dart Step-Throughs',
    purpose: 'The dart passes under your feet as you step over it.',
    dose: '3 × 1 min each direction',
    cues: [
      'Soft end only; clear 3 m (10 ft) all round; flat, even ground',
      'A flat circle low around you, the hand low in front of the hips',
      'As the dart reaches one leg, lift that foot and let it pass under',
      'Step down and lift the other foot: the dart goes all the way round',
      'Short rope and slow first; add a small hop only once stepping is clean',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.rope-dart-belt-wrap',
    element: 'water',
    name: 'Rope Dart Belt Wrap',
    purpose: 'The first wrap behind your back, done without seeing it.',
    dose: '2 × 5 each side',
    cues: [
      'Soft end only; arm and leg wraps clean on both sides first',
      'Swing the dart out to one side in front of you, then draw it back',
      'Lift that arm so the dart passes round behind the waist',
      'It comes out on the far side: take the rope in the other hand',
      'Unwind it the way it came; short rope and slow first',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.rope-dart-shoulder-wraps',
    element: 'water',
    name: 'Rope Dart Dragon and Scorpion Wraps',
    purpose: 'Wraps across the back and over the shoulder, guided by feel.',
    dose: '5 of each wrap, each side',
    cues: [
      'Soft end only; a shorter rope; belt and elbow work clean first',
      'Dragon: from a wheel on the right, send it under the right arm',
      'Across the back; the raised left forearm guides it over that shoulder',
      'Scorpion reverses it: over the right shoulder, out under the left arm',
      'Unwind the way it came; stop if the rope rides up to the neck or face',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'advanced',
  },
  {
    id: 'water.rope-dart-neck-wrap',
    element: 'water',
    name: 'Rope Dart Neck Wrap (necklace)',
    purpose: 'Wraps the rope round the neck, in steps so it never tightens.',
    dose: '5 each side, slow',
    cues: [
      'Soft end only; dragon and scorpion wraps clean on both sides first',
      'By hand first: lay the rope over the back of the neck, no spin',
      'Then a short rope and a slow swing; a raised hand guides it on',
      'The rope rests on the neck and unwinds the way it came; it never knots',
      'Stop if it pulls tight or the dart comes near the face; go back a step',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.rope-dart-combination',
    element: 'water',
    name: 'Rope Dart Linked Combination',
    purpose: 'Links spins, wraps, launches and steps without stopping.',
    dose: '3 min to one track, then again with the other side leading',
    cues: [
      'Soft end only; clear 3 m (10 ft) all round, more if you travel',
      'Link four moves you know: a wheel, a wrap, a launch, a step-through',
      'Each move comes back through a retrieval into a wheel before the next',
      'Travel with a stealing step: one foot steps in behind the other',
      'After a drop, pick it up into a wheel and carry on',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const POI_MOVES: Readonly<Record<string, MoveId>> = {
  'water.poi-wheel-spins': 'staff',
  'water.poi-timing-direction': 'staff',
  'water.poi-planes': 'staff',
  'water.poi-two-beat-weave': 'staff',
  'water.poi-reels': 'staff',
  'water.poi-stalls': 'staff',
  'water.poi-windmill': 'staff',
  'water.poi-turns': 'staff',
  'water.poi-buzzsaw': 'staff',
  'water.poi-crossers': 'staff',
  'water.poi-isolations': 'staff',
  'water.poi-antispin-three-petal': 'staff',
  'water.poi-hybrids': 'staff',
  'water.poi-behind-back-weave': 'staff',
  'water.poi-tosses': 'staff',
};

/** Pictogram and limit class for each move. */
export const ROPE_DART_MOVES: Readonly<Record<string, MoveId>> = {
  'water.rope-dart-pendulum': 'staff',
  'water.rope-dart-figure-8': 'staff',
  'water.rope-dart-overhead': 'staff',
  'water.rope-dart-casts': 'staff',
  'water.rope-dart-stalls': 'staff',
  'water.rope-dart-elbow-launch': 'staff',
  'water.rope-dart-foot-launch': 'staff',
  'water.rope-dart-step-through': 'staff',
  'water.rope-dart-belt-wrap': 'staff',
  'water.rope-dart-shoulder-wraps': 'staff',
  'water.rope-dart-neck-wrap': 'staff',
  'water.rope-dart-combination': 'staff',
};
