import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Staff and double staff curricula — the path from the first spin to
 * blind work, tosses and neck rolls, ordered basic → intermediate →
 * advanced within each prop.
 *
 * The single staff is the most-used prop in the app, so it gets the
 * deepest path: rotors and figure 8s in every plane, passes round the
 * body, transitions, isolations and extensions, then contact staff
 * (wraps, forearm rolls, palm spins, fishtails, chest, halo and angel
 * rolls) and tosses. Double staff runs from side spins to hybrids and
 * throws. The staff figure 8, beat locks, the no-drop album and the
 * double staff windmill and weave, written before the path existed, are
 * slotted in beside these. Moves carry the names practitioners use in
 * tutorials, and each `dose` is the Standard chart. Added 21 Sep 2026.
 *
 * Practice props only: a bo, contact or light-up staff. Flow only: the
 * staff as a dance-combat prop lives in `danceCombat.ts`. Neck rolls and
 * tosses sit at the very end, learned in steps, with a stop cue.
 *
 * Every drill is standing work that swings a staff overhead and around,
 * so each carries "NoFloor" and maps to the staff move: a low ceiling or
 * an office rules it out.
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const STAFF_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.staff-rotor',
    element: 'water',
    name: 'Staff Rotor (hand to hand)',
    purpose:
      'The first spin: the staff turns in front of you, passed hand to hand.',
    dose: '3 × 1 min each direction',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'Hands at chest height, the staff held at its centre, flat to the front',
      'One hand turns it half a turn and hands it on at the centre',
      'The other hand takes it and turns the next half; it never stops',
      'Slow and even first, then the other direction',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.staff-one-hand-rotor',
    element: 'water',
    name: 'Staff One-Hand Rotor (each hand)',
    purpose: 'The wrist spin: the staff turns a full circle in one hand.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Staff flat to the front at your side, held at its centre',
      'Thumb and index finger hold the centre; it turns in their crook',
      'The other fingers open to let it pass, then close again each half turn',
      'The wrist leads; the elbow stays near the ribs',
      'Both directions; a drop is part of practice, so restart slowly',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.staff-reverse-figure-8',
    element: 'water',
    name: 'Staff Reverse Figure 8 (each hand)',
    purpose: 'The figure 8 run backward, the direction most wrists resist.',
    dose: '3 × 1 min each hand',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'Staff at your side, held at its centre; the top end comes back to you',
      'One circle passes inside the arm, the next passes outside it',
      'The wrist leads; the elbow stays near the ribs',
      'If it clips the arm, slow down; then the weaker hand',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.staff-helicopter',
    element: 'water',
    name: 'Staff Helicopter (overhead)',
    purpose:
      'Takes the spin overhead into the flat plane: two hands, then one.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Clear overhead: nothing within a staff length above your hands',
      'Hands up over the head, the staff held at its centre and flat',
      'Hand to hand first: each hand turns it half a turn and passes it on',
      'Then one hand: the staff turns in the crook of the thumb',
      'Elbows soft, head still and upright; both directions',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.staff-back-pass',
    element: 'water',
    name: 'Staff Behind-the-Back Pass',
    purpose: 'The first pass round the body, and the door to turning moves.',
    dose: '3 × 2 min, passing both ways',
    cues: [
      'Walk-through first: pass the still staff behind the back, hand to hand',
      'Then from figure 8s at one side, take the hand low behind the back',
      'Swap hands at the small of the back; the staff keeps turning',
      'The new hand carries it out into figure 8s on the other side',
      'Stand tall; the staff stays low, well clear of the head',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'basic',
  },
  {
    id: 'water.staff-wrist-wrap',
    element: 'water',
    name: 'Contact Staff Wrist Wrap',
    purpose:
      'The first contact move: the staff wraps the wrist and comes home.',
    dose: '10 each direction, each hand',
    cues: [
      'Over grass or soft ground, shoes on: the first tries will drop',
      'From a slow one-hand rotor, open the hand and let the staff keep going',
      'It wraps over the back of the wrist, one full turn around it',
      'Close the hand on its centre as it comes back round, and spin on',
      'Both directions, then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'basic',
  },
  {
    id: 'water.staff-forearm-rolls',
    element: 'water',
    name: 'Contact Staff Forearm Rolls',
    purpose:
      'The base of every contact roll: a staff that rolls along the arm.',
    dose: '3 × 1 min each arm',
    cues: [
      'Over grass or soft ground, shoes on: a weighted staff will drop',
      'Arm out in front, palm up; lay the staff across it at its centre',
      'Raise the hand: it rolls to the elbow. Lower it: it rolls back',
      'Keep the arm level side to side, so the staff stays square to it',
      'Then palm to palm: roll it off one open hand onto the other',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.staff-front-figure-8',
    element: 'water',
    name: 'Staff Front Figure 8 (wall plane)',
    purpose:
      'The figure 8 turned to face the front: a second plane, the same wrist.',
    dose: '3 × 1 min each hand',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'Forearm upright in front of the chest, the staff flat to the front',
      'One turn it passes left of the forearm, the next turn right of it',
      'Wrist-led, as at your side; the hand stays out from the face',
      'Forward and reverse, then the weaker hand; keep the plane flat',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-transitions',
    element: 'water',
    name: 'Staff Transitions (basic flow)',
    purpose: 'Joins single moves into flow that does not stop between them.',
    dose: '3 × 2 min: change move every 8 counts',
    cues: [
      'Three moves you own: rotor, figure 8 and helicopter',
      'Eight counts each, changing at the end of a phrase',
      'Change where both moves turn the same way: that is the door',
      'The staff never stops or reverses at the change',
      'Add the reverse figure 8 and the back pass once those three link',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-behind-head-pass',
    element: 'water',
    name: 'Staff Behind-the-Head Pass',
    purpose:
      'A high pass: the staff crosses behind the head to the other hand.',
    dose: '3 × 2 min, passing both ways',
    cues: [
      'Walk-through first with the still staff, hand to hand behind the head',
      'From a rotor, lift the hand up and back; the staff turns behind you',
      'The other hand reaches up over its shoulder and takes the centre',
      'Head a little forward, so the staff turns a hand’s width behind it',
      'Out into a rotor on the new side, then pass it back',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-under-leg-pass',
    element: 'water',
    name: 'Staff Under-Leg Pass',
    purpose: 'Brings the legs into it: the staff passes under a lifted thigh.',
    dose: '3 × 1 min, alternating legs',
    cues: [
      'Walk-through first: lift a knee and hand the still staff underneath',
      'From figure 8s at your side, lift the knee toward hip height',
      'Hand the staff under the thigh to the other hand; it keeps turning',
      'Stand tall on the standing leg; the foot comes down softly',
      'Under the right leg, then the left, on a slow, steady count',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-palm-spin',
    element: 'water',
    name: 'Contact Staff Palm Spin',
    purpose: 'A staff spinning flat on an open palm, held only by balance.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Over grass or soft ground, shoes on: it will drop',
      'From a slow one-hand helicopter at chest height, open the hand flat',
      'The staff spins on the palm, its centre over the middle of the hand',
      'Small moves of the palm keep it centred; the palm stays level',
      'Close the thumb round it to take it back; then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-chest-roll',
    element: 'water',
    name: 'Contact Staff Chest Roll',
    purpose: 'Rolls the staff across the front of the body, arm to arm.',
    dose: '3 × 1 min, back and forth',
    cues: [
      'Learn forearm rolls first; a practice staff with soft or padded ends',
      'Arms open to the sides at shoulder height, chest lifted',
      'Slowly, it rolls along one arm, across the upper chest, onto the other',
      'More roll than spin; if an end rises toward the face, stop and catch it',
      'Catch it at the centre on the far arm, then roll it back',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-fishtails',
    element: 'water',
    name: 'Contact Staff Fishtails',
    purpose:
      'A small, technical move: a figure 8 balanced on the back of the hand.',
    dose: '3 × 1 min each hand, reverse first',
    cues: [
      'Over grass or soft ground; reverse fishtails first, they are easier',
      'The staff rests across the back of the wrist at its centre; no grip',
      'Small figure 8s of the hand keep it swinging in a figure 8 of its own',
      'Once the wrist version holds, move the contact to the back of the thumb',
      'Forward fishtails and the weaker hand come after',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.staff-360',
    element: 'water',
    name: 'Staff 360 (turning back pass)',
    purpose:
      'The back pass with a full turn of the body, the staff still spinning.',
    dose: '3 × 1 min: a 360 every 8 counts',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'Own the back pass both ways first',
      'Take the back pass and keep turning with it, a full circle',
      'Swap hands behind you as the body turns; the staff never stops',
      'Eyes find the same point each turn; both directions of turn',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.staff-behind-back-figure-8',
    element: 'water',
    name: 'Staff Figure 8 Behind the Back',
    purpose: 'Blind work: figure 8s played behind you, by feel alone.',
    dose: '3 × 1 min each hand: forward, then reverse',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'From the back pass, keep the hand behind the back instead of passing',
      'Figure 8s there, passing either side of the forearm as at your side',
      'A few turns, then out to the side; build the count slowly',
      'Stand tall; the head stays still and the eyes stay forward',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.staff-isolations',
    element: 'water',
    name: 'Staff Isolations and Extensions',
    purpose:
      'Tech: one point of the staff held still, then the staff as a long arm.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Clear an arm plus a staff all round; grip a hand’s width from one end',
      'Isolation: flat to the front, the middle of the staff stays on one spot',
      'The hand circles that spot; let the staff turn in a loose hand',
      'Extension: the staff in line with the arm; the far end draws the circle',
      'Slow, eyes on the still point, both directions; then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'advanced',
  },
  {
    id: 'water.staff-tosses',
    element: 'water',
    name: 'Staff Tosses (flat and upright)',
    purpose: 'Lets the staff leave the hand and come back into the flow.',
    dose: '5 min: flat tosses, then upright tosses',
    cues: [
      'Clear 3 m (10 ft) all round, nothing overhead, nobody near; soft ground',
      'Flat first: from a slow helicopter at chest height, let go and catch',
      'Start 30 cm (1 ft) up; build to head height a little at a time',
      'Upright: from a rotor, let go as it rises; one turn, catch the centre',
      'Let a bad toss fall and step away; never reach for a falling end',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-halo-roll',
    element: 'water',
    name: 'Contact Staff Halo Roll',
    purpose:
      'The first neck roll: shoulder to shoulder across the back of the neck.',
    dose: '10 each way, slow',
    cues: [
      'Learn chest rolls first; a practice staff, the lightest you have',
      'Walk-through: both hands guide it across the back of the shoulders',
      'Head still, chin slightly down; it rolls from one shoulder to the other',
      'Slow, with more roll than spin; speed comes last',
      'Stop if it knocks the head or the neck hurts; back to the walk-through',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-angel-roll',
    element: 'water',
    name: 'Contact Staff Angel Roll',
    purpose: 'The halo roll extended down both arms: one turn, hand to hand.',
    dose: '10 each way',
    cues: [
      'Own the halo roll both ways first; a practice staff only',
      'Arms out wide at shoulder height, like wings',
      'Release with more roll than spin; it rolls up the arm to the neck',
      'At the neck, turn with it so it rolls onto the other arm and down',
      'Stop if it knocks the head or the neck hurts; back to halo rolls',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-long-combination',
    element: 'water',
    name: 'Staff Long Combination',
    purpose:
      'Chains six moves across three planes into one line, then loops it.',
    dose: '4 × the combination each side, then 3 min looped',
    cues: [
      'Six moves you own across three planes: side, front and overhead',
      'Learn it a link at a time: two moves, then three, then all six',
      'Each change keeps the speed; a stall means that link needs work',
      'The weaker hand leads every other time through',
      'Then loop it to one track, carrying on through any drop',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 600,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const STAFF_MOVES: Readonly<Record<string, MoveId>> = {
  'water.staff-rotor': 'staff',
  'water.staff-one-hand-rotor': 'staff',
  'water.staff-reverse-figure-8': 'staff',
  'water.staff-helicopter': 'staff',
  'water.staff-back-pass': 'staff',
  'water.staff-wrist-wrap': 'staff',
  'water.staff-forearm-rolls': 'staff',
  'water.staff-front-figure-8': 'staff',
  'water.staff-transitions': 'staff',
  'water.staff-behind-head-pass': 'staff',
  'water.staff-under-leg-pass': 'staff',
  'water.staff-palm-spin': 'staff',
  'water.staff-chest-roll': 'staff',
  'water.staff-fishtails': 'staff',
  'water.staff-360': 'staff',
  'water.staff-behind-back-figure-8': 'staff',
  'water.staff-isolations': 'staff',
  'water.staff-tosses': 'staff',
  'water.staff-halo-roll': 'staff',
  'water.staff-angel-roll': 'staff',
  'water.staff-long-combination': 'staff',
};

export const DOUBLE_STAFF_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.double-staff-side-spins',
    element: 'water',
    name: 'Double Staff Side Spins (wheel plane)',
    purpose: 'Two staffs spinning beside you, in time and then out of time.',
    dose: '4 × 1 min: together and split, each direction',
    cues: [
      'Practice props only; clear arm plus staff all round, and above',
      'A staff in each hand, held at the centre, spinning beside you',
      'Both forward, together time: the staffs match, like two wheels',
      'Split time is a quarter turn: one staff upright while one is flat',
      'Then backward; hands just outside the hips, elbows soft',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.double-staff-figure-8s',
    element: 'water',
    name: 'Double Staff Figure 8s (same direction)',
    purpose: 'The single-staff figure 8 in both hands at once.',
    dose: '4 × 1 min: forward and reverse, together and split',
    cues: [
      'Each hand plays a figure 8 at its own side, both staffs forward',
      'One circle passes inside each arm, the next passes outside it',
      'Together time first, then split time: a quarter turn apart',
      'Elbows near the ribs; the inside circles pass between arm and body',
      'Then both in reverse',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.double-staff-opposite-8s',
    element: 'water',
    name: 'Double Staff Figure 8s (opposite directions)',
    purpose: 'One hand forward, one in reverse: two patterns, one brain.',
    dose: '4 × 1 min, swapping which hand goes forward',
    cues: [
      'Own forward and reverse figure 8s in each hand first',
      'Start the forward hand alone for 8 counts, then add the reverse hand',
      'Count out loud; the weaker direction sets the speed',
      'If one stalls, stop both and restart the count slowly',
      'Swap: the other hand forward, the first in reverse',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.double-staff-helicopters',
    element: 'water',
    name: 'Double Staff Helicopters',
    purpose: 'Two flat spins overhead: the horizontal plane with both hands.',
    dose: '4 × 1 min: same way, then mirrored',
    cues: [
      'Clear overhead: nothing within a staff length above your hands',
      'Both arms up, a staff in each hand, spinning flat above you',
      'Hands wide apart so the ends never meet',
      'Same way first, then mirrored: the staffs turn opposite ways',
      'Head still, shoulders down, elbows soft; switch direction each set',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.double-staff-flowers',
    element: 'water',
    name: 'Double Staff Flowers (inspin)',
    purpose: 'Big, straight-arm circles with the staffs turning inside them.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Practice props only; clear arm plus staff all round, and above',
      'Arms straight, each drawing a big circle at its own side',
      'Inspin: each staff spins the same way its arm circles',
      'Keep the count: the same number of staff turns in each arm circle',
      'Together time first, then split time; then both backward',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.double-staff-two-beat-weave',
    element: 'water',
    name: 'Double Staff Two-Beat Weave',
    purpose:
      'Both staffs on one side, then the other, the arms crossing each beat.',
    dose: '3 × 2 min: forward, reverse, forward',
    cues: [
      'Both staffs spin forward on the same side of the body',
      'One arm crosses over the other to put both staffs on that side',
      'Each beat both move to the other side; the arms cross the other way',
      'Slow, even count; hands near the chest, shoulders loose',
      'If the staffs touch, spread the hands and slow the count',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.double-staff-isolations',
    element: 'water',
    name: 'Double Staff Isolations',
    purpose: 'Trains the still point: a staff that turns on a spot in the air.',
    dose: '2 min each hand, then 2 min with both',
    cues: [
      'One staff first, held at the centre, flat to the front',
      'Pick one end: it stays on one spot in the air',
      'The hand circles that spot; the staff turns once each circle',
      'Wall plane first, then the wheel plane beside you',
      'Then a staff in each hand, mirrored; slow, both directions',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },
  {
    id: 'water.double-staff-antispin',
    element: 'water',
    name: 'Double Staff Antispin',
    purpose: 'Arms circle one way while the staffs spin the other.',
    dose: '2 min each hand, then 2 min with both',
    cues: [
      'One staff first, flat to the front, held at the centre',
      'The hand draws a circle one way; the staff spins the other way',
      'Count the staff turns in each circle and keep that count the same',
      'Small, slow circles first; widen them once the count holds',
      'Then both staffs mirrored, then both the same way',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.double-staff-flower-turns',
    element: 'water',
    name: 'Double Staff Flowers with Turns',
    purpose: 'Keeps the flowers going through a full turn of the body.',
    dose: '4 × 1 min: a turn every 8 counts, each way',
    cues: [
      'Own mirrored flowers first: the staffs turning opposite ways',
      'Walk the turn in small steps, slowly, the flowers still going',
      'The planes turn with you; arms and staffs keep their circles',
      'Eyes find the same point each turn; finish facing it',
      'Turn both ways; the weaker way gets the extra set',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'advanced',
  },
  {
    id: 'water.double-staff-hybrids',
    element: 'water',
    name: 'Double Staff Hybrids (isolation and antispin)',
    purpose: 'One hand isolates while the other antispins, in one plane.',
    dose: '3 × 1 min each way round',
    cues: [
      'Own isolations and antispins in each hand first',
      'Both staffs flat to the front, hands at chest height, wide apart',
      'Start the isolation alone for 8 counts, then add the antispin',
      'Same timing: both hands finish a circle together',
      'Swap hands: the other one isolates',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.double-staff-throws',
    element: 'water',
    name: 'Double Staff Throws',
    purpose: 'Sends one staff up while the other keeps spinning.',
    dose: '5 min: 10 throws each hand, then alternating',
    cues: [
      'Clear 3 m (10 ft) all round, nothing overhead, nobody near; soft ground',
      'Both staffs spinning; one goes up while the other keeps turning',
      'Small first: one turn, no higher than the head; catch the centre',
      'The throwing hand is back in the pattern the moment it catches',
      'Let a bad throw fall and step away; never reach for a falling end',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.double-staff-flow-round',
    element: 'water',
    name: 'Double Staff Flow Round',
    purpose:
      'Joins every double staff move into one track, through every plane.',
    dose: '1 track (3–5 min)',
    cues: [
      'Practice props only; clear arm plus staff all round, and above',
      'Side, front and overhead: visit every plane in the track',
      'Weaves, windmills, flowers, isolations; change on the phrase',
      'A turn in every section; a throw only if the space is clear',
      'Recover each drop straight into the next move, not a restart',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const DOUBLE_STAFF_MOVES: Readonly<Record<string, MoveId>> = {
  'water.double-staff-side-spins': 'staff',
  'water.double-staff-figure-8s': 'staff',
  'water.double-staff-opposite-8s': 'staff',
  'water.double-staff-helicopters': 'staff',
  'water.double-staff-flowers': 'staff',
  'water.double-staff-two-beat-weave': 'staff',
  'water.double-staff-isolations': 'staff',
  'water.double-staff-antispin': 'staff',
  'water.double-staff-flower-turns': 'staff',
  'water.double-staff-hybrids': 'staff',
  'water.double-staff-throws': 'staff',
  'water.double-staff-flow-round': 'staff',
};
