import type {Exercise} from '../types';
import type {MoveId} from '../moves';

/**
 * Staff and double staff curricula — the path from the first spin to
 * blind work, tosses and neck rolls, ordered basic → intermediate →
 * advanced within each prop.
 *
 * The single staff is the most-used prop in the app, so it gets the
 * deepest path: rotors and figure 8s in every plane, passes round the
 * body, transitions, isolations and extensions, then contact staff
 * (wraps, forearm rolls, palm spins, fishtails, chest, halo and angel
 * rolls) and tosses. Double staff runs from side spins to hybrids and
 * throws. The staff figure 8, beat locks, the no-drop album and the
 * double staff windmill and weave, written before the path existed, are
 * slotted in beside these. Moves carry the names practitioners use in
 * tutorials, and each `dose` is the Standard chart. Added 21 Sep 2026.
 *
 * Practice props only: a bo, contact or light-up staff. Flow only: the
 * staff as a dance-combat prop lives in `danceCombat.ts`. Neck rolls and
 * tosses sit at the very end, learned in steps, with a stop cue.
 *
 * Every drill is standing work that swings a staff overhead and around,
 * so each carries "NoFloor" and maps to the staff move: a low ceiling or
 * an office rules it out.
 *
 * Ids are stable — journal entries and custom circuits reference them.
 */
export const STAFF_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.staff-rotor',
    element: 'water',
    name: 'Staff Rotor (hand to hand)',
    purpose: 'The first spin: the staff turns in front, passed hand to hand.',
    dose: '3 × 1 min each direction',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'Hands at chest height, the staff held at its centre, flat to the front',
      'One hand turns it half a turn and hands it on at the centre',
      'The other hand takes it and turns the next half; keep it moving',
      'Slow and even first, then the other direction',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.staff-one-hand-rotor',
    element: 'water',
    name: 'Staff One-Hand Rotor (each hand)',
    purpose: 'The wrist spin: the staff turns a full circle in one hand.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Staff flat to the front at your side, held at its centre',
      'Thumb and index finger hold the centre; it turns between them',
      'Open the other fingers to let it pass; close them each half turn',
      'Lead with the wrist; keep the elbow near the ribs',
      'Both directions; after a drop, restart slowly',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.staff-reverse-figure-8',
    element: 'water',
    name: 'Staff Reverse Figure 8 (each hand)',
    purpose: 'The figure 8 in reverse, the harder direction for most people.',
    dose: '3 × 1 min each hand',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'Staff at your side, held at its centre; the top end moves toward you',
      'One circle passes inside the arm, the next passes outside it',
      'Lead with the wrist; keep the elbow near the ribs',
      'If it hits the arm, slow down; then the weaker hand',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },
  {
    id: 'water.staff-helicopter',
    element: 'water',
    name: 'Staff Helicopter (overhead)',
    purpose: 'A flat spin above your head: two hands, then one.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Clear overhead: nothing within a staff length above your hands',
      'Hands above the head; hold the staff flat, at its centre',
      'Hand to hand first: each hand turns it half a turn and passes it on',
      'Then one hand: the staff turns in the web of the thumb',
      'Elbows soft, head still and upright; both directions',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.staff-back-pass',
    element: 'water',
    name: 'Staff Behind-the-Back Pass',
    purpose: 'The first pass around the body. Turning moves build on it.',
    dose: '3 × 2 min, passing both ways',
    cues: [
      'Walk-through first: pass the still staff behind the back, hand to hand',
      'Then from figure 8s at one side, take the hand low behind the back',
      'Swap hands at the small of the back; keep the staff turning',
      'The new hand carries it out into figure 8s on the other side',
      'Stand tall; keep the staff low, well clear of the head',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'basic',
  },
  {
    id: 'water.staff-wrist-wrap',
    element: 'water',
    name: 'Contact Staff Wrist Wrap',
    purpose: 'The first contact move: the staff wraps the wrist and returns.',
    dose: '10 each direction, each hand',
    cues: [
      'Over grass or soft ground, shoes on; expect drops at first',
      'From a slow one-hand rotor, open the hand and let the staff keep going',
      'It wraps over the back of the wrist, one full turn around it',
      'As it comes back round, close the hand on its centre; keep spinning',
      'Both directions, then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'basic',
  },
  {
    id: 'water.staff-forearm-rolls',
    element: 'water',
    name: 'Contact Staff Forearm Rolls',
    purpose: 'Rolls the staff along the arm. Every contact roll builds on it.',
    dose: '3 × 1 min each arm',
    cues: [
      'Over grass or soft ground, shoes on; a weighted staff will drop',
      'Arm out in front, palm up; lay the staff across it at its centre',
      'Raise the hand: it rolls to the elbow. Lower it: it rolls back',
      'Keep the arm level side to side, so the staff stays square to it',
      'Then palm to palm: roll it off one open hand onto the other',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.staff-front-figure-8',
    element: 'water',
    name: 'Staff Front Figure 8 (wall plane)',
    purpose: 'The figure 8 in front of you, in the wall plane.',
    dose: '3 × 1 min each hand',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'Forearm upright in front of the chest, the staff flat to the front',
      'One turn it passes left of the forearm, the next turn right of it',
      'Lead with the wrist, as at your side; keep the hand away from the face',
      'Forward and reverse, then the weaker hand; keep the plane flat',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-transitions',
    element: 'water',
    name: 'Staff Transitions (basic flow)',
    purpose: 'Links single moves without stopping between them.',
    dose: '3 × 2 min: change move every 8 counts',
    cues: [
      'Use three moves you know well: rotor, figure 8 and helicopter',
      'Eight counts each, changing at the end of a phrase',
      'Change at a point where both moves turn the same way',
      'Do not stop or reverse the staff at the change',
      'Once those three link, add the reverse figure 8 and the back pass',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-behind-head-pass',
    element: 'water',
    name: 'Staff Behind-the-Head Pass',
    purpose: 'The staff passes behind the head to the other hand.',
    dose: '3 × 2 min, passing both ways',
    cues: [
      'Walk-through first with the still staff, hand to hand behind the head',
      'From a rotor, lift the hand up and back; the staff turns behind you',
      'The other hand reaches up over its shoulder and takes the centre',
      'Tip the head a little forward; the staff turns a hand’s width behind it',
      'Out into a rotor on the new side, then pass it back',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-under-leg-pass',
    element: 'water',
    name: 'Staff Under-Leg Pass',
    purpose: 'The staff passes under a lifted thigh to the other hand.',
    dose: '3 × 1 min, alternating legs',
    cues: [
      'Walk-through first: lift a knee and hand the still staff underneath',
      'From figure 8s at your side, lift the knee toward hip height',
      'Hand the staff under the thigh to the other hand; keep it turning',
      'Stand tall on the standing leg; put the foot down softly',
      'Under the right leg, then the left, on a slow, steady count',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-palm-spin',
    element: 'water',
    name: 'Contact Staff Palm Spin',
    purpose: 'A staff spinning flat on an open palm, held only by balance.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Over grass or soft ground, shoes on: it will drop',
      'From a slow one-hand helicopter at chest height, open the hand flat',
      'The staff spins on the palm, its centre over the middle of the hand',
      'Make small palm moves to keep it centred; keep the palm level',
      'Close the thumb round it to take it back; then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-chest-roll',
    element: 'water',
    name: 'Contact Staff Chest Roll',
    purpose: 'Rolls the staff across the front of the body, arm to arm.',
    dose: '3 × 1 min, back and forth',
    cues: [
      'Learn forearm rolls first; a practice staff with soft or padded ends',
      'Arms open to the sides at shoulder height, chest lifted',
      'Roll it slowly along one arm, across the upper chest, onto the other',
      'More roll than spin; if an end rises toward the face, stop and catch it',
      'Catch it at the centre on the far arm, then roll it back',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
    tier: 'intermediate',
  },
  {
    id: 'water.staff-fishtails',
    element: 'water',
    name: 'Contact Staff Fishtails',
    purpose: 'A small figure 8 balanced on the back of the hand.',
    dose: '3 × 1 min each hand, reverse first',
    cues: [
      'Over grass or soft ground; reverse fishtails first, they are easier',
      'The staff rests across the back of the wrist at its centre; no grip',
      'Move the hand in small figure 8s; the staff swings in a figure 8 too',
      'Once the wrist version holds, move the contact to the back of the thumb',
      'Then forward fishtails, then the weaker hand',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.staff-360',
    element: 'water',
    name: 'Staff 360 (turning back pass)',
    purpose: 'The back pass with a full body turn, the staff still spinning.',
    dose: '3 × 1 min: a 360 every 8 counts',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'Learn the back pass both ways first',
      'Do the back pass and keep turning with it, a full circle',
      'Swap hands behind you as the body turns; keep the staff moving',
      'Look at the same point each turn; turn both ways',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
    tier: 'advanced',
  },
  {
    id: 'water.staff-behind-back-figure-8',
    element: 'water',
    name: 'Staff Figure 8 Behind the Back',
    purpose: 'Figure 8s behind your back, done by feel.',
    dose: '3 × 1 min each hand: forward, then reverse',
    cues: [
      'Practice props only; clear a staff length all round, and above',
      'From the back pass, keep the hand behind the back instead of passing',
      'Do figure 8s there, either side of the forearm, as at your side',
      'A few turns, then out to the side; build the count slowly',
      'Stand tall; keep the head still and the eyes forward',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.staff-isolations',
    element: 'water',
    name: 'Staff Isolations and Extensions',
    purpose:
      'Holds one point still, then circles the staff in line with the arm.',
    dose: '4 × 1 min: each hand, each direction',
    cues: [
      'Clear an arm plus a staff all round; grip a hand’s width from one end',
      'Isolation: flat to the front; keep the staff’s middle on one spot',
      'Circle the hand round that spot; let the staff turn in a loose grip',
      'Extension: hold the staff in line with the arm; the far end circles',
      'Go slow; watch the still point; both directions, then the other hand',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'advanced',
  },
  {
    id: 'water.staff-tosses',
    element: 'water',
    name: 'Staff Tosses (flat and upright)',
    purpose: 'Toss the staff, catch it and carry on spinning.',
    dose: '5 min: flat tosses, then upright tosses',
    cues: [
      'Clear 3 m (10 ft) all round, nothing overhead, nobody near; soft ground',
      'Flat first: from a slow helicopter at chest height, let go and catch',
      'Start 30 cm (1 ft) up; build to head height a little at a time',
      'Upright: from a rotor, let go as it rises; one turn, catch the centre',
      'Let a bad toss fall and step away; never reach for a falling end',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-halo-roll',
    element: 'water',
    name: 'Contact Staff Halo Roll',
    purpose: 'The first neck roll: shoulder to shoulder behind the neck.',
    dose: '10 each way, slow',
    cues: [
      'Learn chest rolls first; use your lightest practice staff',
      'Walk-through: both hands guide it across the back of the shoulders',
      'Keep the head still, chin slightly down; roll it shoulder to shoulder',
      'Go slow, with more roll than spin; add speed last',
      'Stop if it hits the head or the neck hurts; go back to the walk-through',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-angel-roll',
    element: 'water',
    name: 'Contact Staff Angel Roll',
    purpose: 'The halo roll extended down both arms: one turn, hand to hand.',
    dose: '10 each way',
    cues: [
      'Learn the halo roll both ways first; practice staff only',
      'Arms out wide at shoulder height',
      'Release with more roll than spin; it rolls up the arm to the neck',
      'At the neck, turn with it so it rolls onto the other arm and down',
      'Stop if it hits the head or the neck hurts; go back to halo rolls',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.staff-long-combination',
    element: 'water',
    name: 'Staff Long Combination',
    purpose:
      'Links six moves across three planes, then repeats them in a loop.',
    dose: '4 × the combination each side, then 3 min looped',
    cues: [
      'Pick six moves you know across three planes: side, front, overhead',
      'Learn it a link at a time: two moves, then three, then all six',
      'Keep the speed at each change; if it stalls, practise that link',
      'Lead with the weaker hand every other time through',
      'Then loop it for one track; keep going after any drop',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 600,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const STAFF_MOVES: Readonly<Record<string, MoveId>> = {
  'water.staff-rotor': 'staff',
  'water.staff-one-hand-rotor': 'staff',
  'water.staff-reverse-figure-8': 'staff',
  'water.staff-helicopter': 'staff',
  'water.staff-back-pass': 'staff',
  'water.staff-wrist-wrap': 'staff',
  'water.staff-forearm-rolls': 'staff',
  'water.staff-front-figure-8': 'staff',
  'water.staff-transitions': 'staff',
  'water.staff-behind-head-pass': 'staff',
  'water.staff-under-leg-pass': 'staff',
  'water.staff-palm-spin': 'staff',
  'water.staff-chest-roll': 'staff',
  'water.staff-fishtails': 'staff',
  'water.staff-360': 'staff',
  'water.staff-behind-back-figure-8': 'staff',
  'water.staff-isolations': 'staff',
  'water.staff-tosses': 'staff',
  'water.staff-halo-roll': 'staff',
  'water.staff-angel-roll': 'staff',
  'water.staff-long-combination': 'staff',
};

export const DOUBLE_STAFF_DRILLS: Exercise[] = [
  // ─── Basic ─────────────────────────────────────────────────────────────
  {
    id: 'water.double-staff-side-spins',
    element: 'water',
    name: 'Double Staff Side Spins (wheel plane)',
    purpose:
      'Two staffs spinning beside you, in together time, then split time.',
    dose: '4 × 1 min: together and split, each direction',
    cues: [
      'Practice props only; clear arm plus staff all round, and above',
      'A staff in each hand, held at the centre, spinning beside you',
      'Both forward in together time: the staffs move in step',
      'Split time is a quarter turn: one staff upright while one is flat',
      'Then backward; hands just outside the hips, elbows soft',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.double-staff-figure-8s',
    element: 'water',
    name: 'Double Staff Figure 8s (same direction)',
    purpose: 'The single-staff figure 8 in both hands at once.',
    dose: '4 × 1 min: forward and reverse, together and split',
    cues: [
      'Each hand does a figure 8 at its own side, both staffs forward',
      'One circle passes inside each arm, the next passes outside it',
      'Together time first, then split time: a quarter turn apart',
      'Elbows near the ribs; the inside circles pass between arm and body',
      'Then both in reverse',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.double-staff-opposite-8s',
    element: 'water',
    name: 'Double Staff Figure 8s (opposite directions)',
    purpose: 'Figure 8s with one hand forward and the other in reverse.',
    dose: '4 × 1 min, swapping which hand goes forward',
    cues: [
      'Learn forward and reverse figure 8s in each hand first',
      'Start the forward hand alone for 8 counts, then add the reverse hand',
      'Count out loud; go at the speed of the weaker direction',
      'If one stalls, stop both and restart the count slowly',
      'Swap: the other hand forward, the first in reverse',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },
  {
    id: 'water.double-staff-helicopters',
    element: 'water',
    name: 'Double Staff Helicopters',
    purpose: 'Two flat spins above your head, one in each hand.',
    dose: '4 × 1 min: same way, then mirrored',
    cues: [
      'Clear overhead: nothing within a staff length above your hands',
      'Both arms up, a staff in each hand, spinning flat above you',
      'Keep the hands wide apart so the ends never meet',
      'Same way first, then mirrored: the staffs turn opposite ways',
      'Head still, shoulders down, elbows soft; switch direction each set',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'basic',
  },

  // ─── Intermediate ──────────────────────────────────────────────────────
  {
    id: 'water.double-staff-flowers',
    element: 'water',
    name: 'Double Staff Flowers (inspin)',
    purpose: 'Big, straight-arm circles with the staffs turning inside them.',
    dose: '4 × 1 min, alternating direction',
    cues: [
      'Practice props only; clear arm plus staff all round, and above',
      'Arms straight, each drawing a big circle at its own side',
      'Inspin: each staff spins the same way its arm circles',
      'Keep the count: the same number of staff turns in each arm circle',
      'Together time first, then split time; then both backward',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'intermediate',
  },
  {
    id: 'water.double-staff-two-beat-weave',
    element: 'water',
    name: 'Double Staff Two-Beat Weave',
    purpose:
      'Both staffs on one side, then the other, arms crossing each beat.',
    dose: '3 × 2 min: forward, reverse, forward',
    cues: [
      'Both staffs spin forward on the same side of the body',
      'One arm crosses over the other to put both staffs on that side',
      'Each beat both move to the other side; the arms cross the other way',
      'Slow, even count; hands near the chest, shoulders loose',
      'If the staffs touch, spread the hands and slow the count',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 420,
    tier: 'intermediate',
  },
  {
    id: 'water.double-staff-isolations',
    element: 'water',
    name: 'Double Staff Isolations',
    purpose: 'Turns the staff round one point that stays still in the air.',
    dose: '2 min each hand, then 2 min with both',
    cues: [
      'One staff first, held at the centre, flat to the front',
      'Pick one end and keep it on one spot in the air',
      'Circle the hand round that spot; the staff turns once each circle',
      'Wall plane first, then the wheel plane beside you',
      'Then a staff in each hand, mirrored; slow, both directions',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },
  {
    id: 'water.double-staff-antispin',
    element: 'water',
    name: 'Double Staff Antispin',
    purpose: 'Arms circle one way while the staffs spin the other.',
    dose: '2 min each hand, then 2 min with both',
    cues: [
      'One staff first, flat to the front, held at the centre',
      'Circle the hand one way; spin the staff the other way',
      'Count the staff turns in each circle and keep that count the same',
      'Small, slow circles first; widen them once the count holds',
      'Then both staffs mirrored, then both the same way',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 360,
    tier: 'intermediate',
  },

  // ─── Advanced ──────────────────────────────────────────────────────────
  {
    id: 'water.double-staff-flower-turns',
    element: 'water',
    name: 'Double Staff Flowers with Turns',
    purpose: 'Keeps the flowers going through a full turn of the body.',
    dose: '4 × 1 min: a turn every 8 counts, each way',
    cues: [
      'Learn mirrored flowers first: the staffs turning opposite ways',
      'Walk the turn slowly in small steps; keep the flowers going',
      'The planes turn with you; arms and staffs keep their circles',
      'Look at the same point each turn; finish facing it',
      'Turn both ways; do an extra set on the weaker way',
    ],
    targets: ['Flow', 'Coordination', 'Agility', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 270,
    tier: 'advanced',
  },
  {
    id: 'water.double-staff-hybrids',
    element: 'water',
    name: 'Double Staff Hybrids (isolation and antispin)',
    purpose: 'One hand isolates while the other antispins, in one plane.',
    dose: '3 × 1 min each way round',
    cues: [
      'Learn isolations and antispins in each hand first',
      'Both staffs flat to the front, hands at chest height, wide apart',
      'Start the isolation alone for 8 counts, then add the antispin',
      'Same timing: both hands finish a circle together',
      'Swap hands: the other one isolates',
    ],
    targets: ['Flow', 'Coordination', 'Grip', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 390,
    tier: 'advanced',
  },
  {
    id: 'water.double-staff-throws',
    element: 'water',
    name: 'Double Staff Throws',
    purpose: 'Sends one staff up while the other keeps spinning.',
    dose: '5 min: 10 throws each hand, then alternating',
    cues: [
      'Clear 3 m (10 ft) all round, nothing overhead, nobody near; soft ground',
      'Both staffs spinning; one goes up while the other keeps turning',
      'Small first: one turn, no higher than the head; catch the centre',
      'Go straight back into the pattern as you catch',
      'Let a bad throw fall and step away; never reach for a falling end',
    ],
    targets: ['Flow', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
  {
    id: 'water.double-staff-flow-round',
    element: 'water',
    name: 'Double Staff Flow Round',
    purpose: 'Links every double staff move into one track, in every plane.',
    dose: '1 track (3–5 min)',
    cues: [
      'Practice props only; clear arm plus staff all round, and above',
      'Use every plane in the track: side, front and overhead',
      'Weaves, windmills, flowers, isolations; change on the phrase',
      'Add a turn in every section; throw only if the space is clear',
      'After a drop, go straight into the next move; do not restart',
    ],
    targets: ['Flow', 'Coordination', 'Presence', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
    tier: 'advanced',
  },
];

/** Pictogram and limit class for each move. */
export const DOUBLE_STAFF_MOVES: Readonly<Record<string, MoveId>> = {
  'water.double-staff-side-spins': 'staff',
  'water.double-staff-figure-8s': 'staff',
  'water.double-staff-opposite-8s': 'staff',
  'water.double-staff-helicopters': 'staff',
  'water.double-staff-flowers': 'staff',
  'water.double-staff-two-beat-weave': 'staff',
  'water.double-staff-isolations': 'staff',
  'water.double-staff-antispin': 'staff',
  'water.double-staff-flower-turns': 'staff',
  'water.double-staff-hybrids': 'staff',
  'water.double-staff-throws': 'staff',
  'water.double-staff-flow-round': 'staff',
};
