import type {Exercise} from '../types';

/**
 * Drills for things a person carries from place to place: a resistance
 * band, a skipping rope, a ball, water jugs, a sandbag.
 *
 * Each is gated by kit in `domain/profile/kit.ts`, so nobody without the
 * thing is ever offered it.
 *
 * Added 21 Sep 2026.
 */
export const CARRIED_DRILLS: Exercise[] = [
  // ─── Resistance band ───────────────────────────────────────────────────
  {
    id: 'air.band-pull-apart',
    element: 'air',
    name: 'Band Pull-Aparts',
    purpose:
      'Strengthens the mid back and rear shoulders, which sitting weakens.',
    dose: '3 × 15',
    cues: [
      'Arms straight out at shoulder height, hands shoulder-width on the band',
      'Pull the band apart until it touches the chest',
      'Squeeze the shoulder blades together; keep the shoulders down',
      'Return slowly; do not let the band pull your arms back',
    ],
    targets: ['UCS', 'Strength', 'NoFloor'],
    venues: ['desk', 'standing'],
    approxSeconds: 120,
  },
  {
    id: 'air.band-face-pull',
    element: 'air',
    name: 'Band Face Pulls',
    purpose: 'Pulls the shoulders back and turns them out to counter hunching.',
    dose: '3 × 12',
    cues: [
      'Anchor the band at face height: a post, a railing or a playground bar',
      'In a door: knot on the hinge side, door shut and opening away from you',
      'Step back until the band is tight; pull it to your face',
      'Keep the elbows high and wide; finish with thumbs back by the ears',
      'Pause a second, then return slowly; keep ribs down, do not lean back',
    ],
    targets: ['UCS', 'Strength', 'NoFloor'],
    venues: ['standing'],
    approxSeconds: 150,
  },
  {
    id: 'air.band-dislocate',
    element: 'air',
    name: 'Shoulder Pass-Throughs',
    purpose: 'Moves the shoulders through full range to loosen a tight chest.',
    dose: '2 × 10 slow reps',
    cues: [
      'Use a band or a staff; hold it much wider than your shoulders',
      'Arms straight, lift it up over the head and back behind you',
      'Bring it back over the same way; ribs down, do not arch the low back',
      'Narrow the grip a little only when the pass feels easy',
      'Do not force it; if an elbow bends or a shoulder pinches, go wider',
    ],
    targets: ['Mobility', 'UCS', 'NoFloor'],
    venues: ['standing'],
    approxSeconds: 90,
  },
  {
    id: 'earth.banded-glute-bridge',
    element: 'earth',
    name: 'Banded Glute Bridge',
    purpose: 'Works the side glutes and trains your knees to stay out.',
    dose: '3 × 12',
    cues: [
      'Band just above the knees, feet flat and hip-width apart',
      'Press the knees out against the band and keep them there',
      'Ribs down, tilt the pelvis under, then drive up through the heels',
      'Squeeze the glutes for a second at the top; lower slowly',
    ],
    targets: ['APT', 'Strength'],
    venues: ['mat'],
    approxSeconds: 150,
  },
  {
    id: 'earth.band-clamshell',
    element: 'earth',
    name: 'Band Clamshells',
    purpose:
      'Strengthens the side glute, which keeps the pelvis steady as you walk.',
    dose: '2 × 15 each side',
    cues: [
      'Lie on your side, band just above the knees, knees bent, heels together',
      'Stack the hips; rest a hand on the top hip to keep it still',
      'Open the top knee without letting the pelvis roll back',
      'Pause at the top, close slowly; stop before the hip starts to turn',
    ],
    targets: ['APT', 'Strength'],
    venues: ['mat'],
    approxSeconds: 180,
  },
  {
    id: 'earth.band-lateral-walk',
    element: 'earth',
    name: 'Band Lateral Walk',
    purpose:
      'Strengthens the side hips to keep the knees aligned and pelvis level.',
    dose: '3 × 10 steps each way',
    cues: [
      'Band just above the knees; around the ankles is harder',
      'Half-squat, chest up, toes pointing forward',
      'Step sideways, then bring the other foot in without losing tension',
      'Do not let the feet touch or the knees cave in; go both directions',
    ],
    targets: ['APT', 'Strength', 'NoFloor'],
    venues: ['standing', 'house'],
    approxSeconds: 150,
  },
  {
    id: 'fire.band-row',
    element: 'fire',
    name: 'Seated Band Row',
    purpose:
      'Builds upper-back pulling strength without anything to hang from.',
    dose: '3 × 12',
    cues: [
      'Sit tall, legs straight, band looped around the soles of the feet',
      'Hold the ends with the arms long; shorten the band to make it harder',
      'Row the hands to the lower ribs, elbows close to the body',
      'Shoulder blades back and down; pause a second',
      'Stay upright; do not lean back to finish the rep',
    ],
    targets: ['Strength', 'UCS'],
    venues: ['mat'],
    approxSeconds: 150,
  },
  {
    id: 'fire.band-pushup',
    element: 'fire',
    name: 'Banded Push-Ups',
    purpose: 'Adds resistance at the top of the push-up, where it is easiest.',
    dose: '3 × 8',
    cues: [
      'Band across the upper back, an end pinned under each hand',
      'Hands under the shoulders, body in one straight line',
      'Lower until the chest is a fist from the floor; press to locked arms',
      'Push the floor away at the top so the shoulder blades spread',
      'If your form slips, drop the band and finish with plain push-ups',
    ],
    targets: ['Strength', 'PFT-Pushups'],
    venues: ['mat'],
    approxSeconds: 150,
  },
  {
    id: 'fire.band-assisted-pullup',
    element: 'fire',
    name: 'Band-Assisted Pull-Ups',
    purpose: 'The band assists full pull-ups until you can do one alone.',
    dose: '4 × 5',
    cues: [
      'Test the hang point first: load it with your feet still down',
      'Loop the band over a high bar or beam and back through itself',
      'From a stable step or chair, put a foot or a knee in the loop',
      'Start from a full hang; pull until the chin passes the bar or beam',
      'Lower slowly to a full hang; ease out of the loop so it cannot snap',
    ],
    targets: ['Strength', 'Grip'],
    venues: ['porch'],
    approxSeconds: 240,
  },

  // ─── Skipping rope ─────────────────────────────────────────────────────
  {
    id: 'fire.skip-rope',
    element: 'fire',
    name: 'Skipping Rope',
    purpose: 'Builds ankle spring and raises your heart rate.',
    dose: '3 × 1 min',
    cues: [
      'Check for clear space overhead and all around the rope',
      'Keep your elbows by your ribs; turn the rope with your wrists',
      'Small hops on the balls of the feet, just high enough to clear it',
      'Let the heels touch down lightly, never slam; stay tall and relaxed',
    ],
    targets: ['Conditioning', 'Agility', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 240,
  },
  {
    id: 'fire.skip-rope-intervals',
    element: 'fire',
    name: 'Skipping Intervals',
    purpose: 'Hard rounds and short rests build fitness in about ten minutes.',
    dose: '8 rounds: 30 sec on, 30 sec off',
    cues: [
      'Check for clear space overhead; warm up with 1 min of easy bouncing',
      'On: skip as fast as you can while staying smooth',
      'Off: let the rope hang, walk, and breathe through the nose',
      'If you trip, reset and keep going; the timer does not stop',
      'Stop early if your form breaks down in the last rounds',
    ],
    targets: ['Conditioning', 'Agility', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 540,
  },
  {
    id: 'air.boxer-skip',
    element: 'air',
    name: 'Boxer Skip',
    purpose: 'A steady foot-to-foot skip you can keep up with nose breathing.',
    dose: '3 × 2 min',
    cues: [
      'Check for clear space overhead; start with a few basic bounces',
      'Shift your weight onto one foot, then the other: one rope pass each',
      'Keep it low and quiet; the free foot barely leaves the ground',
      'Shoulders loose and down, elbows in, wrists turning the rope',
      'Breathe through your nose; if you need your mouth, slow down',
    ],
    targets: ['Agility', 'Coordination', 'Conditioning', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 450,
  },
  {
    id: 'fire.double-under-progression',
    element: 'fire',
    name: 'Double-Under Progression',
    purpose: 'Learn two rope passes per jump, one attempt at a time.',
    dose: '10 single attempts over 5 min',
    cues: [
      'Check the space overhead, then start a basic bounce',
      'Every few bounces, hop a little higher and turn the wrists faster',
      'Try to pass the rope twice under that hop, then go back to basic bounce',
      'Stay tall with legs nearly straight; do not pike or tuck the knees',
      'Stop when your attempts get sloppy',
    ],
    targets: ['Agility', 'Conditioning', 'Coordination', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 300,
  },

  // ─── Ball ──────────────────────────────────────────────────────────────
  {
    id: 'air.ball-pec-release',
    element: 'air',
    name: 'Ball Pec Release',
    purpose:
      'Loosens pec minor, the chest muscle that pulls the shoulder forward.',
    dose: '60 sec each side',
    cues: [
      'Face a wall or doorframe, ball just under the collarbone, armpit side',
      'Lean in until it is tender but not sharp; breathe slowly',
      'Slide the arm slowly up and down the wall to work into the spot',
      'Keep off the armpit and collarbone; if you feel tingling, move the ball',
    ],
    targets: ['UCS', 'Mobility', 'NoFloor'],
    venues: ['wall'],
    approxSeconds: 150,
  },
  {
    id: 'water.ball-glute-release',
    element: 'water',
    name: 'Ball Glute Release',
    purpose: 'Loosens the deep hip muscles that tighten from long sitting.',
    dose: '90 sec each side',
    cues: [
      'Sit with the ball under one glute, hands behind you on the mat',
      'Cross that ankle over the other knee to reach the muscle',
      'Roll slowly; pause on a tender spot and breathe until it eases',
      'Keep off the sit bone and spine; if the leg tingles, move the ball',
    ],
    targets: ['Mobility', 'APT'],
    venues: ['mat'],
    approxSeconds: 210,
  },

  // ─── Water jugs ────────────────────────────────────────────────────────
  {
    id: 'earth.jug-farmer-carry',
    element: 'earth',
    name: 'Jug Farmer Carry',
    purpose: 'Builds grip, core and posture using water jugs.',
    dose: '4 × 30 m (100 ft)',
    cues: [
      'Caps tight; a full 4 L (1 gal) jug in each hand, about 4 kg (9 lb)',
      'Stand tall, shoulders down and back, arms long at the sides',
      'Short, quick steps; ribs down, breathe normally',
      'To make it harder, walk farther or stand still for 20 sec mid-lap',
    ],
    targets: ['Grip', 'Strength', 'Core', 'NoFloor'],
    venues: ['yard', 'house', 'neighborhood'],
    approxSeconds: 240,
  },
  {
    id: 'earth.jug-goblet-squat',
    element: 'earth',
    name: 'Jug Goblet Squat',
    purpose:
      'Weight at your chest keeps you upright and helps you squat deeper.',
    dose: '3 × 12',
    cues: [
      'Caps tight; hug one full jug at the chest, hands on its sides',
      'Feet a little wider than the hips, toes turned out slightly',
      'Sit down between the heels, elbows inside the knees',
      'Chest up, heels down; stand by pushing through your feet',
    ],
    targets: ['Strength', 'NoFloor'],
    venues: ['standing'],
    approxSeconds: 150,
  },
  {
    id: 'fire.jug-row',
    element: 'fire',
    name: 'Jug Bent-Over Row',
    purpose:
      'Strengthens the upper back that holds the shoulders back all day.',
    dose: '3 × 12',
    cues: [
      'A jug in each hand; soft knees, hinge at the hips, back flat',
      'Arms hang straight down, neck long, eyes on the floor ahead',
      'Row the jugs to the hips, elbows brushing the sides',
      'Pause a second with the shoulder blades squeezed; lower slowly',
    ],
    targets: ['Strength', 'UCS', 'NoFloor'],
    venues: ['standing'],
    approxSeconds: 150,
  },

  // ─── Sandbag ───────────────────────────────────────────────────────────
  {
    id: 'earth.sandbag-bear-hug-carry',
    element: 'earth',
    name: 'Sandbag Bear Hug Carry',
    purpose: 'Trains your whole trunk to brace under an awkward load.',
    dose: '4 × 30 m (100 ft)',
    cues: [
      'Squat down to the bag and lift it with the legs, back flat',
      'Hug it high on the chest, arms wrapped all the way around',
      'Walk tall and brace your trunk firmly',
      'Take short breaths and keep your belly firm',
      'Lower it the same way you lifted it',
    ],
    targets: ['Strength', 'Core', 'Grip', 'NoFloor'],
    venues: ['yard', 'neighborhood'],
    approxSeconds: 240,
  },
  {
    id: 'earth.sandbag-zercher-squat',
    element: 'earth',
    name: 'Sandbag Zercher Squat',
    purpose: 'Load in the elbows keeps you upright and works your trunk.',
    dose: '3 × 8',
    cues: [
      'From a squat, roll the bag onto the thighs, then into the elbows',
      'Hands clasped, bag held tight to the body, chest up',
      'Brace, then squat as deep as you can with your torso upright',
      'Stand by driving through the whole foot',
      'If your elbows hurt, wrap the bag in a towel or wear long sleeves',
    ],
    targets: ['Strength', 'Core', 'NoFloor'],
    venues: ['yard', 'standing'],
    approxSeconds: 180,
  },
  {
    id: 'fire.sandbag-shouldering',
    element: 'fire',
    name: 'Sandbag Shouldering',
    purpose:
      'Builds hip power for lifting awkward loads from floor to shoulder.',
    dose: '3 × 6 (alternating shoulders)',
    cues: [
      'Straddle the bag, hinge down with a flat back, hands underneath it',
      'Pull it up onto the thighs, then drive the hips forward hard',
      'Drive the hips to lift it onto one shoulder; the arms only guide it',
      'Lower it under control; never drop it on anything that could break',
      'Alternate shoulders each rep; stop when your arms start doing the lift',
    ],
    targets: ['Strength', 'Conditioning'],
    venues: ['yard'],
    approxSeconds: 240,
  },
];
